hostname sb078.cluster
ipconfig 1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN group default qlen 1000 link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00 inet 127.0.0.1/8 scope host lo valid_lft forever preferred_lft forever inet6 ::1/128 scope host valid_lft forever preferred_lft forever 2: enp4s0f0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 9000 qdisc mq state UP group default qlen 1000 link/ether a0:8c:f8:74:c9:18 brd ff:ff:ff:ff:ff:ff inet 10.3.81.158/22 brd 10.3.83.255 scope global enp4s0f0 valid_lft forever preferred_lft forever inet6 fe80::a28c:f8ff:fe74:c918/64 scope link valid_lft forever preferred_lft forever 3: enp4s0f1: <BROADCAST,MULTICAST> mtu 1500 qdisc noop state DOWN group default qlen 1000 link/ether a0:8c:f8:74:c9:19 brd ff:ff:ff:ff:ff:ff 4: enp4s0f2: <BROADCAST,MULTICAST> mtu 1500 qdisc noop state DOWN group default qlen 1000 link/ether a0:8c:f8:74:c9:1a brd ff:ff:ff:ff:ff:ff 5: enp4s0f3: <BROADCAST,MULTICAST> mtu 1500 qdisc noop state DOWN group default qlen 1000 link/ether a0:8c:f8:74:c9:1b brd ff:ff:ff:ff:ff:ff 6: ib0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 4092 qdisc pfifo_fast state UP group default qlen 256 link/infiniband 80:00:00:29:fe:80:00:00:00:00:00:00:38:bc:01:03:00:4c:f2:10 brd 00:ff:ff:ff:ff:12:40:1b:ff:ff:00:00:00:00:00:00:ff:ff:ff:ff inet 10.3.89.158/22 brd 10.3.91.255 scope global ib0 valid_lft forever preferred_lft forever inet 10.3.97.158/22 brd 10.3.99.255 scope global ib0:1 valid_lft forever preferred_lft forever inet6 fe80::3abc:103:4c:f210/64 scope link valid_lft forever preferred_lft forever 7: ib1: <NO-CARRIER,BROADCAST,MULTICAST,UP> mtu 4092 qdisc pfifo_fast state DOWN group default qlen 256 link/infiniband 80:00:00:29:fe:80:00:00:00:00:00:00:38:bc:01:03:00:4c:f2:11 brd 00:ff:ff:ff:ff:12:40:1b:ff:ff:00:00:00:00:00:00:ff:ff:ff:ff
2024-02-01 08:16:13,534 - distributed.nanny - INFO -         Start Nanny at: 'tcp://10.3.89.158:45507'
2024-02-01 08:16:15,804 - distributed.diskutils - INFO - Found stale lock file and directory '/scratch/dask-worker-space/worker-x12edol8', purging
2024-02-01 08:16:19,670 - distributed.worker - INFO -       Start worker at:    tcp://10.3.89.158:33341
2024-02-01 08:16:19,672 - distributed.worker - INFO -          Listening to:    tcp://10.3.89.158:33341
2024-02-01 08:16:19,672 - distributed.worker - INFO -           Worker name:           SLURMCluster-203
2024-02-01 08:16:19,672 - distributed.worker - INFO -          dashboard at:          10.3.89.158:38450
2024-02-01 08:16:19,672 - distributed.worker - INFO - Waiting to connect to:     tcp://10.3.88.11:37020
2024-02-01 08:16:19,672 - distributed.worker - INFO - -------------------------------------------------
2024-02-01 08:16:19,672 - distributed.worker - INFO -               Threads:                          2
2024-02-01 08:16:19,672 - distributed.worker - INFO -                Memory:                  20.49 GiB
2024-02-01 08:16:19,672 - distributed.worker - INFO -       Local Directory: /scratch/dask-worker-space/worker-67ce5gxy
2024-02-01 08:16:19,672 - distributed.worker - INFO - -------------------------------------------------
2024-02-01 08:16:19,718 - distributed.worker - INFO -         Registered to:     tcp://10.3.88.11:37020
2024-02-01 08:16:19,718 - distributed.worker - INFO - -------------------------------------------------
2024-02-01 08:16:19,719 - distributed.core - INFO - Starting established connection to tcp://10.3.88.11:37020
2024-02-01 08:17:44,635 - distributed.core - INFO - Event loop was unresponsive in Worker for 5.30s.  This is often caused by long-running GIL-holding functions or moving large chunks of data. This can cause timeouts and instability.
2024-02-01 08:35:11,355 - distributed.core - INFO - Event loop was unresponsive in Worker for 3.32s.  This is often caused by long-running GIL-holding functions or moving large chunks of data. This can cause timeouts and instability.
2024-02-01 08:35:38,026 - distributed.worker - ERROR - Worker stream died during communication: tcp://10.3.89.95:36040
Traceback (most recent call last):
  File "/mnt/storage/nobackup/nmb1063/mamba/envs/fegrow/lib/python3.9/site-packages/distributed/comm/tcp.py", line 225, in read
    frames_nbytes = await stream.read_bytes(fmt_size)
asyncio.exceptions.CancelledError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/mnt/storage/nobackup/nmb1063/mamba/envs/fegrow/lib/python3.9/asyncio/tasks.py", line 490, in wait_for
    return fut.result()
asyncio.exceptions.CancelledError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/mnt/storage/nobackup/nmb1063/mamba/envs/fegrow/lib/python3.9/site-packages/distributed/comm/core.py", line 328, in connect
    handshake = await asyncio.wait_for(comm.read(), time_left())
  File "/mnt/storage/nobackup/nmb1063/mamba/envs/fegrow/lib/python3.9/asyncio/tasks.py", line 492, in wait_for
    raise exceptions.TimeoutError() from exc
asyncio.exceptions.TimeoutError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/mnt/storage/nobackup/nmb1063/mamba/envs/fegrow/lib/python3.9/site-packages/distributed/worker.py", line 2081, in gather_dep
    response = await get_data_from_worker(
  File "/mnt/storage/nobackup/nmb1063/mamba/envs/fegrow/lib/python3.9/site-packages/distributed/worker.py", line 2900, in get_data_from_worker
    comm = await rpc.connect(worker)
  File "/mnt/storage/nobackup/nmb1063/mamba/envs/fegrow/lib/python3.9/site-packages/distributed/core.py", line 1468, in connect
    return await connect_attempt
  File "/mnt/storage/nobackup/nmb1063/mamba/envs/fegrow/lib/python3.9/site-packages/distributed/core.py", line 1389, in _connect
    comm = await connect(
  File "/mnt/storage/nobackup/nmb1063/mamba/envs/fegrow/lib/python3.9/site-packages/distributed/comm/core.py", line 333, in connect
    raise OSError(
OSError: Timed out during handshake while connecting to tcp://10.3.89.95:36040 after 30 s
2024-02-01 08:36:08,055 - distributed.worker - ERROR - Worker stream died during communication: tcp://10.3.89.93:44896
Traceback (most recent call last):
  File "/mnt/storage/nobackup/nmb1063/mamba/envs/fegrow/lib/python3.9/site-packages/distributed/comm/tcp.py", line 225, in read
    frames_nbytes = await stream.read_bytes(fmt_size)
asyncio.exceptions.CancelledError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/mnt/storage/nobackup/nmb1063/mamba/envs/fegrow/lib/python3.9/asyncio/tasks.py", line 490, in wait_for
    return fut.result()
asyncio.exceptions.CancelledError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/mnt/storage/nobackup/nmb1063/mamba/envs/fegrow/lib/python3.9/site-packages/distributed/comm/core.py", line 328, in connect
    handshake = await asyncio.wait_for(comm.read(), time_left())
  File "/mnt/storage/nobackup/nmb1063/mamba/envs/fegrow/lib/python3.9/asyncio/tasks.py", line 492, in wait_for
    raise exceptions.TimeoutError() from exc
asyncio.exceptions.TimeoutError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/mnt/storage/nobackup/nmb1063/mamba/envs/fegrow/lib/python3.9/site-packages/distributed/worker.py", line 2081, in gather_dep
    response = await get_data_from_worker(
  File "/mnt/storage/nobackup/nmb1063/mamba/envs/fegrow/lib/python3.9/site-packages/distributed/worker.py", line 2900, in get_data_from_worker
    comm = await rpc.connect(worker)
  File "/mnt/storage/nobackup/nmb1063/mamba/envs/fegrow/lib/python3.9/site-packages/distributed/core.py", line 1468, in connect
    return await connect_attempt
  File "/mnt/storage/nobackup/nmb1063/mamba/envs/fegrow/lib/python3.9/site-packages/distributed/core.py", line 1389, in _connect
    comm = await connect(
  File "/mnt/storage/nobackup/nmb1063/mamba/envs/fegrow/lib/python3.9/site-packages/distributed/comm/core.py", line 333, in connect
    raise OSError(
OSError: Timed out during handshake while connecting to tcp://10.3.89.93:44896 after 30 s
2024-02-01 08:36:39,726 - distributed.worker - ERROR - Worker stream died during communication: tcp://10.3.89.95:36040
Traceback (most recent call last):
  File "/mnt/storage/nobackup/nmb1063/mamba/envs/fegrow/lib/python3.9/site-packages/distributed/comm/tcp.py", line 225, in read
    frames_nbytes = await stream.read_bytes(fmt_size)
asyncio.exceptions.CancelledError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/mnt/storage/nobackup/nmb1063/mamba/envs/fegrow/lib/python3.9/asyncio/tasks.py", line 490, in wait_for
    return fut.result()
asyncio.exceptions.CancelledError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/mnt/storage/nobackup/nmb1063/mamba/envs/fegrow/lib/python3.9/site-packages/distributed/comm/core.py", line 328, in connect
    handshake = await asyncio.wait_for(comm.read(), time_left())
  File "/mnt/storage/nobackup/nmb1063/mamba/envs/fegrow/lib/python3.9/asyncio/tasks.py", line 492, in wait_for
    raise exceptions.TimeoutError() from exc
asyncio.exceptions.TimeoutError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/mnt/storage/nobackup/nmb1063/mamba/envs/fegrow/lib/python3.9/site-packages/distributed/worker.py", line 2081, in gather_dep
    response = await get_data_from_worker(
  File "/mnt/storage/nobackup/nmb1063/mamba/envs/fegrow/lib/python3.9/site-packages/distributed/worker.py", line 2900, in get_data_from_worker
    comm = await rpc.connect(worker)
  File "/mnt/storage/nobackup/nmb1063/mamba/envs/fegrow/lib/python3.9/site-packages/distributed/core.py", line 1468, in connect
    return await connect_attempt
  File "/mnt/storage/nobackup/nmb1063/mamba/envs/fegrow/lib/python3.9/site-packages/distributed/core.py", line 1389, in _connect
    comm = await connect(
  File "/mnt/storage/nobackup/nmb1063/mamba/envs/fegrow/lib/python3.9/site-packages/distributed/comm/core.py", line 333, in connect
    raise OSError(
OSError: Timed out during handshake while connecting to tcp://10.3.89.95:36040 after 30 s
2024-02-01 08:36:57,711 - distributed.core - INFO - Event loop was unresponsive in Worker for 15.63s.  This is often caused by long-running GIL-holding functions or moving large chunks of data. This can cause timeouts and instability.
2024-02-01 08:36:57,711 [INFO] [core.py:595] distributed.core: Event loop was unresponsive in Worker for 15.63s.  This is often caused by long-running GIL-holding functions or moving large chunks of data. This can cause timeouts and instability.
/mnt/storage/nobackup/nmb1063/mamba/envs/fegrow/lib/python3.9/site-packages/parmed/structure.py:1775: UnitStrippedWarning: The unit of the quantity is stripped when downcasting to ndarray.
  coords = np.array(value, dtype=np.float64, copy=False, subok=True)
/mnt/storage/nobackup/nmb1063/mamba/envs/fegrow/lib/python3.9/site-packages/torchani/__init__.py:55: UserWarning: Dependency not satisfied, torchani.ase will not be available
  warnings.warn("Dependency not satisfied, torchani.ase will not be available")
2024-02-01 08:37:37,275 [WARNING] [__init__.py:5] root: Warning: importing 'simtk.openmm' is deprecated.  Import 'openmm' instead.
TIME changed dir: 0.0s
TIME changed dir: 0.0s
Generated 19 conformers. 
Removed 6 conformers. 
Generated 8 conformers. 
Removed 6 conformers. 
using ani2x
/mnt/storage/nobackup/nmb1063/mamba/envs/fegrow/lib/python3.9/site-packages/torchani/resources/
failed to equip `nnpops` with error: No module named 'NNPOps'
Optimising conformer:   0%|                               | 0/2 [00:00<?, ?it/s][W BinaryOps.cpp:601] Warning: floor_divide is deprecated, and will be removed in a future version of pytorch. It currently rounds toward 0 (like the 'trunc' function NOT 'floor'). This results in incorrect rounding for negative values.
To keep the current behavior, use torch.div(a, b, rounding_mode='trunc'), or for actual floor division, use torch.div(a, b, rounding_mode='floor'). (function operator())
Optimising conformer:  50%|███████████▌           | 1/2 [00:04<00:04,  4.19s/it]Optimising conformer: 100%|███████████████████████| 2/2 [00:06<00:00,  3.27s/it]Optimising conformer: 100%|███████████████████████| 2/2 [00:06<00:00,  3.41s/it]
/mnt/storage/nobackup/nmb1063/code/gal/sars-cov-2-main-protease-al-study-combo1/rsearcher.py:89: UserWarning: The ligand was an array (SDF?). Using the first frame. 
  warnings.warn("The ligand was an array (SDF?). Using the first frame. ")
/mnt/storage/nobackup/nmb1063/mamba/envs/fegrow/lib/python3.9/site-packages/parmed/structure.py:1775: UnitStrippedWarning: The unit of the quantity is stripped when downcasting to ndarray.
  coords = np.array(value, dtype=np.float64, copy=False, subok=True)
TIME Completed the molecule generation in 63.1s.
TIME changed dir: 0.0s
Generated 32 conformers. 
Removed 27 conformers. 
using ani2x
/mnt/storage/nobackup/nmb1063/mamba/envs/fegrow/lib/python3.9/site-packages/torchani/resources/
failed to equip `nnpops` with error: No module named 'NNPOps'
Optimising conformer:   0%|                              | 0/13 [00:00<?, ?it/s]Optimising conformer:   8%|█▋                    | 1/13 [00:03<00:39,  3.31s/it]Optimising conformer:  15%|███▍                  | 2/13 [00:06<00:33,  3.07s/it]Optimising conformer:  23%|█████                 | 3/13 [00:11<00:41,  4.16s/it]Optimising conformer:  31%|██████▊               | 4/13 [00:16<00:38,  4.24s/it]Optimising conformer:  38%|████████▍             | 5/13 [00:18<00:29,  3.69s/it]Optimising conformer:  46%|██████████▏           | 6/13 [00:23<00:27,  3.96s/it]Optimising conformer:  54%|███████████▊          | 7/13 [00:26<00:22,  3.82s/it]Optimising conformer:  62%|█████████████▌        | 8/13 [00:29<00:17,  3.45s/it]using ani2x
/mnt/storage/nobackup/nmb1063/mamba/envs/fegrow/lib/python3.9/site-packages/torchani/resources/
failed to equip `nnpops` with error: No module named 'NNPOps'

Optimising conformer:   0%|                               | 0/5 [00:00<?, ?it/s][AOptimising conformer:  69%|███████████████▏      | 9/13 [00:34<00:15,  3.90s/it]Optimising conformer:  77%|████████████████▏    | 10/13 [00:36<00:09,  3.31s/it]
Optimising conformer:  20%|████▌                  | 1/5 [00:05<00:20,  5.16s/it][AOptimising conformer:  85%|█████████████████▊   | 11/13 [00:39<00:06,  3.30s/it]
Optimising conformer:  40%|█████████▏             | 2/5 [00:08<00:11,  3.94s/it][AOptimising conformer:  92%|███████████████████▍ | 12/13 [00:42<00:03,  3.20s/it]
Optimising conformer:  60%|█████████████▊         | 3/5 [00:11<00:06,  3.44s/it][AOptimising conformer: 100%|█████████████████████| 13/13 [00:45<00:00,  3.07s/it]Optimising conformer: 100%|█████████████████████| 13/13 [00:45<00:00,  3.49s/it]

Optimising conformer:  80%|██████████████████▍    | 4/5 [00:13<00:03,  3.05s/it][A
Optimising conformer: 100%|███████████████████████| 5/5 [00:16<00:00,  2.92s/it][AOptimising conformer: 100%|███████████████████████| 5/5 [00:16<00:00,  3.24s/it]
/mnt/storage/nobackup/nmb1063/code/gal/sars-cov-2-main-protease-al-study-combo1/rsearcher.py:89: UserWarning: The ligand was an array (SDF?). Using the first frame. 
  warnings.warn("The ligand was an array (SDF?). Using the first frame. ")
2024-02-01 09:04:52,774 - distributed.core - INFO - Event loop was unresponsive in Worker for 5.68s.  This is often caused by long-running GIL-holding functions or moving large chunks of data. This can cause timeouts and instability.
2024-02-01 09:04:52,774 [INFO] [core.py:595] distributed.core: Event loop was unresponsive in Worker for 5.68s.  This is often caused by long-running GIL-holding functions or moving large chunks of data. This can cause timeouts and instability.
2024-02-01 09:05:10,375 - distributed.core - INFO - Event loop was unresponsive in Worker for 3.15s.  This is often caused by long-running GIL-holding functions or moving large chunks of data. This can cause timeouts and instability.
2024-02-01 09:05:10,375 [INFO] [core.py:595] distributed.core: Event loop was unresponsive in Worker for 3.15s.  This is often caused by long-running GIL-holding functions or moving large chunks of data. This can cause timeouts and instability.
2024-02-01 09:05:13,461 - distributed.core - INFO - Event loop was unresponsive in Worker for 3.09s.  This is often caused by long-running GIL-holding functions or moving large chunks of data. This can cause timeouts and instability.
2024-02-01 09:05:13,461 [INFO] [core.py:595] distributed.core: Event loop was unresponsive in Worker for 3.09s.  This is often caused by long-running GIL-holding functions or moving large chunks of data. This can cause timeouts and instability.
/mnt/storage/nobackup/nmb1063/mamba/envs/fegrow/lib/python3.9/site-packages/parmed/structure.py:1775: UnitStrippedWarning: The unit of the quantity is stripped when downcasting to ndarray.
  coords = np.array(value, dtype=np.float64, copy=False, subok=True)
TIME Completed the molecule generation in 148.2s.
TIME Completed the molecule generation in 102.7s.
TIME changed dir: 0.0s
TIME changed dir: 0.0s
Generated 15 conformers. 
Generated 10 conformers. 
Removed 6 conformers. 
Removed 11 conformers. 
using ani2x
/mnt/storage/nobackup/nmb1063/mamba/envs/fegrow/lib/python3.9/site-packages/torchani/resources/
using ani2x
/mnt/storage/nobackup/nmb1063/mamba/envs/fegrow/lib/python3.9/site-packages/torchani/resources/
failed to equip `nnpops` with error: No module named 'NNPOps'
Optimising conformer:   0%|                               | 0/4 [00:00<?, ?it/s]Optimising conformer:  25%|█████▊                 | 1/4 [00:03<00:11,  3.68s/it]failed to equip `nnpops` with error: No module named 'NNPOps'

Optimising conformer:   0%|                               | 0/4 [00:00<?, ?it/s][AOptimising conformer:  50%|███████████▌           | 2/4 [00:05<00:05,  2.79s/it]
Optimising conformer:  25%|█████▊                 | 1/4 [00:03<00:10,  3.37s/it][AOptimising conformer:  75%|█████████████████▎     | 3/4 [00:09<00:03,  3.04s/it]
Optimising conformer:  50%|███████████▌           | 2/4 [00:06<00:05,  3.00s/it][AOptimising conformer: 100%|███████████████████████| 4/4 [00:11<00:00,  2.69s/it]Optimising conformer: 100%|███████████████████████| 4/4 [00:11<00:00,  2.84s/it]

Optimising conformer:  75%|█████████████████▎     | 3/4 [00:09<00:03,  3.29s/it][A
Optimising conformer: 100%|███████████████████████| 4/4 [00:12<00:00,  2.95s/it][AOptimising conformer: 100%|███████████████████████| 4/4 [00:12<00:00,  3.04s/it]
/mnt/storage/nobackup/nmb1063/code/gal/sars-cov-2-main-protease-al-study-combo1/rsearcher.py:89: UserWarning: The ligand was an array (SDF?). Using the first frame. 
  warnings.warn("The ligand was an array (SDF?). Using the first frame. ")
2024-02-01 09:24:32,616 [WARNING] [rdkit_wrapper.py:3213] openff.toolkit.utils.rdkit_wrapper: Warning (not error because allow_undefined_stereo=True): RDMol has unspecified stereochemistry. Undefined chiral centers are:
 - Atom C (index 1)
 - Atom C (index 3)

/mnt/storage/nobackup/nmb1063/mamba/envs/fegrow/lib/python3.9/site-packages/parmed/structure.py:1775: UnitStrippedWarning: The unit of the quantity is stripped when downcasting to ndarray.
  coords = np.array(value, dtype=np.float64, copy=False, subok=True)
2024-02-01 09:24:35,955 [WARNING] [rdkit_wrapper.py:3213] openff.toolkit.utils.rdkit_wrapper: Warning (not error because allow_undefined_stereo=True): RDMol has unspecified stereochemistry. Undefined chiral centers are:
 - Atom C (index 1)
 - Atom C (index 3)

2024-02-01 09:24:37,558 [WARNING] [rdkit_wrapper.py:3213] openff.toolkit.utils.rdkit_wrapper: Warning (not error because allow_undefined_stereo=True): RDMol has unspecified stereochemistry. Undefined chiral centers are:
 - Atom C (index 1)
 - Atom C (index 3)

/mnt/storage/nobackup/nmb1063/mamba/envs/fegrow/lib/python3.9/site-packages/parmed/structure.py:1775: UnitStrippedWarning: The unit of the quantity is stripped when downcasting to ndarray.
  coords = np.array(value, dtype=np.float64, copy=False, subok=True)
2024-02-01 09:24:39,375 [WARNING] [rdkit_wrapper.py:3213] openff.toolkit.utils.rdkit_wrapper: Warning (not error because allow_undefined_stereo=True): RDMol has unspecified stereochemistry. Undefined chiral centers are:
 - Atom C (index 1)
 - Atom C (index 3)

TIME Completed the molecule generation in 65.0s.
TIME changed dir: 0.0s
TIME Completed the molecule generation in 67.5s.
TIME changed dir: 0.0s
Generated 21 conformers. 
Removed 10 conformers. 
Generated 32 conformers. 
Removed 21 conformers. 
using ani2x
/mnt/storage/nobackup/nmb1063/mamba/envs/fegrow/lib/python3.9/site-packages/torchani/resources/
failed to equip `nnpops` with error: No module named 'NNPOps'
Optimising conformer:   0%|                              | 0/11 [00:00<?, ?it/s]Optimising conformer:   9%|██                    | 1/11 [00:03<00:39,  3.99s/it]Optimising conformer:  18%|████                  | 2/11 [00:05<00:23,  2.66s/it]Optimising conformer:  27%|██████                | 3/11 [00:07<00:17,  2.24s/it]Optimising conformer:  36%|████████              | 4/11 [00:10<00:18,  2.70s/it]Optimising conformer:  45%|██████████            | 5/11 [00:15<00:20,  3.35s/it]Optimising conformer:  55%|████████████          | 6/11 [00:16<00:13,  2.76s/it]using ani2x
/mnt/storage/nobackup/nmb1063/mamba/envs/fegrow/lib/python3.9/site-packages/torchani/resources/
failed to equip `nnpops` with error: No module named 'NNPOps'

Optimising conformer:   0%|                              | 0/11 [00:00<?, ?it/s][AOptimising conformer:  64%|██████████████        | 7/11 [00:18<00:09,  2.46s/it]Optimising conformer:  73%|████████████████      | 8/11 [00:20<00:06,  2.21s/it]Optimising conformer:  82%|██████████████████    | 9/11 [00:22<00:04,  2.12s/it]
Optimising conformer:   9%|██                    | 1/11 [00:05<00:52,  5.27s/it][AOptimising conformer:  91%|███████████████████  | 10/11 [00:24<00:02,  2.00s/it]Optimising conformer: 100%|█████████████████████| 11/11 [00:26<00:00,  2.06s/it]Optimising conformer: 100%|█████████████████████| 11/11 [00:26<00:00,  2.40s/it]

Optimising conformer:  18%|████                  | 2/11 [00:08<00:37,  4.18s/it][A
Optimising conformer:  27%|██████                | 3/11 [00:14<00:37,  4.71s/it][A
Optimising conformer:  36%|████████              | 4/11 [00:16<00:27,  3.93s/it][A
Optimising conformer:  45%|██████████            | 5/11 [00:20<00:23,  3.96s/it][A
Optimising conformer:  55%|████████████          | 6/11 [00:24<00:19,  3.95s/it][A/mnt/storage/nobackup/nmb1063/code/gal/sars-cov-2-main-protease-al-study-combo1/rsearcher.py:89: UserWarning: The ligand was an array (SDF?). Using the first frame. 
  warnings.warn("The ligand was an array (SDF?). Using the first frame. ")

Optimising conformer:  64%|██████████████        | 7/11 [00:35<00:25,  6.32s/it][A
Optimising conformer:  73%|████████████████      | 8/11 [00:39<00:16,  5.45s/it][A
Optimising conformer:  82%|██████████████████    | 9/11 [00:41<00:08,  4.22s/it][A
Optimising conformer:  91%|███████████████████  | 10/11 [00:42<00:03,  3.40s/it][A
Optimising conformer: 100%|█████████████████████| 11/11 [00:45<00:00,  3.26s/it][AOptimising conformer: 100%|█████████████████████| 11/11 [00:45<00:00,  4.14s/it]
2024-02-01 09:51:08,166 - distributed.core - INFO - Event loop was unresponsive in Worker for 3.89s.  This is often caused by long-running GIL-holding functions or moving large chunks of data. This can cause timeouts and instability.
2024-02-01 09:51:08,166 [INFO] [core.py:595] distributed.core: Event loop was unresponsive in Worker for 3.89s.  This is often caused by long-running GIL-holding functions or moving large chunks of data. This can cause timeouts and instability.
slurmstepd: error: *** JOB 19912194 ON sb078 CANCELLED AT 2024-02-01T09:54:47 ***
