hostname sb035.cluster
ipconfig 1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN group default qlen 1000 link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00 inet 127.0.0.1/8 scope host lo valid_lft forever preferred_lft forever inet6 ::1/128 scope host valid_lft forever preferred_lft forever 2: enp4s0f0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 9000 qdisc mq state UP group default qlen 1000 link/ether a0:8c:f8:74:c8:c4 brd ff:ff:ff:ff:ff:ff inet 10.3.81.115/22 brd 10.3.83.255 scope global enp4s0f0 valid_lft forever preferred_lft forever inet6 fe80::a28c:f8ff:fe74:c8c4/64 scope link valid_lft forever preferred_lft forever 3: enp4s0f1: <BROADCAST,MULTICAST> mtu 1500 qdisc noop state DOWN group default qlen 1000 link/ether a0:8c:f8:74:c8:c5 brd ff:ff:ff:ff:ff:ff 4: enp4s0f2: <BROADCAST,MULTICAST> mtu 1500 qdisc noop state DOWN group default qlen 1000 link/ether a0:8c:f8:74:c8:c6 brd ff:ff:ff:ff:ff:ff 5: enp4s0f3: <BROADCAST,MULTICAST> mtu 1500 qdisc noop state DOWN group default qlen 1000 link/ether a0:8c:f8:74:c8:c7 brd ff:ff:ff:ff:ff:ff 6: ib0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 4092 qdisc pfifo_fast state UP group default qlen 256 link/infiniband 80:00:00:29:fe:80:00:00:00:00:00:00:70:79:90:03:00:50:5e:63 brd 00:ff:ff:ff:ff:12:40:1b:ff:ff:00:00:00:00:00:00:ff:ff:ff:ff inet 10.3.89.115/22 brd 10.3.91.255 scope global ib0 valid_lft forever preferred_lft forever inet 10.3.93.115/22 brd 10.3.95.255 scope global ib0:1 valid_lft forever preferred_lft forever inet6 fe80::7279:9003:50:5e63/64 scope link valid_lft forever preferred_lft forever 7: ib1: <NO-CARRIER,BROADCAST,MULTICAST,UP> mtu 4092 qdisc pfifo_fast state DOWN group default qlen 256 link/infiniband 80:00:00:29:fe:80:00:00:00:00:00:00:70:79:90:03:00:50:5e:64 brd 00:ff:ff:ff:ff:12:40:1b:ff:ff:00:00:00:00:00:00:ff:ff:ff:ff
2024-02-01 08:20:58,060 - distributed.nanny - INFO -         Start Nanny at: 'tcp://10.3.89.115:46377'
2024-02-01 08:21:00,088 - distributed.diskutils - INFO - Found stale lock file and directory '/scratch/dask-worker-space/worker-kfdm3okj', purging
2024-02-01 08:21:06,886 - distributed.worker - INFO -       Start worker at:    tcp://10.3.89.115:32929
2024-02-01 08:21:06,887 - distributed.worker - INFO -          Listening to:    tcp://10.3.89.115:32929
2024-02-01 08:21:06,887 - distributed.worker - INFO -           Worker name:            SLURMCluster-61
2024-02-01 08:21:06,887 - distributed.worker - INFO -          dashboard at:          10.3.89.115:34946
2024-02-01 08:21:06,888 - distributed.worker - INFO - Waiting to connect to:     tcp://10.3.88.11:37020
2024-02-01 08:21:06,888 - distributed.worker - INFO - -------------------------------------------------
2024-02-01 08:21:06,888 - distributed.worker - INFO -               Threads:                          2
2024-02-01 08:21:06,888 - distributed.worker - INFO -                Memory:                  20.49 GiB
2024-02-01 08:21:06,888 - distributed.worker - INFO -       Local Directory: /scratch/dask-worker-space/worker-wy3_gtzk
2024-02-01 08:21:06,888 - distributed.worker - INFO - -------------------------------------------------
2024-02-01 08:21:06,950 - distributed.worker - INFO -         Registered to:     tcp://10.3.88.11:37020
2024-02-01 08:21:06,950 - distributed.worker - INFO - -------------------------------------------------
2024-02-01 08:21:06,950 - distributed.core - INFO - Starting established connection to tcp://10.3.88.11:37020
2024-02-01 08:35:11,358 - distributed.core - INFO - Event loop was unresponsive in Worker for 3.31s.  This is often caused by long-running GIL-holding functions or moving large chunks of data. This can cause timeouts and instability.
2024-02-01 08:35:38,046 - distributed.worker - ERROR - Worker stream died during communication: tcp://10.3.89.93:44896
Traceback (most recent call last):
  File "/mnt/storage/nobackup/nmb1063/mamba/envs/fegrow/lib/python3.9/site-packages/distributed/comm/tcp.py", line 225, in read
    frames_nbytes = await stream.read_bytes(fmt_size)
asyncio.exceptions.CancelledError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/mnt/storage/nobackup/nmb1063/mamba/envs/fegrow/lib/python3.9/asyncio/tasks.py", line 490, in wait_for
    return fut.result()
asyncio.exceptions.CancelledError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/mnt/storage/nobackup/nmb1063/mamba/envs/fegrow/lib/python3.9/site-packages/distributed/comm/core.py", line 328, in connect
    handshake = await asyncio.wait_for(comm.read(), time_left())
  File "/mnt/storage/nobackup/nmb1063/mamba/envs/fegrow/lib/python3.9/asyncio/tasks.py", line 492, in wait_for
    raise exceptions.TimeoutError() from exc
asyncio.exceptions.TimeoutError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/mnt/storage/nobackup/nmb1063/mamba/envs/fegrow/lib/python3.9/site-packages/distributed/worker.py", line 2081, in gather_dep
    response = await get_data_from_worker(
  File "/mnt/storage/nobackup/nmb1063/mamba/envs/fegrow/lib/python3.9/site-packages/distributed/worker.py", line 2900, in get_data_from_worker
    comm = await rpc.connect(worker)
  File "/mnt/storage/nobackup/nmb1063/mamba/envs/fegrow/lib/python3.9/site-packages/distributed/core.py", line 1468, in connect
    return await connect_attempt
  File "/mnt/storage/nobackup/nmb1063/mamba/envs/fegrow/lib/python3.9/site-packages/distributed/core.py", line 1389, in _connect
    comm = await connect(
  File "/mnt/storage/nobackup/nmb1063/mamba/envs/fegrow/lib/python3.9/site-packages/distributed/comm/core.py", line 333, in connect
    raise OSError(
OSError: Timed out during handshake while connecting to tcp://10.3.89.93:44896 after 30 s
2024-02-01 08:36:08,075 - distributed.worker - ERROR - Worker stream died during communication: tcp://10.3.89.95:36040
Traceback (most recent call last):
  File "/mnt/storage/nobackup/nmb1063/mamba/envs/fegrow/lib/python3.9/site-packages/distributed/comm/tcp.py", line 225, in read
    frames_nbytes = await stream.read_bytes(fmt_size)
asyncio.exceptions.CancelledError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/mnt/storage/nobackup/nmb1063/mamba/envs/fegrow/lib/python3.9/asyncio/tasks.py", line 490, in wait_for
    return fut.result()
asyncio.exceptions.CancelledError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/mnt/storage/nobackup/nmb1063/mamba/envs/fegrow/lib/python3.9/site-packages/distributed/comm/core.py", line 328, in connect
    handshake = await asyncio.wait_for(comm.read(), time_left())
  File "/mnt/storage/nobackup/nmb1063/mamba/envs/fegrow/lib/python3.9/asyncio/tasks.py", line 492, in wait_for
    raise exceptions.TimeoutError() from exc
asyncio.exceptions.TimeoutError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/mnt/storage/nobackup/nmb1063/mamba/envs/fegrow/lib/python3.9/site-packages/distributed/worker.py", line 2081, in gather_dep
    response = await get_data_from_worker(
  File "/mnt/storage/nobackup/nmb1063/mamba/envs/fegrow/lib/python3.9/site-packages/distributed/worker.py", line 2900, in get_data_from_worker
    comm = await rpc.connect(worker)
  File "/mnt/storage/nobackup/nmb1063/mamba/envs/fegrow/lib/python3.9/site-packages/distributed/core.py", line 1468, in connect
    return await connect_attempt
  File "/mnt/storage/nobackup/nmb1063/mamba/envs/fegrow/lib/python3.9/site-packages/distributed/core.py", line 1389, in _connect
    comm = await connect(
  File "/mnt/storage/nobackup/nmb1063/mamba/envs/fegrow/lib/python3.9/site-packages/distributed/comm/core.py", line 333, in connect
    raise OSError(
OSError: Timed out during handshake while connecting to tcp://10.3.89.95:36040 after 30 s
2024-02-01 08:36:38,956 - distributed.worker - ERROR - Worker stream died during communication: tcp://10.3.89.95:36040
Traceback (most recent call last):
  File "/mnt/storage/nobackup/nmb1063/mamba/envs/fegrow/lib/python3.9/site-packages/distributed/comm/tcp.py", line 225, in read
    frames_nbytes = await stream.read_bytes(fmt_size)
asyncio.exceptions.CancelledError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/mnt/storage/nobackup/nmb1063/mamba/envs/fegrow/lib/python3.9/asyncio/tasks.py", line 490, in wait_for
    return fut.result()
asyncio.exceptions.CancelledError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/mnt/storage/nobackup/nmb1063/mamba/envs/fegrow/lib/python3.9/site-packages/distributed/comm/core.py", line 328, in connect
    handshake = await asyncio.wait_for(comm.read(), time_left())
  File "/mnt/storage/nobackup/nmb1063/mamba/envs/fegrow/lib/python3.9/asyncio/tasks.py", line 492, in wait_for
    raise exceptions.TimeoutError() from exc
asyncio.exceptions.TimeoutError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/mnt/storage/nobackup/nmb1063/mamba/envs/fegrow/lib/python3.9/site-packages/distributed/worker.py", line 2081, in gather_dep
    response = await get_data_from_worker(
  File "/mnt/storage/nobackup/nmb1063/mamba/envs/fegrow/lib/python3.9/site-packages/distributed/worker.py", line 2900, in get_data_from_worker
    comm = await rpc.connect(worker)
  File "/mnt/storage/nobackup/nmb1063/mamba/envs/fegrow/lib/python3.9/site-packages/distributed/core.py", line 1468, in connect
    return await connect_attempt
  File "/mnt/storage/nobackup/nmb1063/mamba/envs/fegrow/lib/python3.9/site-packages/distributed/core.py", line 1389, in _connect
    comm = await connect(
  File "/mnt/storage/nobackup/nmb1063/mamba/envs/fegrow/lib/python3.9/site-packages/distributed/comm/core.py", line 333, in connect
    raise OSError(
OSError: Timed out during handshake while connecting to tcp://10.3.89.95:36040 after 30 s
2024-02-01 08:36:58,280 - distributed.core - INFO - Event loop was unresponsive in Worker for 16.29s.  This is often caused by long-running GIL-holding functions or moving large chunks of data. This can cause timeouts and instability.
2024-02-01 08:36:58,280 [INFO] [core.py:595] distributed.core: Event loop was unresponsive in Worker for 16.29s.  This is often caused by long-running GIL-holding functions or moving large chunks of data. This can cause timeouts and instability.
2024-02-01 08:37:08,048 [WARNING] [rdkit_wrapper.py:3213] openff.toolkit.utils.rdkit_wrapper: Warning (not error because allow_undefined_stereo=True): RDMol has unspecified stereochemistry. Undefined chiral centers are:
 - Atom C (index 2)
 - Atom C (index 6)

/mnt/storage/nobackup/nmb1063/mamba/envs/fegrow/lib/python3.9/site-packages/parmed/structure.py:1775: UnitStrippedWarning: The unit of the quantity is stripped when downcasting to ndarray.
  coords = np.array(value, dtype=np.float64, copy=False, subok=True)
2024-02-01 08:37:12,579 [WARNING] [rdkit_wrapper.py:3213] openff.toolkit.utils.rdkit_wrapper: Warning (not error because allow_undefined_stereo=True): RDMol has unspecified stereochemistry. Undefined chiral centers are:
 - Atom C (index 2)
 - Atom C (index 6)

/mnt/storage/nobackup/nmb1063/mamba/envs/fegrow/lib/python3.9/site-packages/torchani/__init__.py:55: UserWarning: Dependency not satisfied, torchani.ase will not be available
  warnings.warn("Dependency not satisfied, torchani.ase will not be available")
2024-02-01 08:38:50,596 [WARNING] [__init__.py:5] root: Warning: importing 'simtk.openmm' is deprecated.  Import 'openmm' instead.
TIME changed dir: 0.0s
TIME changed dir: 0.0s
Generated 12 conformers. 
Removed 8 conformers. 
Generated 48 conformers. 
Removed 40 conformers. 
using ani2x
/mnt/storage/nobackup/nmb1063/mamba/envs/fegrow/lib/python3.9/site-packages/torchani/resources/
failed to equip `nnpops` with error: No module named 'NNPOps'
Optimising conformer:   0%|                               | 0/4 [00:00<?, ?it/s][W BinaryOps.cpp:601] Warning: floor_divide is deprecated, and will be removed in a future version of pytorch. It currently rounds toward 0 (like the 'trunc' function NOT 'floor'). This results in incorrect rounding for negative values.
To keep the current behavior, use torch.div(a, b, rounding_mode='trunc'), or for actual floor division, use torch.div(a, b, rounding_mode='floor'). (function operator())
Optimising conformer:  25%|█████▊                 | 1/4 [00:02<00:08,  2.81s/it]Optimising conformer:  50%|███████████▌           | 2/4 [00:05<00:05,  2.66s/it]Optimising conformer:  75%|█████████████████▎     | 3/4 [00:08<00:02,  2.85s/it]Optimising conformer: 100%|███████████████████████| 4/4 [00:09<00:00,  2.27s/it]Optimising conformer: 100%|███████████████████████| 4/4 [00:09<00:00,  2.46s/it]
/mnt/storage/nobackup/nmb1063/code/gal/sars-cov-2-main-protease-al-study-combo1/rsearcher.py:89: UserWarning: The ligand was an array (SDF?). Using the first frame. 
  warnings.warn("The ligand was an array (SDF?). Using the first frame. ")
/mnt/storage/nobackup/nmb1063/mamba/envs/fegrow/lib/python3.9/site-packages/parmed/structure.py:1775: UnitStrippedWarning: The unit of the quantity is stripped when downcasting to ndarray.
  coords = np.array(value, dtype=np.float64, copy=False, subok=True)
TIME Completed the molecule generation in 138.8s.
TIME changed dir: 0.0s
Generated 32 conformers. 
Removed 12 conformers. 
using ani2x
/mnt/storage/nobackup/nmb1063/mamba/envs/fegrow/lib/python3.9/site-packages/torchani/resources/
using ani2x
/mnt/storage/nobackup/nmb1063/mamba/envs/fegrow/lib/python3.9/site-packages/torchani/resources/
failed to equip `nnpops` with error: No module named 'NNPOps'
Optimising conformer:   0%|                              | 0/20 [00:00<?, ?it/s]failed to equip `nnpops` with error: No module named 'NNPOps'

Optimising conformer:   0%|                               | 0/8 [00:00<?, ?it/s][AOptimising conformer:   5%|█                     | 1/20 [00:05<01:43,  5.46s/it]Optimising conformer:  10%|██▏                   | 2/20 [00:08<01:16,  4.26s/it]
Optimising conformer:  12%|██▉                    | 1/8 [00:07<00:50,  7.16s/it][AOptimising conformer:  15%|███▎                  | 3/20 [00:13<01:14,  4.40s/it]Optimising conformer:  20%|████▍                 | 4/20 [00:17<01:10,  4.42s/it]Optimising conformer:  25%|█████▌                | 5/20 [00:21<00:59,  3.98s/it]Optimising conformer:  30%|██████▌               | 6/20 [00:25<00:57,  4.08s/it]Optimising conformer:  35%|███████▋              | 7/20 [00:28<00:50,  3.88s/it]Optimising conformer:  40%|████████▊             | 8/20 [00:33<00:49,  4.09s/it]Optimising conformer:  45%|█████████▉            | 9/20 [00:37<00:45,  4.15s/it]Optimising conformer:  50%|██████████▌          | 10/20 [00:41<00:39,  3.98s/it]
Optimising conformer:  25%|█████▊                 | 2/8 [00:41<02:19, 23.25s/it][A
Optimising conformer:  38%|████████▋              | 3/8 [00:43<01:07, 13.55s/it][AOptimising conformer:  55%|███████████▌         | 11/20 [00:45<00:37,  4.16s/it]
Optimising conformer:  50%|███████████▌           | 4/8 [00:45<00:35,  8.95s/it][A
Optimising conformer:  62%|██████████████▍        | 5/8 [00:47<00:19,  6.43s/it][AOptimising conformer:  60%|████████████▌        | 12/20 [00:50<00:33,  4.19s/it]
Optimising conformer:  75%|█████████████████▎     | 6/8 [00:51<00:11,  5.52s/it][AOptimising conformer:  65%|█████████████▋       | 13/20 [00:54<00:29,  4.26s/it]
Optimising conformer:  88%|████████████████████▏  | 7/8 [00:55<00:05,  5.18s/it][AOptimising conformer:  70%|██████████████▋      | 14/20 [00:59<00:26,  4.35s/it]
Optimising conformer: 100%|███████████████████████| 8/8 [00:59<00:00,  4.69s/it][AOptimising conformer: 100%|███████████████████████| 8/8 [00:59<00:00,  7.43s/it]
Optimising conformer:  75%|███████████████▊     | 15/20 [01:03<00:22,  4.47s/it]/mnt/storage/nobackup/nmb1063/code/gal/sars-cov-2-main-protease-al-study-combo1/rsearcher.py:89: UserWarning: The ligand was an array (SDF?). Using the first frame. 
  warnings.warn("The ligand was an array (SDF?). Using the first frame. ")
Optimising conformer:  80%|████████████████▊    | 16/20 [01:06<00:16,  4.03s/it]Optimising conformer:  85%|█████████████████▊   | 17/20 [01:10<00:11,  4.00s/it]Optimising conformer:  90%|██████████████████▉  | 18/20 [01:14<00:07,  3.96s/it]Optimising conformer:  95%|███████████████████▉ | 19/20 [01:17<00:03,  3.60s/it]Optimising conformer: 100%|█████████████████████| 20/20 [01:20<00:00,  3.55s/it]Optimising conformer: 100%|█████████████████████| 20/20 [01:20<00:00,  4.04s/it]
2024-02-01 09:04:49,516 - distributed.core - INFO - Event loop was unresponsive in Worker for 3.07s.  This is often caused by long-running GIL-holding functions or moving large chunks of data. This can cause timeouts and instability.
2024-02-01 09:04:49,516 [INFO] [core.py:595] distributed.core: Event loop was unresponsive in Worker for 3.07s.  This is often caused by long-running GIL-holding functions or moving large chunks of data. This can cause timeouts and instability.
2024-02-01 09:05:10,466 - distributed.core - INFO - Event loop was unresponsive in Worker for 3.02s.  This is often caused by long-running GIL-holding functions or moving large chunks of data. This can cause timeouts and instability.
2024-02-01 09:05:10,466 [INFO] [core.py:595] distributed.core: Event loop was unresponsive in Worker for 3.02s.  This is often caused by long-running GIL-holding functions or moving large chunks of data. This can cause timeouts and instability.
/mnt/storage/nobackup/nmb1063/mamba/envs/fegrow/lib/python3.9/site-packages/parmed/structure.py:1775: UnitStrippedWarning: The unit of the quantity is stripped when downcasting to ndarray.
  coords = np.array(value, dtype=np.float64, copy=False, subok=True)
/mnt/storage/nobackup/nmb1063/mamba/envs/fegrow/lib/python3.9/site-packages/parmed/structure.py:1775: UnitStrippedWarning: The unit of the quantity is stripped when downcasting to ndarray.
  coords = np.array(value, dtype=np.float64, copy=False, subok=True)
TIME Completed the molecule generation in 257.2s.
TIME Completed the molecule generation in 175.3s.
TIME changed dir: 0.0s
TIME changed dir: 0.0s
Generated 12 conformers. 
Generated 48 conformers. 
Removed 10 conformers. 
Removed 23 conformers. 
using ani2x
/mnt/storage/nobackup/nmb1063/mamba/envs/fegrow/lib/python3.9/site-packages/torchani/resources/
failed to equip `nnpops` with error: No module named 'NNPOps'
Optimising conformer:   0%|                              | 0/25 [00:00<?, ?it/s]Optimising conformer:   4%|▉                     | 1/25 [00:05<02:01,  5.04s/it]Optimising conformer:   8%|█▊                    | 2/25 [00:08<01:40,  4.36s/it]Optimising conformer:  12%|██▋                   | 3/25 [00:10<01:11,  3.26s/it]Optimising conformer:  16%|███▌                  | 4/25 [00:13<01:01,  2.93s/it]Optimising conformer:  20%|████▍                 | 5/25 [00:16<01:03,  3.18s/it]Optimising conformer:  24%|█████▎                | 6/25 [00:21<01:08,  3.63s/it]Optimising conformer:  28%|██████▏               | 7/25 [00:24<01:00,  3.36s/it]Optimising conformer:  32%|███████               | 8/25 [00:30<01:10,  4.17s/it]Optimising conformer:  36%|███████▉              | 9/25 [00:33<01:04,  4.01s/it]Optimising conformer:  40%|████████▍            | 10/25 [00:35<00:51,  3.43s/it]Optimising conformer:  44%|█████████▏           | 11/25 [00:37<00:41,  2.98s/it]Optimising conformer:  48%|██████████           | 12/25 [00:41<00:39,  3.04s/it]Optimising conformer:  52%|██████████▉          | 13/25 [00:44<00:37,  3.09s/it]Optimising conformer:  56%|███████████▊         | 14/25 [00:48<00:36,  3.34s/it]Optimising conformer:  60%|████████████▌        | 15/25 [00:55<00:46,  4.65s/it]Optimising conformer:  64%|█████████████▍       | 16/25 [00:57<00:34,  3.88s/it]Optimising conformer:  68%|██████████████▎      | 17/25 [00:59<00:26,  3.29s/it]Optimising conformer:  72%|███████████████      | 18/25 [01:02<00:20,  2.98s/it]Optimising conformer:  76%|███████████████▉     | 19/25 [01:06<00:19,  3.27s/it]Optimising conformer:  80%|████████████████▊    | 20/25 [01:09<00:16,  3.31s/it]Optimising conformer:  84%|█████████████████▋   | 21/25 [01:11<00:11,  2.94s/it]Optimising conformer:  88%|██████████████████▍  | 22/25 [01:13<00:07,  2.66s/it]Optimising conformer:  92%|███████████████████▎ | 23/25 [01:16<00:05,  2.75s/it]Optimising conformer:  96%|████████████████████▏| 24/25 [01:19<00:02,  2.74s/it]Optimising conformer: 100%|█████████████████████| 25/25 [01:21<00:00,  2.51s/it]Optimising conformer: 100%|█████████████████████| 25/25 [01:21<00:00,  3.25s/it]
/mnt/storage/nobackup/nmb1063/code/gal/sars-cov-2-main-protease-al-study-combo1/rsearcher.py:89: UserWarning: The ligand was an array (SDF?). Using the first frame. 
  warnings.warn("The ligand was an array (SDF?). Using the first frame. ")
using ani2x
/mnt/storage/nobackup/nmb1063/mamba/envs/fegrow/lib/python3.9/site-packages/torchani/resources/
failed to equip `nnpops` with error: No module named 'NNPOps'
TIME Completed the molecule generation in 139.6s.
Optimising conformer:   0%|                               | 0/2 [00:00<?, ?it/s]Optimising conformer:  50%|███████████▌           | 1/2 [00:02<00:02,  2.47s/it]Optimising conformer: 100%|███████████████████████| 2/2 [00:03<00:00,  1.79s/it]Optimising conformer: 100%|███████████████████████| 2/2 [00:03<00:00,  1.90s/it]
slurmstepd: error: *** JOB 19912202 ON sb035 CANCELLED AT 2024-02-01T09:54:47 ***
