hostname sb017.cluster
ipconfig 1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN group default qlen 1000 link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00 inet 127.0.0.1/8 scope host lo valid_lft forever preferred_lft forever inet6 ::1/128 scope host valid_lft forever preferred_lft forever 2: enp4s0f0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 9000 qdisc mq state UP group default qlen 1000 link/ether a0:8c:f8:34:cc:c8 brd ff:ff:ff:ff:ff:ff inet 10.3.81.97/22 brd 10.3.83.255 scope global enp4s0f0 valid_lft forever preferred_lft forever inet6 fe80::a28c:f8ff:fe34:ccc8/64 scope link valid_lft forever preferred_lft forever 3: enp4s0f1: <BROADCAST,MULTICAST> mtu 1500 qdisc noop state DOWN group default qlen 1000 link/ether a0:8c:f8:34:cc:c9 brd ff:ff:ff:ff:ff:ff 4: enp4s0f2: <BROADCAST,MULTICAST> mtu 1500 qdisc noop state DOWN group default qlen 1000 link/ether a0:8c:f8:34:cc:ca brd ff:ff:ff:ff:ff:ff 5: enp4s0f3: <BROADCAST,MULTICAST> mtu 1500 qdisc noop state DOWN group default qlen 1000 link/ether a0:8c:f8:34:cc:cb brd ff:ff:ff:ff:ff:ff 6: ib0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 4092 qdisc pfifo_fast state UP group default qlen 256 link/infiniband 80:00:00:29:fe:80:00:00:00:00:00:00:38:bc:01:03:00:4c:f5:40 brd 00:ff:ff:ff:ff:12:40:1b:ff:ff:00:00:00:00:00:00:ff:ff:ff:ff inet 10.3.89.97/22 brd 10.3.91.255 scope global ib0 valid_lft forever preferred_lft forever inet 10.3.93.97/22 brd 10.3.95.255 scope global ib0:1 valid_lft forever preferred_lft forever inet6 fe80::3abc:103:4c:f540/64 scope link valid_lft forever preferred_lft forever 7: ib1: <NO-CARRIER,BROADCAST,MULTICAST,UP> mtu 4092 qdisc pfifo_fast state DOWN group default qlen 256 link/infiniband 80:00:00:29:fe:80:00:00:00:00:00:00:38:bc:01:03:00:4c:f5:41 brd 00:ff:ff:ff:ff:12:40:1b:ff:ff:00:00:00:00:00:00:ff:ff:ff:ff
2024-02-01 06:19:22,585 - distributed.nanny - INFO -         Start Nanny at: 'tcp://10.3.89.97:44006'
2024-02-01 06:19:35,617 - distributed.worker - INFO -       Start worker at:     tcp://10.3.89.97:39535
2024-02-01 06:19:35,618 - distributed.worker - INFO -          Listening to:     tcp://10.3.89.97:39535
2024-02-01 06:19:35,618 - distributed.worker - INFO -           Worker name:           SLURMCluster-265
2024-02-01 06:19:35,618 - distributed.worker - INFO -          dashboard at:           10.3.89.97:33669
2024-02-01 06:19:35,618 - distributed.worker - INFO - Waiting to connect to:     tcp://10.3.88.11:37020
2024-02-01 06:19:35,618 - distributed.worker - INFO - -------------------------------------------------
2024-02-01 06:19:35,618 - distributed.worker - INFO -               Threads:                          2
2024-02-01 06:19:35,618 - distributed.worker - INFO -                Memory:                  20.49 GiB
2024-02-01 06:19:35,618 - distributed.worker - INFO -       Local Directory: /scratch/dask-worker-space/worker-gt0adocd
2024-02-01 06:19:35,619 - distributed.worker - INFO - -------------------------------------------------
2024-02-01 06:19:35,687 - distributed.worker - INFO -         Registered to:     tcp://10.3.88.11:37020
2024-02-01 06:19:35,687 - distributed.worker - INFO - -------------------------------------------------
2024-02-01 06:19:35,687 - distributed.core - INFO - Starting established connection to tcp://10.3.88.11:37020
2024-02-01 06:30:25,937 - distributed.core - INFO - Event loop was unresponsive in Worker for 56.21s.  This is often caused by long-running GIL-holding functions or moving large chunks of data. This can cause timeouts and instability.
2024-02-01 06:30:25,940 - distributed.core - INFO - Event loop was unresponsive in Nanny for 62.72s.  This is often caused by long-running GIL-holding functions or moving large chunks of data. This can cause timeouts and instability.
2024-02-01 06:45:52,175 - distributed.core - INFO - Event loop was unresponsive in Worker for 3.49s.  This is often caused by long-running GIL-holding functions or moving large chunks of data. This can cause timeouts and instability.
2024-02-01 06:45:56,479 - distributed.core - INFO - Event loop was unresponsive in Worker for 3.18s.  This is often caused by long-running GIL-holding functions or moving large chunks of data. This can cause timeouts and instability.
2024-02-01 07:01:24,028 - distributed.core - INFO - Event loop was unresponsive in Worker for 6.71s.  This is often caused by long-running GIL-holding functions or moving large chunks of data. This can cause timeouts and instability.
2024-02-01 07:14:28,517 - distributed.core - INFO - Event loop was unresponsive in Worker for 59.23s.  This is often caused by long-running GIL-holding functions or moving large chunks of data. This can cause timeouts and instability.
2024-02-01 07:14:28,517 [INFO] [core.py:595] distributed.core: Event loop was unresponsive in Worker for 59.23s.  This is often caused by long-running GIL-holding functions or moving large chunks of data. This can cause timeouts and instability.
2024-02-01 07:14:34,658 [WARNING] [rdkit_wrapper.py:3213] openff.toolkit.utils.rdkit_wrapper: Warning (not error because allow_undefined_stereo=True): RDMol has unspecified stereochemistry. Bonds with undefined stereochemistry are:
 - Bond 8 (atoms 8-9 of element (C-N)

2024-02-01 07:14:34,849 [WARNING] [rdkit_wrapper.py:3213] openff.toolkit.utils.rdkit_wrapper: Warning (not error because allow_undefined_stereo=True): RDMol has unspecified stereochemistry. Undefined chiral centers are:
 - Atom S (index 8)

/mnt/storage/nobackup/nmb1063/mamba/envs/fegrow/lib/python3.9/site-packages/parmed/structure.py:1775: UnitStrippedWarning: The unit of the quantity is stripped when downcasting to ndarray.
  coords = np.array(value, dtype=np.float64, copy=False, subok=True)
2024-02-01 07:14:39,630 [WARNING] [rdkit_wrapper.py:3213] openff.toolkit.utils.rdkit_wrapper: Warning (not error because allow_undefined_stereo=True): RDMol has unspecified stereochemistry. Bonds with undefined stereochemistry are:
 - Bond 8 (atoms 8-9 of element (C-N)

2024-02-01 07:14:39,745 [WARNING] [rdkit_wrapper.py:3213] openff.toolkit.utils.rdkit_wrapper: Warning (not error because allow_undefined_stereo=True): RDMol has unspecified stereochemistry. Undefined chiral centers are:
 - Atom S (index 8)

/mnt/storage/nobackup/nmb1063/mamba/envs/fegrow/lib/python3.9/site-packages/torchani/__init__.py:55: UserWarning: Dependency not satisfied, torchani.ase will not be available
  warnings.warn("Dependency not satisfied, torchani.ase will not be available")
2024-02-01 07:15:53,734 [WARNING] [__init__.py:5] root: Warning: importing 'simtk.openmm' is deprecated.  Import 'openmm' instead.
2024-02-01 07:16:00,015 - distributed.nanny - INFO - Worker process 4012 was killed by signal 11
2024-02-01 07:16:00,025 - distributed.nanny - WARNING - Restarting worker
2024-02-01 07:16:07,028 - distributed.worker - INFO -       Start worker at:     tcp://10.3.89.97:43296
2024-02-01 07:16:07,031 - distributed.worker - INFO -          Listening to:     tcp://10.3.89.97:43296
2024-02-01 07:16:07,031 - distributed.worker - INFO -           Worker name:           SLURMCluster-265
2024-02-01 07:16:07,031 - distributed.worker - INFO -          dashboard at:           10.3.89.97:46365
2024-02-01 07:16:07,031 - distributed.worker - INFO - Waiting to connect to:     tcp://10.3.88.11:37020
2024-02-01 07:16:07,031 - distributed.worker - INFO - -------------------------------------------------
2024-02-01 07:16:07,031 - distributed.worker - INFO -               Threads:                          2
2024-02-01 07:16:07,032 - distributed.worker - INFO -                Memory:                  20.49 GiB
2024-02-01 07:16:07,032 - distributed.worker - INFO -       Local Directory: /scratch/dask-worker-space/worker-vtslevma
2024-02-01 07:16:07,032 - distributed.worker - INFO - -------------------------------------------------
2024-02-01 07:16:07,063 - distributed.worker - INFO -         Registered to:     tcp://10.3.88.11:37020
2024-02-01 07:16:07,063 - distributed.worker - INFO - -------------------------------------------------
2024-02-01 07:16:07,063 - distributed.core - INFO - Starting established connection to tcp://10.3.88.11:37020
2024-02-01 07:16:25,950 - distributed.core - INFO - Event loop was unresponsive in Worker for 18.79s.  This is often caused by long-running GIL-holding functions or moving large chunks of data. This can cause timeouts and instability.
2024-02-01 07:16:25,950 [INFO] [core.py:595] distributed.core: Event loop was unresponsive in Worker for 18.79s.  This is often caused by long-running GIL-holding functions or moving large chunks of data. This can cause timeouts and instability.
2024-02-01 07:16:37,035 [WARNING] [rdkit_wrapper.py:3213] openff.toolkit.utils.rdkit_wrapper: Warning (not error because allow_undefined_stereo=True): RDMol has unspecified stereochemistry. Undefined chiral centers are:
 - Atom C (index 3)

/mnt/storage/nobackup/nmb1063/mamba/envs/fegrow/lib/python3.9/site-packages/parmed/structure.py:1775: UnitStrippedWarning: The unit of the quantity is stripped when downcasting to ndarray.
  coords = np.array(value, dtype=np.float64, copy=False, subok=True)
2024-02-01 07:16:41,465 [WARNING] [rdkit_wrapper.py:3213] openff.toolkit.utils.rdkit_wrapper: Warning (not error because allow_undefined_stereo=True): RDMol has unspecified stereochemistry. Undefined chiral centers are:
 - Atom C (index 3)

/mnt/storage/nobackup/nmb1063/mamba/envs/fegrow/lib/python3.9/site-packages/torchani/__init__.py:55: UserWarning: Dependency not satisfied, torchani.ase will not be available
  warnings.warn("Dependency not satisfied, torchani.ase will not be available")
2024-02-01 07:17:32,563 [WARNING] [__init__.py:5] root: Warning: importing 'simtk.openmm' is deprecated.  Import 'openmm' instead.
TIME changed dir: 0.0s
TIME changed dir: 0.0s
Generated 47 conformers. 
Generated 35 conformers. 
Removed 29 conformers. 
Removed 36 conformers. 
using ani2x
/mnt/storage/nobackup/nmb1063/mamba/envs/fegrow/lib/python3.9/site-packages/torchani/resources/
failed to equip `nnpops` with error: No module named 'NNPOps'
Optimising conformer:   0%|                               | 0/6 [00:00<?, ?it/s][W BinaryOps.cpp:601] Warning: floor_divide is deprecated, and will be removed in a future version of pytorch. It currently rounds toward 0 (like the 'trunc' function NOT 'floor'). This results in incorrect rounding for negative values.
To keep the current behavior, use torch.div(a, b, rounding_mode='trunc'), or for actual floor division, use torch.div(a, b, rounding_mode='floor'). (function operator())
Optimising conformer:  17%|███▊                   | 1/6 [00:03<00:17,  3.43s/it]Optimising conformer:  33%|███████▋               | 2/6 [00:05<00:09,  2.34s/it]Optimising conformer:  50%|███████████▌           | 3/6 [00:21<00:26,  8.85s/it]Optimising conformer:  67%|███████████████▎       | 4/6 [00:23<00:11,  6.00s/it]Optimising conformer:  83%|███████████████████▏   | 5/6 [00:28<00:05,  5.91s/it]Optimising conformer: 100%|███████████████████████| 6/6 [00:58<00:00, 13.86s/it]Optimising conformer: 100%|███████████████████████| 6/6 [00:58<00:00,  9.71s/it]
using ani2x
/mnt/storage/nobackup/nmb1063/mamba/envs/fegrow/lib/python3.9/site-packages/torchani/resources/
failed to equip `nnpops` with error: No module named 'NNPOps'
Optimising conformer:   0%|                              | 0/11 [00:00<?, ?it/s]/mnt/storage/nobackup/nmb1063/code/gal/sars-cov-2-main-protease-al-study-combo1/rsearcher.py:89: UserWarning: The ligand was an array (SDF?). Using the first frame. 
  warnings.warn("The ligand was an array (SDF?). Using the first frame. ")
Optimising conformer:   9%|██                    | 1/11 [00:04<00:46,  4.67s/it]Optimising conformer:  18%|████                  | 2/11 [00:08<00:35,  3.97s/it]Optimising conformer:  27%|██████                | 3/11 [00:13<00:35,  4.47s/it]Optimising conformer:  36%|████████              | 4/11 [00:16<00:28,  4.11s/it]Optimising conformer:  45%|██████████            | 5/11 [00:18<00:19,  3.22s/it]Optimising conformer:  55%|████████████          | 6/11 [00:20<00:14,  2.91s/it]Optimising conformer:  64%|██████████████        | 7/11 [00:24<00:12,  3.11s/it]Optimising conformer:  73%|████████████████      | 8/11 [00:27<00:09,  3.09s/it]Optimising conformer:  82%|██████████████████    | 9/11 [00:29<00:05,  2.77s/it]Optimising conformer:  91%|███████████████████  | 10/11 [00:32<00:02,  2.75s/it]Optimising conformer: 100%|█████████████████████| 11/11 [00:35<00:00,  3.11s/it]Optimising conformer: 100%|█████████████████████| 11/11 [00:35<00:00,  3.27s/it]
2024-02-01 08:01:23,519 - distributed.core - INFO - Event loop was unresponsive in Worker for 6.46s.  This is often caused by long-running GIL-holding functions or moving large chunks of data. This can cause timeouts and instability.
2024-02-01 08:01:23,519 [INFO] [core.py:595] distributed.core: Event loop was unresponsive in Worker for 6.46s.  This is often caused by long-running GIL-holding functions or moving large chunks of data. This can cause timeouts and instability.
2024-02-01 08:03:09,432 - distributed.core - INFO - Event loop was unresponsive in Worker for 3.37s.  This is often caused by long-running GIL-holding functions or moving large chunks of data. This can cause timeouts and instability.
2024-02-01 08:03:09,432 [INFO] [core.py:595] distributed.core: Event loop was unresponsive in Worker for 3.37s.  This is often caused by long-running GIL-holding functions or moving large chunks of data. This can cause timeouts and instability.
2024-02-01 08:35:38,042 - distributed.worker - ERROR - Worker stream died during communication: tcp://10.3.89.93:44896
Traceback (most recent call last):
  File "/mnt/storage/nobackup/nmb1063/mamba/envs/fegrow/lib/python3.9/site-packages/distributed/comm/tcp.py", line 225, in read
    frames_nbytes = await stream.read_bytes(fmt_size)
asyncio.exceptions.CancelledError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/mnt/storage/nobackup/nmb1063/mamba/envs/fegrow/lib/python3.9/asyncio/tasks.py", line 490, in wait_for
    return fut.result()
asyncio.exceptions.CancelledError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/mnt/storage/nobackup/nmb1063/mamba/envs/fegrow/lib/python3.9/site-packages/distributed/comm/core.py", line 328, in connect
    handshake = await asyncio.wait_for(comm.read(), time_left())
  File "/mnt/storage/nobackup/nmb1063/mamba/envs/fegrow/lib/python3.9/asyncio/tasks.py", line 492, in wait_for
    raise exceptions.TimeoutError() from exc
asyncio.exceptions.TimeoutError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/mnt/storage/nobackup/nmb1063/mamba/envs/fegrow/lib/python3.9/site-packages/distributed/worker.py", line 2081, in gather_dep
    response = await get_data_from_worker(
  File "/mnt/storage/nobackup/nmb1063/mamba/envs/fegrow/lib/python3.9/site-packages/distributed/worker.py", line 2900, in get_data_from_worker
    comm = await rpc.connect(worker)
  File "/mnt/storage/nobackup/nmb1063/mamba/envs/fegrow/lib/python3.9/site-packages/distributed/core.py", line 1468, in connect
    return await connect_attempt
  File "/mnt/storage/nobackup/nmb1063/mamba/envs/fegrow/lib/python3.9/site-packages/distributed/core.py", line 1389, in _connect
    comm = await connect(
  File "/mnt/storage/nobackup/nmb1063/mamba/envs/fegrow/lib/python3.9/site-packages/distributed/comm/core.py", line 333, in connect
    raise OSError(
OSError: Timed out during handshake while connecting to tcp://10.3.89.93:44896 after 30 s
2024-02-01 08:35:38,042 [ERROR] [worker.py:2115] distributed.worker: Worker stream died during communication: tcp://10.3.89.93:44896
Traceback (most recent call last):
  File "/mnt/storage/nobackup/nmb1063/mamba/envs/fegrow/lib/python3.9/site-packages/distributed/comm/tcp.py", line 225, in read
    frames_nbytes = await stream.read_bytes(fmt_size)
asyncio.exceptions.CancelledError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/mnt/storage/nobackup/nmb1063/mamba/envs/fegrow/lib/python3.9/asyncio/tasks.py", line 490, in wait_for
    return fut.result()
asyncio.exceptions.CancelledError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/mnt/storage/nobackup/nmb1063/mamba/envs/fegrow/lib/python3.9/site-packages/distributed/comm/core.py", line 328, in connect
    handshake = await asyncio.wait_for(comm.read(), time_left())
  File "/mnt/storage/nobackup/nmb1063/mamba/envs/fegrow/lib/python3.9/asyncio/tasks.py", line 492, in wait_for
    raise exceptions.TimeoutError() from exc
asyncio.exceptions.TimeoutError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/mnt/storage/nobackup/nmb1063/mamba/envs/fegrow/lib/python3.9/site-packages/distributed/worker.py", line 2081, in gather_dep
    response = await get_data_from_worker(
  File "/mnt/storage/nobackup/nmb1063/mamba/envs/fegrow/lib/python3.9/site-packages/distributed/worker.py", line 2900, in get_data_from_worker
    comm = await rpc.connect(worker)
  File "/mnt/storage/nobackup/nmb1063/mamba/envs/fegrow/lib/python3.9/site-packages/distributed/core.py", line 1468, in connect
    return await connect_attempt
  File "/mnt/storage/nobackup/nmb1063/mamba/envs/fegrow/lib/python3.9/site-packages/distributed/core.py", line 1389, in _connect
    comm = await connect(
  File "/mnt/storage/nobackup/nmb1063/mamba/envs/fegrow/lib/python3.9/site-packages/distributed/comm/core.py", line 333, in connect
    raise OSError(
OSError: Timed out during handshake while connecting to tcp://10.3.89.93:44896 after 30 s
2024-02-01 08:36:08,129 - distributed.worker - ERROR - Worker stream died during communication: tcp://10.3.89.95:36040
Traceback (most recent call last):
  File "/mnt/storage/nobackup/nmb1063/mamba/envs/fegrow/lib/python3.9/site-packages/distributed/comm/tcp.py", line 225, in read
    frames_nbytes = await stream.read_bytes(fmt_size)
asyncio.exceptions.CancelledError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/mnt/storage/nobackup/nmb1063/mamba/envs/fegrow/lib/python3.9/asyncio/tasks.py", line 490, in wait_for
    return fut.result()
asyncio.exceptions.CancelledError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/mnt/storage/nobackup/nmb1063/mamba/envs/fegrow/lib/python3.9/site-packages/distributed/comm/core.py", line 328, in connect
    handshake = await asyncio.wait_for(comm.read(), time_left())
  File "/mnt/storage/nobackup/nmb1063/mamba/envs/fegrow/lib/python3.9/asyncio/tasks.py", line 492, in wait_for
    raise exceptions.TimeoutError() from exc
asyncio.exceptions.TimeoutError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/mnt/storage/nobackup/nmb1063/mamba/envs/fegrow/lib/python3.9/site-packages/distributed/worker.py", line 2081, in gather_dep
    response = await get_data_from_worker(
  File "/mnt/storage/nobackup/nmb1063/mamba/envs/fegrow/lib/python3.9/site-packages/distributed/worker.py", line 2900, in get_data_from_worker
    comm = await rpc.connect(worker)
  File "/mnt/storage/nobackup/nmb1063/mamba/envs/fegrow/lib/python3.9/site-packages/distributed/core.py", line 1468, in connect
    return await connect_attempt
  File "/mnt/storage/nobackup/nmb1063/mamba/envs/fegrow/lib/python3.9/site-packages/distributed/core.py", line 1389, in _connect
    comm = await connect(
  File "/mnt/storage/nobackup/nmb1063/mamba/envs/fegrow/lib/python3.9/site-packages/distributed/comm/core.py", line 333, in connect
    raise OSError(
OSError: Timed out during handshake while connecting to tcp://10.3.89.95:36040 after 30 s
2024-02-01 08:36:08,129 [ERROR] [worker.py:2115] distributed.worker: Worker stream died during communication: tcp://10.3.89.95:36040
Traceback (most recent call last):
  File "/mnt/storage/nobackup/nmb1063/mamba/envs/fegrow/lib/python3.9/site-packages/distributed/comm/tcp.py", line 225, in read
    frames_nbytes = await stream.read_bytes(fmt_size)
asyncio.exceptions.CancelledError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/mnt/storage/nobackup/nmb1063/mamba/envs/fegrow/lib/python3.9/asyncio/tasks.py", line 490, in wait_for
    return fut.result()
asyncio.exceptions.CancelledError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/mnt/storage/nobackup/nmb1063/mamba/envs/fegrow/lib/python3.9/site-packages/distributed/comm/core.py", line 328, in connect
    handshake = await asyncio.wait_for(comm.read(), time_left())
  File "/mnt/storage/nobackup/nmb1063/mamba/envs/fegrow/lib/python3.9/asyncio/tasks.py", line 492, in wait_for
    raise exceptions.TimeoutError() from exc
asyncio.exceptions.TimeoutError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/mnt/storage/nobackup/nmb1063/mamba/envs/fegrow/lib/python3.9/site-packages/distributed/worker.py", line 2081, in gather_dep
    response = await get_data_from_worker(
  File "/mnt/storage/nobackup/nmb1063/mamba/envs/fegrow/lib/python3.9/site-packages/distributed/worker.py", line 2900, in get_data_from_worker
    comm = await rpc.connect(worker)
  File "/mnt/storage/nobackup/nmb1063/mamba/envs/fegrow/lib/python3.9/site-packages/distributed/core.py", line 1468, in connect
    return await connect_attempt
  File "/mnt/storage/nobackup/nmb1063/mamba/envs/fegrow/lib/python3.9/site-packages/distributed/core.py", line 1389, in _connect
    comm = await connect(
  File "/mnt/storage/nobackup/nmb1063/mamba/envs/fegrow/lib/python3.9/site-packages/distributed/comm/core.py", line 333, in connect
    raise OSError(
OSError: Timed out during handshake while connecting to tcp://10.3.89.95:36040 after 30 s
2024-02-01 08:36:39,067 - distributed.worker - ERROR - Worker stream died during communication: tcp://10.3.89.95:36040
Traceback (most recent call last):
  File "/mnt/storage/nobackup/nmb1063/mamba/envs/fegrow/lib/python3.9/site-packages/distributed/comm/tcp.py", line 225, in read
    frames_nbytes = await stream.read_bytes(fmt_size)
asyncio.exceptions.CancelledError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/mnt/storage/nobackup/nmb1063/mamba/envs/fegrow/lib/python3.9/asyncio/tasks.py", line 490, in wait_for
    return fut.result()
asyncio.exceptions.CancelledError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/mnt/storage/nobackup/nmb1063/mamba/envs/fegrow/lib/python3.9/site-packages/distributed/comm/core.py", line 328, in connect
    handshake = await asyncio.wait_for(comm.read(), time_left())
  File "/mnt/storage/nobackup/nmb1063/mamba/envs/fegrow/lib/python3.9/asyncio/tasks.py", line 492, in wait_for
    raise exceptions.TimeoutError() from exc
asyncio.exceptions.TimeoutError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/mnt/storage/nobackup/nmb1063/mamba/envs/fegrow/lib/python3.9/site-packages/distributed/worker.py", line 2081, in gather_dep
    response = await get_data_from_worker(
  File "/mnt/storage/nobackup/nmb1063/mamba/envs/fegrow/lib/python3.9/site-packages/distributed/worker.py", line 2900, in get_data_from_worker
    comm = await rpc.connect(worker)
  File "/mnt/storage/nobackup/nmb1063/mamba/envs/fegrow/lib/python3.9/site-packages/distributed/core.py", line 1468, in connect
    return await connect_attempt
  File "/mnt/storage/nobackup/nmb1063/mamba/envs/fegrow/lib/python3.9/site-packages/distributed/core.py", line 1389, in _connect
    comm = await connect(
  File "/mnt/storage/nobackup/nmb1063/mamba/envs/fegrow/lib/python3.9/site-packages/distributed/comm/core.py", line 333, in connect
    raise OSError(
OSError: Timed out during handshake while connecting to tcp://10.3.89.95:36040 after 30 s
2024-02-01 08:36:39,067 [ERROR] [worker.py:2115] distributed.worker: Worker stream died during communication: tcp://10.3.89.95:36040
Traceback (most recent call last):
  File "/mnt/storage/nobackup/nmb1063/mamba/envs/fegrow/lib/python3.9/site-packages/distributed/comm/tcp.py", line 225, in read
    frames_nbytes = await stream.read_bytes(fmt_size)
asyncio.exceptions.CancelledError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/mnt/storage/nobackup/nmb1063/mamba/envs/fegrow/lib/python3.9/asyncio/tasks.py", line 490, in wait_for
    return fut.result()
asyncio.exceptions.CancelledError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/mnt/storage/nobackup/nmb1063/mamba/envs/fegrow/lib/python3.9/site-packages/distributed/comm/core.py", line 328, in connect
    handshake = await asyncio.wait_for(comm.read(), time_left())
  File "/mnt/storage/nobackup/nmb1063/mamba/envs/fegrow/lib/python3.9/asyncio/tasks.py", line 492, in wait_for
    raise exceptions.TimeoutError() from exc
asyncio.exceptions.TimeoutError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/mnt/storage/nobackup/nmb1063/mamba/envs/fegrow/lib/python3.9/site-packages/distributed/worker.py", line 2081, in gather_dep
    response = await get_data_from_worker(
  File "/mnt/storage/nobackup/nmb1063/mamba/envs/fegrow/lib/python3.9/site-packages/distributed/worker.py", line 2900, in get_data_from_worker
    comm = await rpc.connect(worker)
  File "/mnt/storage/nobackup/nmb1063/mamba/envs/fegrow/lib/python3.9/site-packages/distributed/core.py", line 1468, in connect
    return await connect_attempt
  File "/mnt/storage/nobackup/nmb1063/mamba/envs/fegrow/lib/python3.9/site-packages/distributed/core.py", line 1389, in _connect
    comm = await connect(
  File "/mnt/storage/nobackup/nmb1063/mamba/envs/fegrow/lib/python3.9/site-packages/distributed/comm/core.py", line 333, in connect
    raise OSError(
OSError: Timed out during handshake while connecting to tcp://10.3.89.95:36040 after 30 s
/mnt/storage/nobackup/nmb1063/mamba/envs/fegrow/lib/python3.9/site-packages/parmed/structure.py:1775: UnitStrippedWarning: The unit of the quantity is stripped when downcasting to ndarray.
  coords = np.array(value, dtype=np.float64, copy=False, subok=True)
2024-02-01 08:36:55,434 [WARNING] [rdkit_wrapper.py:3213] openff.toolkit.utils.rdkit_wrapper: Warning (not error because allow_undefined_stereo=True): RDMol has unspecified stereochemistry. Undefined chiral centers are:
 - Atom C (index 2)
 - Atom C (index 29)

/mnt/storage/nobackup/nmb1063/mamba/envs/fegrow/lib/python3.9/site-packages/parmed/structure.py:1775: UnitStrippedWarning: The unit of the quantity is stripped when downcasting to ndarray.
  coords = np.array(value, dtype=np.float64, copy=False, subok=True)
2024-02-01 08:36:57,084 [WARNING] [rdkit_wrapper.py:3213] openff.toolkit.utils.rdkit_wrapper: Warning (not error because allow_undefined_stereo=True): RDMol has unspecified stereochemistry. Undefined chiral centers are:
 - Atom C (index 2)
 - Atom C (index 29)

TIME Completed the molecule generation in 137.4s.
TIME Completed the molecule generation in 186.2s.
TIME changed dir: 0.0s
TIME changed dir: 0.0s
Generated 27 conformers. 
Removed 13 conformers. 
Generated 43 conformers. 
Removed 40 conformers. 
using ani2x
/mnt/storage/nobackup/nmb1063/mamba/envs/fegrow/lib/python3.9/site-packages/torchani/resources/
failed to equip `nnpops` with error: No module named 'NNPOps'
Optimising conformer:   0%|                              | 0/14 [00:00<?, ?it/s]Optimising conformer:   7%|█▌                    | 1/14 [00:03<00:40,  3.09s/it]Optimising conformer:  14%|███▏                  | 2/14 [00:06<00:39,  3.29s/it]Optimising conformer:  21%|████▋                 | 3/14 [00:08<00:31,  2.87s/it]Optimising conformer:  29%|██████▎               | 4/14 [00:11<00:26,  2.67s/it]Optimising conformer:  36%|███████▊              | 5/14 [00:13<00:22,  2.46s/it]Optimising conformer:  43%|█████████▍            | 6/14 [00:15<00:19,  2.38s/it]Optimising conformer:  50%|███████████           | 7/14 [00:18<00:18,  2.63s/it]Optimising conformer:  57%|████████████▌         | 8/14 [00:20<00:14,  2.49s/it]Optimising conformer:  64%|██████████████▏       | 9/14 [00:24<00:13,  2.79s/it]Optimising conformer:  71%|███████████████      | 10/14 [00:27<00:11,  2.99s/it]Optimising conformer:  79%|████████████████▌    | 11/14 [00:29<00:08,  2.71s/it]Optimising conformer:  86%|██████████████████   | 12/14 [00:33<00:05,  2.85s/it]Optimising conformer:  93%|███████████████████▌ | 13/14 [00:35<00:02,  2.86s/it]Optimising conformer: 100%|█████████████████████| 14/14 [00:38<00:00,  2.73s/it]Optimising conformer: 100%|█████████████████████| 14/14 [00:38<00:00,  2.74s/it]
/mnt/storage/nobackup/nmb1063/code/gal/sars-cov-2-main-protease-al-study-combo1/rsearcher.py:89: UserWarning: The ligand was an array (SDF?). Using the first frame. 
  warnings.warn("The ligand was an array (SDF?). Using the first frame. ")
2024-02-01 08:38:29,747 [WARNING] [rdkit_wrapper.py:3213] openff.toolkit.utils.rdkit_wrapper: Warning (not error because allow_undefined_stereo=True): RDMol has unspecified stereochemistry. Undefined chiral centers are:
 - Atom C (index 10)
 - Atom C (index 19)

/mnt/storage/nobackup/nmb1063/mamba/envs/fegrow/lib/python3.9/site-packages/parmed/structure.py:1775: UnitStrippedWarning: The unit of the quantity is stripped when downcasting to ndarray.
  coords = np.array(value, dtype=np.float64, copy=False, subok=True)
2024-02-01 08:38:31,488 [WARNING] [rdkit_wrapper.py:3213] openff.toolkit.utils.rdkit_wrapper: Warning (not error because allow_undefined_stereo=True): RDMol has unspecified stereochemistry. Undefined chiral centers are:
 - Atom C (index 10)
 - Atom C (index 19)

TIME Completed the molecule generation in 100.1s.
TIME changed dir: 0.0s
Generated 44 conformers. 
Removed 38 conformers. 
using ani2x
/mnt/storage/nobackup/nmb1063/mamba/envs/fegrow/lib/python3.9/site-packages/torchani/resources/
failed to equip `nnpops` with error: No module named 'NNPOps'
Optimising conformer:   0%|                               | 0/3 [00:00<?, ?it/s]Optimising conformer:  33%|███████▋               | 1/3 [00:03<00:07,  3.82s/it]Optimising conformer:  67%|███████████████▎       | 2/3 [00:08<00:04,  4.58s/it]Optimising conformer: 100%|███████████████████████| 3/3 [00:11<00:00,  3.62s/it]Optimising conformer: 100%|███████████████████████| 3/3 [00:11<00:00,  3.81s/it]
/mnt/storage/nobackup/nmb1063/code/gal/sars-cov-2-main-protease-al-study-combo1/rsearcher.py:89: UserWarning: The ligand was an array (SDF?). Using the first frame. 
  warnings.warn("The ligand was an array (SDF?). Using the first frame. ")
/mnt/storage/nobackup/nmb1063/mamba/envs/fegrow/lib/python3.9/site-packages/parmed/structure.py:1775: UnitStrippedWarning: The unit of the quantity is stripped when downcasting to ndarray.
  coords = np.array(value, dtype=np.float64, copy=False, subok=True)
TIME Completed the molecule generation in 147.4s.
TIME changed dir: 0.0s
Generated 19 conformers. 
Removed 14 conformers. 
using ani2x
/mnt/storage/nobackup/nmb1063/mamba/envs/fegrow/lib/python3.9/site-packages/torchani/resources/
failed to equip `nnpops` with error: No module named 'NNPOps'
Optimising conformer:   0%|                               | 0/6 [00:00<?, ?it/s]Optimising conformer:  17%|███▊                   | 1/6 [00:06<00:34,  6.92s/it]Optimising conformer:  33%|███████▋               | 2/6 [00:12<00:23,  5.86s/it]Optimising conformer:  50%|███████████▌           | 3/6 [00:16<00:16,  5.38s/it]Optimising conformer:  67%|███████████████▎       | 4/6 [00:20<00:09,  4.51s/it]Optimising conformer:  83%|███████████████████▏   | 5/6 [00:23<00:04,  4.11s/it]using ani2x
/mnt/storage/nobackup/nmb1063/mamba/envs/fegrow/lib/python3.9/site-packages/torchani/resources/
failed to equip `nnpops` with error: No module named 'NNPOps'

Optimising conformer:   0%|                               | 0/5 [00:00<?, ?it/s][A
Optimising conformer:  20%|████▌                  | 1/5 [00:04<00:17,  4.48s/it][A
Optimising conformer:  40%|█████████▏             | 2/5 [00:07<00:10,  3.62s/it][A
Optimising conformer:  60%|█████████████▊         | 3/5 [00:09<00:05,  2.85s/it][AOptimising conformer: 100%|███████████████████████| 6/6 [00:37<00:00,  7.42s/it]Optimising conformer: 100%|███████████████████████| 6/6 [00:37<00:00,  6.21s/it]

Optimising conformer:  80%|██████████████████▍    | 4/5 [00:15<00:04,  4.19s/it][A
Optimising conformer: 100%|███████████████████████| 5/5 [00:20<00:00,  4.30s/it][AOptimising conformer: 100%|███████████████████████| 5/5 [00:20<00:00,  4.04s/it]
/mnt/storage/nobackup/nmb1063/code/gal/sars-cov-2-main-protease-al-study-combo1/rsearcher.py:89: UserWarning: The ligand was an array (SDF?). Using the first frame. 
  warnings.warn("The ligand was an array (SDF?). Using the first frame. ")
2024-02-01 09:04:51,748 - distributed.core - INFO - Event loop was unresponsive in Worker for 4.26s.  This is often caused by long-running GIL-holding functions or moving large chunks of data. This can cause timeouts and instability.
2024-02-01 09:04:51,748 [INFO] [core.py:595] distributed.core: Event loop was unresponsive in Worker for 4.26s.  This is often caused by long-running GIL-holding functions or moving large chunks of data. This can cause timeouts and instability.
2024-02-01 09:05:13,196 - distributed.core - INFO - Event loop was unresponsive in Worker for 5.64s.  This is often caused by long-running GIL-holding functions or moving large chunks of data. This can cause timeouts and instability.
2024-02-01 09:05:13,196 [INFO] [core.py:595] distributed.core: Event loop was unresponsive in Worker for 5.64s.  This is often caused by long-running GIL-holding functions or moving large chunks of data. This can cause timeouts and instability.
/mnt/storage/nobackup/nmb1063/mamba/envs/fegrow/lib/python3.9/site-packages/parmed/structure.py:1775: UnitStrippedWarning: The unit of the quantity is stripped when downcasting to ndarray.
  coords = np.array(value, dtype=np.float64, copy=False, subok=True)
/mnt/storage/nobackup/nmb1063/mamba/envs/fegrow/lib/python3.9/site-packages/parmed/structure.py:1775: UnitStrippedWarning: The unit of the quantity is stripped when downcasting to ndarray.
  coords = np.array(value, dtype=np.float64, copy=False, subok=True)
TIME Completed the molecule generation in 116.6s.
TIME Completed the molecule generation in 74.9s.
TIME changed dir: 0.0s
TIME changed dir: 0.0s
Generated 21 conformers. 
Removed 5 conformers. 
Generated 37 conformers. 
Removed 24 conformers. 
using ani2x
/mnt/storage/nobackup/nmb1063/mamba/envs/fegrow/lib/python3.9/site-packages/torchani/resources/
using ani2x
/mnt/storage/nobackup/nmb1063/mamba/envs/fegrow/lib/python3.9/site-packages/torchani/resources/
failed to equip `nnpops` with error: No module named 'NNPOps'
Optimising conformer:   0%|                              | 0/16 [00:00<?, ?it/s]failed to equip `nnpops` with error: No module named 'NNPOps'

Optimising conformer:   0%|                              | 0/13 [00:00<?, ?it/s][AOptimising conformer:   6%|█▍                    | 1/16 [00:03<00:48,  3.24s/it]Optimising conformer:  12%|██▊                   | 2/16 [00:07<00:51,  3.70s/it]
Optimising conformer:   8%|█▋                    | 1/13 [00:06<01:17,  6.47s/it][A
Optimising conformer:  15%|███▍                  | 2/13 [00:08<00:44,  4.04s/it][AOptimising conformer:  19%|████▏                 | 3/16 [00:11<00:53,  4.10s/it]
Optimising conformer:  23%|█████                 | 3/13 [00:10<00:30,  3.06s/it][A
Optimising conformer:  31%|██████▊               | 4/13 [00:12<00:24,  2.74s/it][AOptimising conformer:  25%|█████▌                | 4/16 [00:16<00:52,  4.37s/it]
Optimising conformer:  38%|████████▍             | 5/13 [00:17<00:27,  3.43s/it][AOptimising conformer:  31%|██████▉               | 5/16 [00:20<00:46,  4.27s/it]Optimising conformer:  38%|████████▎             | 6/16 [00:23<00:36,  3.69s/it]
Optimising conformer:  46%|██████████▏           | 6/13 [00:21<00:25,  3.66s/it][AOptimising conformer:  44%|█████████▋            | 7/16 [00:27<00:34,  3.83s/it]Optimising conformer:  50%|███████████           | 8/16 [00:30<00:29,  3.68s/it]
Optimising conformer:  54%|███████████▊          | 7/13 [00:30<00:31,  5.19s/it][AOptimising conformer:  56%|████████████▍         | 9/16 [00:35<00:28,  4.01s/it]Optimising conformer:  62%|█████████████▏       | 10/16 [00:40<00:25,  4.21s/it]Optimising conformer:  69%|██████████████▍      | 11/16 [00:44<00:21,  4.22s/it]
Optimising conformer:  62%|█████████████▌        | 8/13 [00:46<00:43,  8.80s/it][AOptimising conformer:  75%|███████████████▊     | 12/16 [00:52<00:21,  5.37s/it]
Optimising conformer:  69%|███████████████▏      | 9/13 [00:51<00:30,  7.65s/it][A
Optimising conformer:  77%|████████████████▏    | 10/13 [00:53<00:17,  5.97s/it][AOptimising conformer:  81%|█████████████████    | 13/16 [00:56<00:14,  4.98s/it]
Optimising conformer:  85%|█████████████████▊   | 11/13 [00:55<00:09,  4.69s/it][AOptimising conformer:  88%|██████████████████▍  | 14/16 [00:59<00:09,  4.54s/it]
Optimising conformer:  92%|███████████████████▍ | 12/13 [01:00<00:04,  4.69s/it][AOptimising conformer:  94%|███████████████████▋ | 15/16 [01:04<00:04,  4.53s/it]
Optimising conformer: 100%|█████████████████████| 13/13 [01:03<00:00,  4.16s/it][AOptimising conformer: 100%|█████████████████████| 13/13 [01:03<00:00,  4.87s/it]
Optimising conformer: 100%|█████████████████████| 16/16 [01:07<00:00,  4.21s/it]Optimising conformer: 100%|█████████████████████| 16/16 [01:07<00:00,  4.25s/it]
/mnt/storage/nobackup/nmb1063/code/gal/sars-cov-2-main-protease-al-study-combo1/rsearcher.py:89: UserWarning: The ligand was an array (SDF?). Using the first frame. 
  warnings.warn("The ligand was an array (SDF?). Using the first frame. ")
/mnt/storage/nobackup/nmb1063/mamba/envs/fegrow/lib/python3.9/site-packages/parmed/structure.py:1775: UnitStrippedWarning: The unit of the quantity is stripped when downcasting to ndarray.
  coords = np.array(value, dtype=np.float64, copy=False, subok=True)
TIME Completed the molecule generation in 130.8s.
TIME changed dir: 0.0s
Generated 17 conformers. 
Removed 3 conformers. 
TIME Completed the molecule generation in 136.2s.
using ani2x
/mnt/storage/nobackup/nmb1063/mamba/envs/fegrow/lib/python3.9/site-packages/torchani/resources/
failed to equip `nnpops` with error: No module named 'NNPOps'
Optimising conformer:   0%|                              | 0/14 [00:00<?, ?it/s]Optimising conformer:   7%|█▌                    | 1/14 [00:04<00:54,  4.19s/it]Optimising conformer:  14%|███▏                  | 2/14 [00:05<00:31,  2.66s/it]Optimising conformer:  21%|████▋                 | 3/14 [00:07<00:24,  2.23s/it]Optimising conformer:  29%|██████▎               | 4/14 [00:09<00:19,  1.99s/it]/mnt/storage/nobackup/nmb1063/mamba/envs/fegrow/lib/python3.9/site-packages/parmed/structure.py:1775: UnitStrippedWarning: The unit of the quantity is stripped when downcasting to ndarray.
  coords = np.array(value, dtype=np.float64, copy=False, subok=True)
Optimising conformer:  36%|███████▊              | 5/14 [00:11<00:19,  2.15s/it]Optimising conformer:  43%|█████████▍            | 6/14 [00:13<00:17,  2.22s/it]Optimising conformer:  50%|███████████           | 7/14 [00:16<00:17,  2.46s/it]Optimising conformer:  57%|████████████▌         | 8/14 [00:18<00:13,  2.20s/it]Optimising conformer:  64%|██████████████▏       | 9/14 [00:21<00:11,  2.31s/it]Optimising conformer:  71%|███████████████      | 10/14 [00:43<00:33,  8.42s/it]Optimising conformer:  79%|████████████████▌    | 11/14 [00:45<00:19,  6.58s/it]Optimising conformer:  86%|██████████████████   | 12/14 [00:47<00:10,  5.07s/it]Optimising conformer:  93%|███████████████████▌ | 13/14 [00:50<00:04,  4.53s/it]Optimising conformer: 100%|█████████████████████| 14/14 [00:53<00:00,  4.19s/it]Optimising conformer: 100%|█████████████████████| 14/14 [00:53<00:00,  3.85s/it]
/mnt/storage/nobackup/nmb1063/code/gal/sars-cov-2-main-protease-al-study-combo1/rsearcher.py:89: UserWarning: The ligand was an array (SDF?). Using the first frame. 
  warnings.warn("The ligand was an array (SDF?). Using the first frame. ")
TIME changed dir: 0.0s
Generated 21 conformers. 
Removed 19 conformers. 
using ani2x
/mnt/storage/nobackup/nmb1063/mamba/envs/fegrow/lib/python3.9/site-packages/torchani/resources/
TIME Completed the molecule generation in 94.2s.
failed to equip `nnpops` with error: No module named 'NNPOps'
Optimising conformer:   0%|                               | 0/2 [00:00<?, ?it/s]Optimising conformer:  50%|███████████▌           | 1/2 [00:14<00:14, 14.91s/it]Optimising conformer: 100%|███████████████████████| 2/2 [00:17<00:00,  7.89s/it]Optimising conformer: 100%|███████████████████████| 2/2 [00:17<00:00,  8.94s/it]
slurmstepd: error: *** JOB 19912155 ON sb017 CANCELLED AT 2024-02-01T09:54:43 ***
