hostname sb062.cluster
ipconfig 1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN group default qlen 1000 link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00 inet 127.0.0.1/8 scope host lo valid_lft forever preferred_lft forever inet6 ::1/128 scope host valid_lft forever preferred_lft forever 2: enp4s0f0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 9000 qdisc mq state UP group default qlen 1000 link/ether a0:8c:f8:74:c8:e8 brd ff:ff:ff:ff:ff:ff inet 10.3.81.142/22 brd 10.3.83.255 scope global enp4s0f0 valid_lft forever preferred_lft forever inet6 fe80::a28c:f8ff:fe74:c8e8/64 scope link valid_lft forever preferred_lft forever 3: enp4s0f1: <BROADCAST,MULTICAST> mtu 1500 qdisc noop state DOWN group default qlen 1000 link/ether a0:8c:f8:74:c8:e9 brd ff:ff:ff:ff:ff:ff 4: enp4s0f2: <BROADCAST,MULTICAST> mtu 1500 qdisc noop state DOWN group default qlen 1000 link/ether a0:8c:f8:74:c8:ea brd ff:ff:ff:ff:ff:ff 5: enp4s0f3: <BROADCAST,MULTICAST> mtu 1500 qdisc noop state DOWN group default qlen 1000 link/ether a0:8c:f8:74:c8:eb brd ff:ff:ff:ff:ff:ff 6: ib0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 4092 qdisc pfifo_fast state UP group default qlen 256 link/infiniband 80:00:00:29:fe:80:00:00:00:00:00:00:70:79:90:03:00:50:5d:a3 brd 00:ff:ff:ff:ff:12:40:1b:ff:ff:00:00:00:00:00:00:ff:ff:ff:ff inet 10.3.89.142/22 brd 10.3.91.255 scope global ib0 valid_lft forever preferred_lft forever inet 10.3.97.142/22 brd 10.3.99.255 scope global ib0:1 valid_lft forever preferred_lft forever inet6 fe80::7279:9003:50:5da3/64 scope link valid_lft forever preferred_lft forever 7: ib1: <BROADCAST,MULTICAST> mtu 4092 qdisc noop state DOWN group default qlen 256 link/infiniband 80:00:00:29:fe:80:00:00:00:00:00:00:70:79:90:03:00:50:5d:a4 brd 00:ff:ff:ff:ff:12:40:1b:ff:ff:00:00:00:00:00:00:ff:ff:ff:ff
2024-01-18 12:17:38,072 - distributed.nanny - INFO -         Start Nanny at: 'tcp://10.3.89.142:43082'
2024-01-18 12:17:38,178 - distributed.nanny - INFO -         Start Nanny at: 'tcp://10.3.89.142:46040'
2024-01-18 12:17:39,946 - distributed.diskutils - INFO - Found stale lock file and directory '/scratch/dask-worker-space/worker-h4d78c_3', purging
2024-01-18 12:17:39,946 - distributed.diskutils - INFO - Found stale lock file and directory '/scratch/dask-worker-space/worker-4q0r78o8', purging
2024-01-18 12:18:02,204 - distributed.worker - INFO -       Start worker at:    tcp://10.3.89.142:35561
2024-01-18 12:18:02,204 - distributed.worker - INFO -          Listening to:    tcp://10.3.89.142:35561
2024-01-18 12:18:02,204 - distributed.worker - INFO -           Worker name:         SLURMCluster-353-0
2024-01-18 12:18:02,205 - distributed.worker - INFO -          dashboard at:          10.3.89.142:41357
2024-01-18 12:18:02,204 - distributed.worker - INFO -       Start worker at:    tcp://10.3.89.142:39469
2024-01-18 12:18:02,205 - distributed.worker - INFO - Waiting to connect to:     tcp://10.3.88.12:40797
2024-01-18 12:18:02,205 - distributed.worker - INFO - -------------------------------------------------
2024-01-18 12:18:02,205 - distributed.worker - INFO -          Listening to:    tcp://10.3.89.142:39469
2024-01-18 12:18:02,205 - distributed.worker - INFO -           Worker name:         SLURMCluster-353-1
2024-01-18 12:18:02,205 - distributed.worker - INFO -               Threads:                          2
2024-01-18 12:18:02,205 - distributed.worker - INFO -          dashboard at:          10.3.89.142:38392
2024-01-18 12:18:02,205 - distributed.worker - INFO -                Memory:                  10.24 GiB
2024-01-18 12:18:02,205 - distributed.worker - INFO - Waiting to connect to:     tcp://10.3.88.12:40797
2024-01-18 12:18:02,205 - distributed.worker - INFO -       Local Directory: /scratch/dask-worker-space/worker-3z52sp35
2024-01-18 12:18:02,205 - distributed.worker - INFO - -------------------------------------------------
2024-01-18 12:18:02,205 - distributed.worker - INFO - -------------------------------------------------
2024-01-18 12:18:02,205 - distributed.worker - INFO -               Threads:                          2
2024-01-18 12:18:02,205 - distributed.worker - INFO -                Memory:                  10.24 GiB
2024-01-18 12:18:02,205 - distributed.worker - INFO -       Local Directory: /scratch/dask-worker-space/worker-54lbflnr
2024-01-18 12:18:02,205 - distributed.worker - INFO - -------------------------------------------------
2024-01-18 12:18:02,270 - distributed.worker - INFO -         Registered to:     tcp://10.3.88.12:40797
2024-01-18 12:18:02,270 - distributed.worker - INFO - -------------------------------------------------
2024-01-18 12:18:02,271 - distributed.core - INFO - Starting established connection to tcp://10.3.88.12:40797
2024-01-18 12:18:02,273 - distributed.worker - INFO -         Registered to:     tcp://10.3.88.12:40797
2024-01-18 12:18:02,273 - distributed.worker - INFO - -------------------------------------------------
2024-01-18 12:18:02,274 - distributed.core - INFO - Starting established connection to tcp://10.3.88.12:40797
2024-01-18 12:49:39,106 - distributed.core - INFO - Connection to tcp://10.3.88.12:40797 has been closed.
2024-01-18 12:49:39,107 - distributed.core - INFO - Connection to tcp://10.3.88.12:40797 has been closed.
2024-01-18 12:49:39,107 - distributed.worker - INFO - Stopping worker at tcp://10.3.89.142:39469. Reason: worker-handle-scheduler-connection-broken
2024-01-18 12:49:39,107 - distributed.worker - INFO - Stopping worker at tcp://10.3.89.142:35561. Reason: worker-handle-scheduler-connection-broken
2024-01-18 12:49:39,108 - distributed.worker - ERROR - Failed to communicate with scheduler during heartbeat.
Traceback (most recent call last):
  File "/mnt/storage/nobackup/nmb1063/mamba/envs/fegrow/lib/python3.9/site-packages/tornado/iostream.py", line 861, in _read_to_buffer
    bytes_read = self.read_from_fd(buf)
  File "/mnt/storage/nobackup/nmb1063/mamba/envs/fegrow/lib/python3.9/site-packages/tornado/iostream.py", line 1116, in read_from_fd
    return self.socket.recv_into(buf, len(buf))
ConnectionResetError: [Errno 104] Connection reset by peer

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/mnt/storage/nobackup/nmb1063/mamba/envs/fegrow/lib/python3.9/site-packages/distributed/worker.py", line 1237, in heartbeat
    response = await retry_operation(
  File "/mnt/storage/nobackup/nmb1063/mamba/envs/fegrow/lib/python3.9/site-packages/distributed/utils_comm.py", line 434, in retry_operation
    return await retry(
  File "/mnt/storage/nobackup/nmb1063/mamba/envs/fegrow/lib/python3.9/site-packages/distributed/utils_comm.py", line 413, in retry
    return await coro()
  File "/mnt/storage/nobackup/nmb1063/mamba/envs/fegrow/lib/python3.9/site-packages/distributed/core.py", line 1227, in send_recv_from_rpc
    return await send_recv(comm=comm, op=key, **kwargs)
  File "/mnt/storage/nobackup/nmb1063/mamba/envs/fegrow/lib/python3.9/site-packages/distributed/core.py", line 986, in send_recv
    response = await comm.read(deserializers=deserializers)
  File "/mnt/storage/nobackup/nmb1063/mamba/envs/fegrow/lib/python3.9/site-packages/distributed/comm/tcp.py", line 241, in read
    convert_stream_closed_error(self, e)
  File "/mnt/storage/nobackup/nmb1063/mamba/envs/fegrow/lib/python3.9/site-packages/distributed/comm/tcp.py", line 142, in convert_stream_closed_error
    raise CommClosedError(f"in {obj}: {exc.__class__.__name__}: {exc}") from exc
distributed.comm.core.CommClosedError: in <TCP (closed) ConnectionPool.heartbeat_worker local=tcp://10.3.89.142:39710 remote=tcp://10.3.88.12:40797>: ConnectionResetError: [Errno 104] Connection reset by peer
2024-01-18 12:49:39,116 - distributed.nanny - INFO - Closing Nanny gracefully at 'tcp://10.3.89.142:46040'. Reason: worker-handle-scheduler-connection-broken
2024-01-18 12:49:39,108 - distributed.worker - ERROR - Failed to communicate with scheduler during heartbeat.
Traceback (most recent call last):
  File "/mnt/storage/nobackup/nmb1063/mamba/envs/fegrow/lib/python3.9/site-packages/tornado/iostream.py", line 861, in _read_to_buffer
    bytes_read = self.read_from_fd(buf)
  File "/mnt/storage/nobackup/nmb1063/mamba/envs/fegrow/lib/python3.9/site-packages/tornado/iostream.py", line 1116, in read_from_fd
    return self.socket.recv_into(buf, len(buf))
ConnectionResetError: [Errno 104] Connection reset by peer

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/mnt/storage/nobackup/nmb1063/mamba/envs/fegrow/lib/python3.9/site-packages/distributed/worker.py", line 1237, in heartbeat
    response = await retry_operation(
  File "/mnt/storage/nobackup/nmb1063/mamba/envs/fegrow/lib/python3.9/site-packages/distributed/utils_comm.py", line 434, in retry_operation
    return await retry(
  File "/mnt/storage/nobackup/nmb1063/mamba/envs/fegrow/lib/python3.9/site-packages/distributed/utils_comm.py", line 413, in retry
    return await coro()
  File "/mnt/storage/nobackup/nmb1063/mamba/envs/fegrow/lib/python3.9/site-packages/distributed/core.py", line 1227, in send_recv_from_rpc
    return await send_recv(comm=comm, op=key, **kwargs)
  File "/mnt/storage/nobackup/nmb1063/mamba/envs/fegrow/lib/python3.9/site-packages/distributed/core.py", line 986, in send_recv
    response = await comm.read(deserializers=deserializers)
  File "/mnt/storage/nobackup/nmb1063/mamba/envs/fegrow/lib/python3.9/site-packages/distributed/comm/tcp.py", line 241, in read
    convert_stream_closed_error(self, e)
  File "/mnt/storage/nobackup/nmb1063/mamba/envs/fegrow/lib/python3.9/site-packages/distributed/comm/tcp.py", line 142, in convert_stream_closed_error
    raise CommClosedError(f"in {obj}: {exc.__class__.__name__}: {exc}") from exc
distributed.comm.core.CommClosedError: in <TCP (closed) ConnectionPool.heartbeat_worker local=tcp://10.3.89.142:39712 remote=tcp://10.3.88.12:40797>: ConnectionResetError: [Errno 104] Connection reset by peer
2024-01-18 12:49:39,119 - distributed.nanny - INFO - Closing Nanny gracefully at 'tcp://10.3.89.142:43082'. Reason: worker-handle-scheduler-connection-broken
2024-01-18 12:49:39,119 - distributed.nanny - INFO - Worker closed
2024-01-18 12:49:39,121 - distributed.nanny - INFO - Worker closed
2024-01-18 12:49:41,120 - distributed.nanny - ERROR - Worker process died unexpectedly
2024-01-18 12:49:41,122 - distributed.nanny - ERROR - Worker process died unexpectedly
2024-01-18 12:49:41,460 - distributed.nanny - INFO - Closing Nanny at 'tcp://10.3.89.142:43082'. Reason: nanny-close-gracefully
2024-01-18 12:49:41,471 - distributed.nanny - INFO - Closing Nanny at 'tcp://10.3.89.142:46040'. Reason: nanny-close-gracefully
2024-01-18 12:49:41,472 - distributed.dask_worker - INFO - End worker
