hostname sb030.cluster
ipconfig 1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN group default qlen 1000 link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00 inet 127.0.0.1/8 scope host lo valid_lft forever preferred_lft forever inet6 ::1/128 scope host valid_lft forever preferred_lft forever 2: enp4s0f0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 9000 qdisc mq state UP group default qlen 1000 link/ether a0:8c:f8:34:c9:e8 brd ff:ff:ff:ff:ff:ff inet 10.3.81.110/22 brd 10.3.83.255 scope global enp4s0f0 valid_lft forever preferred_lft forever inet6 fe80::a28c:f8ff:fe34:c9e8/64 scope link valid_lft forever preferred_lft forever 3: enp4s0f1: <BROADCAST,MULTICAST> mtu 1500 qdisc noop state DOWN group default qlen 1000 link/ether a0:8c:f8:34:c9:e9 brd ff:ff:ff:ff:ff:ff 4: enp4s0f2: <BROADCAST,MULTICAST> mtu 1500 qdisc noop state DOWN group default qlen 1000 link/ether a0:8c:f8:34:c9:ea brd ff:ff:ff:ff:ff:ff 5: enp4s0f3: <BROADCAST,MULTICAST> mtu 1500 qdisc noop state DOWN group default qlen 1000 link/ether a0:8c:f8:34:c9:eb brd ff:ff:ff:ff:ff:ff 6: ib0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 4092 qdisc pfifo_fast state UP group default qlen 256 link/infiniband 80:00:00:29:fe:80:00:00:00:00:00:00:38:bc:01:03:00:4c:f3:10 brd 00:ff:ff:ff:ff:12:40:1b:ff:ff:00:00:00:00:00:00:ff:ff:ff:ff inet 10.3.89.110/22 brd 10.3.91.255 scope global ib0 valid_lft forever preferred_lft forever inet 10.3.97.110/22 brd 10.3.99.255 scope global ib0:1 valid_lft forever preferred_lft forever inet6 fe80::3abc:103:4c:f310/64 scope link valid_lft forever preferred_lft forever 7: ib1: <NO-CARRIER,BROADCAST,MULTICAST,UP> mtu 4092 qdisc pfifo_fast state DOWN group default qlen 256 link/infiniband 80:00:00:29:fe:80:00:00:00:00:00:00:38:bc:01:03:00:4c:f3:11 brd 00:ff:ff:ff:ff:12:40:1b:ff:ff:00:00:00:00:00:00:ff:ff:ff:ff
2024-01-28 23:20:28,239 - distributed.nanny - INFO -         Start Nanny at: 'tcp://10.3.89.110:40716'
2024-01-28 23:20:32,973 - distributed.diskutils - INFO - Found stale lock file and directory '/scratch/dask-worker-space/worker-if1cwfx0', purging
2024-01-28 23:20:42,230 - distributed.worker - INFO -       Start worker at:    tcp://10.3.89.110:46092
2024-01-28 23:20:42,235 - distributed.worker - INFO -          Listening to:    tcp://10.3.89.110:46092
2024-01-28 23:20:42,235 - distributed.worker - INFO -           Worker name:           SLURMCluster-282
2024-01-28 23:20:42,235 - distributed.worker - INFO -          dashboard at:          10.3.89.110:43450
2024-01-28 23:20:42,236 - distributed.worker - INFO - Waiting to connect to:     tcp://10.3.88.11:44532
2024-01-28 23:20:42,236 - distributed.worker - INFO - -------------------------------------------------
2024-01-28 23:20:42,236 - distributed.worker - INFO -               Threads:                          2
2024-01-28 23:20:42,236 - distributed.worker - INFO -                Memory:                  20.49 GiB
2024-01-28 23:20:42,236 - distributed.worker - INFO -       Local Directory: /scratch/dask-worker-space/worker-7lquw2ut
2024-01-28 23:20:42,236 - distributed.worker - INFO - -------------------------------------------------
2024-01-28 23:20:42,343 - distributed.worker - INFO -         Registered to:     tcp://10.3.88.11:44532
2024-01-28 23:20:42,343 - distributed.worker - INFO - -------------------------------------------------
2024-01-28 23:20:42,344 - distributed.core - INFO - Starting established connection to tcp://10.3.88.11:44532
2024-01-28 23:27:11,804 - distributed.core - INFO - Event loop was unresponsive in Nanny for 8.88s.  This is often caused by long-running GIL-holding functions or moving large chunks of data. This can cause timeouts and instability.
2024-01-28 23:27:11,806 - distributed.core - INFO - Event loop was unresponsive in Worker for 8.88s.  This is often caused by long-running GIL-holding functions or moving large chunks of data. This can cause timeouts and instability.
2024-01-28 23:37:10,505 - distributed.core - INFO - Event loop was unresponsive in Worker for 5.16s.  This is often caused by long-running GIL-holding functions or moving large chunks of data. This can cause timeouts and instability.
2024-01-28 23:44:13,822 - distributed.core - INFO - Event loop was unresponsive in Worker for 9.28s.  This is often caused by long-running GIL-holding functions or moving large chunks of data. This can cause timeouts and instability.
2024-01-28 23:44:13,820 - distributed.core - INFO - Event loop was unresponsive in Nanny for 9.26s.  This is often caused by long-running GIL-holding functions or moving large chunks of data. This can cause timeouts and instability.
2024-01-28 23:52:41,484 - distributed.core - INFO - Event loop was unresponsive in Worker for 61.94s.  This is often caused by long-running GIL-holding functions or moving large chunks of data. This can cause timeouts and instability.
2024-01-28 23:52:41,484 [INFO] [core.py:595] distributed.core: Event loop was unresponsive in Worker for 61.94s.  This is often caused by long-running GIL-holding functions or moving large chunks of data. This can cause timeouts and instability.
/mnt/storage/nobackup/nmb1063/mamba/envs/fegrow/lib/python3.9/site-packages/parmed/structure.py:1775: UnitStrippedWarning: The unit of the quantity is stripped when downcasting to ndarray.
  coords = np.array(value, dtype=np.float64, copy=False, subok=True)
/mnt/storage/nobackup/nmb1063/mamba/envs/fegrow/lib/python3.9/site-packages/torchani/__init__.py:55: UserWarning: Dependency not satisfied, torchani.ase will not be available
  warnings.warn("Dependency not satisfied, torchani.ase will not be available")
2024-01-28 23:53:24,267 [WARNING] [__init__.py:5] root: Warning: importing 'simtk.openmm' is deprecated.  Import 'openmm' instead.
TIME changed dir: 0.0s
TIME changed dir: 0.0s
Generated 8 conformers. 
Generated 7 conformers. 
Removed 5 conformers. 
Removed 4 conformers. 
using ani2x
/mnt/storage/nobackup/nmb1063/mamba/envs/fegrow/lib/python3.9/site-packages/torchani/resources/
failed to equip `nnpops` with error: No module named 'NNPOps'
Optimising conformer:   0%|                               | 0/2 [00:00<?, ?it/s][W BinaryOps.cpp:601] Warning: floor_divide is deprecated, and will be removed in a future version of pytorch. It currently rounds toward 0 (like the 'trunc' function NOT 'floor'). This results in incorrect rounding for negative values.
To keep the current behavior, use torch.div(a, b, rounding_mode='trunc'), or for actual floor division, use torch.div(a, b, rounding_mode='floor'). (function operator())
Optimising conformer:  50%|███████████▌           | 1/2 [00:05<00:05,  5.22s/it]Optimising conformer: 100%|███████████████████████| 2/2 [00:07<00:00,  3.70s/it]Optimising conformer: 100%|███████████████████████| 2/2 [00:07<00:00,  3.93s/it]
/mnt/storage/nobackup/nmb1063/code/gal/sars-cov-2-main-protease-al-study-plip/rsearcher.py:89: UserWarning: The ligand was an array (SDF?). Using the first frame. 
  warnings.warn("The ligand was an array (SDF?). Using the first frame. ")
TIME Completed the molecule generation in 60.2s.
using ani2x
/mnt/storage/nobackup/nmb1063/mamba/envs/fegrow/lib/python3.9/site-packages/torchani/resources/
failed to equip `nnpops` with error: No module named 'NNPOps'
Optimising conformer:   0%|                               | 0/4 [00:00<?, ?it/s]Optimising conformer:  25%|█████▊                 | 1/4 [00:03<00:09,  3.16s/it]Optimising conformer:  50%|███████████▌           | 2/4 [00:06<00:06,  3.10s/it]Optimising conformer:  75%|█████████████████▎     | 3/4 [00:07<00:02,  2.46s/it]Optimising conformer: 100%|███████████████████████| 4/4 [00:09<00:00,  2.20s/it]Optimising conformer: 100%|███████████████████████| 4/4 [00:09<00:00,  2.43s/it]
/mnt/storage/nobackup/nmb1063/code/gal/sars-cov-2-main-protease-al-study-plip/rsearcher.py:89: UserWarning: The ligand was an array (SDF?). Using the first frame. 
  warnings.warn("The ligand was an array (SDF?). Using the first frame. ")
2024-01-29 00:09:33,930 - distributed.core - INFO - Event loop was unresponsive in Worker for 3.71s.  This is often caused by long-running GIL-holding functions or moving large chunks of data. This can cause timeouts and instability.
2024-01-29 00:09:33,930 [INFO] [core.py:595] distributed.core: Event loop was unresponsive in Worker for 3.71s.  This is often caused by long-running GIL-holding functions or moving large chunks of data. This can cause timeouts and instability.
2024-01-29 00:24:26,432 [WARNING] [rdkit_wrapper.py:3213] openff.toolkit.utils.rdkit_wrapper: Warning (not error because allow_undefined_stereo=True): RDMol has unspecified stereochemistry. Undefined chiral centers are:
 - Atom C (index 3)

/mnt/storage/nobackup/nmb1063/mamba/envs/fegrow/lib/python3.9/site-packages/parmed/structure.py:1775: UnitStrippedWarning: The unit of the quantity is stripped when downcasting to ndarray.
  coords = np.array(value, dtype=np.float64, copy=False, subok=True)
2024-01-29 00:24:30,639 [WARNING] [rdkit_wrapper.py:3213] openff.toolkit.utils.rdkit_wrapper: Warning (not error because allow_undefined_stereo=True): RDMol has unspecified stereochemistry. Undefined chiral centers are:
 - Atom C (index 3)

2024-01-29 00:24:31,088 [WARNING] [rdkit_wrapper.py:3213] openff.toolkit.utils.rdkit_wrapper: Warning (not error because allow_undefined_stereo=True): RDMol has unspecified stereochemistry. Undefined chiral centers are:
 - Atom C (index 1)

/mnt/storage/nobackup/nmb1063/mamba/envs/fegrow/lib/python3.9/site-packages/parmed/structure.py:1775: UnitStrippedWarning: The unit of the quantity is stripped when downcasting to ndarray.
  coords = np.array(value, dtype=np.float64, copy=False, subok=True)
2024-01-29 00:24:33,438 [WARNING] [rdkit_wrapper.py:3213] openff.toolkit.utils.rdkit_wrapper: Warning (not error because allow_undefined_stereo=True): RDMol has unspecified stereochemistry. Undefined chiral centers are:
 - Atom C (index 1)

TIME Completed the molecule generation in 95.1s.
TIME changed dir: 0.0s
TIME changed dir: 0.0s
Generated 19 conformers. 
Removed 15 conformers. 
Generated 44 conformers. 
Removed 36 conformers. 
Using force field
Optimising conformer:   0%|                               | 0/4 [00:00<?, ?it/s]Optimising conformer:  25%|█████▊                 | 1/4 [00:01<00:03,  1.08s/it]Optimising conformer:  50%|███████████▌           | 2/4 [00:01<00:01,  1.15it/s]Optimising conformer:  75%|█████████████████▎     | 3/4 [00:03<00:01,  1.22s/it]Optimising conformer: 100%|███████████████████████| 4/4 [00:04<00:00,  1.24s/it]Optimising conformer: 100%|███████████████████████| 4/4 [00:04<00:00,  1.18s/it]
/mnt/storage/nobackup/nmb1063/code/gal/sars-cov-2-main-protease-al-study-plip/rsearcher.py:89: UserWarning: The ligand was an array (SDF?). Using the first frame. 
  warnings.warn("The ligand was an array (SDF?). Using the first frame. ")
/mnt/storage/nobackup/nmb1063/mamba/envs/fegrow/lib/python3.9/site-packages/parmed/structure.py:1775: UnitStrippedWarning: The unit of the quantity is stripped when downcasting to ndarray.
  coords = np.array(value, dtype=np.float64, copy=False, subok=True)
TIME Completed the molecule generation in 60.4s.
TIME changed dir: 0.0s
Generated 42 conformers. 
Removed 30 conformers. 
using ani2x
/mnt/storage/nobackup/nmb1063/mamba/envs/fegrow/lib/python3.9/site-packages/torchani/resources/
using ani2x
/mnt/storage/nobackup/nmb1063/mamba/envs/fegrow/lib/python3.9/site-packages/torchani/resources/
failed to equip `nnpops` with error: No module named 'NNPOps'
failed to equip `nnpops` with error: No module named 'NNPOps'
Optimising conformer:   0%|                               | 0/8 [00:00<?, ?it/s]
Optimising conformer:   0%|                              | 0/12 [00:00<?, ?it/s][A
Optimising conformer:   8%|█▊                    | 1/12 [00:03<00:37,  3.41s/it][AOptimising conformer:  12%|██▉                    | 1/8 [00:06<00:46,  6.59s/it]
Optimising conformer:  17%|███▋                  | 2/12 [00:05<00:28,  2.82s/it][A
Optimising conformer:  25%|█████▌                | 3/12 [00:08<00:24,  2.74s/it][A
Optimising conformer:  33%|███████▎              | 4/12 [00:10<00:20,  2.52s/it][AOptimising conformer:  25%|█████▊                 | 2/8 [00:12<00:38,  6.36s/it]
Optimising conformer:  42%|█████████▏            | 5/12 [00:12<00:16,  2.33s/it][A
Optimising conformer:  50%|███████████           | 6/12 [00:14<00:13,  2.20s/it][AOptimising conformer:  38%|████████▋              | 3/8 [00:17<00:27,  5.54s/it]
Optimising conformer:  58%|████████████▊         | 7/12 [00:19<00:15,  3.16s/it][A
Optimising conformer:  67%|██████████████▋       | 8/12 [00:21<00:10,  2.71s/it][A
Optimising conformer:  75%|████████████████▌     | 9/12 [00:23<00:07,  2.55s/it][AOptimising conformer:  50%|███████████▌           | 4/8 [00:25<00:26,  6.53s/it]
Optimising conformer:  83%|█████████████████▌   | 10/12 [00:26<00:05,  2.66s/it][A
Optimising conformer:  92%|███████████████████▎ | 11/12 [00:28<00:02,  2.50s/it][AOptimising conformer:  62%|██████████████▍        | 5/8 [00:29<00:17,  5.83s/it]
Optimising conformer: 100%|█████████████████████| 12/12 [00:31<00:00,  2.53s/it][AOptimising conformer: 100%|█████████████████████| 12/12 [00:31<00:00,  2.61s/it]
/mnt/storage/nobackup/nmb1063/code/gal/sars-cov-2-main-protease-al-study-plip/rsearcher.py:89: UserWarning: The ligand was an array (SDF?). Using the first frame. 
  warnings.warn("The ligand was an array (SDF?). Using the first frame. ")
Optimising conformer:  75%|█████████████████▎     | 6/8 [00:33<00:09,  4.92s/it]Optimising conformer:  88%|████████████████████▏  | 7/8 [00:36<00:04,  4.49s/it]Optimising conformer: 100%|███████████████████████| 8/8 [00:39<00:00,  3.82s/it]Optimising conformer: 100%|███████████████████████| 8/8 [00:39<00:00,  4.89s/it]
2024-01-29 00:43:41,703 - distributed.core - INFO - Event loop was unresponsive in Worker for 4.86s.  This is often caused by long-running GIL-holding functions or moving large chunks of data. This can cause timeouts and instability.
2024-01-29 00:43:41,703 [INFO] [core.py:595] distributed.core: Event loop was unresponsive in Worker for 4.86s.  This is often caused by long-running GIL-holding functions or moving large chunks of data. This can cause timeouts and instability.
2024-01-29 00:44:01,933 - distributed.core - INFO - Event loop was unresponsive in Worker for 5.09s.  This is often caused by long-running GIL-holding functions or moving large chunks of data. This can cause timeouts and instability.
2024-01-29 00:44:01,933 [INFO] [core.py:595] distributed.core: Event loop was unresponsive in Worker for 5.09s.  This is often caused by long-running GIL-holding functions or moving large chunks of data. This can cause timeouts and instability.
/mnt/storage/nobackup/nmb1063/mamba/envs/fegrow/lib/python3.9/site-packages/parmed/structure.py:1775: UnitStrippedWarning: The unit of the quantity is stripped when downcasting to ndarray.
  coords = np.array(value, dtype=np.float64, copy=False, subok=True)
2024-01-29 00:58:20,234 [WARNING] [rdkit_wrapper.py:3213] openff.toolkit.utils.rdkit_wrapper: Warning (not error because allow_undefined_stereo=True): RDMol has unspecified stereochemistry. Undefined chiral centers are:
 - Atom N (index 6)

/mnt/storage/nobackup/nmb1063/mamba/envs/fegrow/lib/python3.9/site-packages/parmed/structure.py:1775: UnitStrippedWarning: The unit of the quantity is stripped when downcasting to ndarray.
  coords = np.array(value, dtype=np.float64, copy=False, subok=True)
2024-01-29 00:58:23,176 [WARNING] [rdkit_wrapper.py:3213] openff.toolkit.utils.rdkit_wrapper: Warning (not error because allow_undefined_stereo=True): RDMol has unspecified stereochemistry. Undefined chiral centers are:
 - Atom N (index 6)

TIME Completed the molecule generation in 91.4s.
TIME Completed the molecule generation in 158.4s.
TIME changed dir: 0.0s
TIME changed dir: 0.0s
Generated 34 conformers. 
Generated 11 conformers. 
Removed 10 conformers. 
Removed 20 conformers. 
using ani2x
/mnt/storage/nobackup/nmb1063/mamba/envs/fegrow/lib/python3.9/site-packages/torchani/resources/
failed to equip `nnpops` with error: No module named 'NNPOps'
Optimising conformer:   0%|                              | 0/14 [00:00<?, ?it/s]Optimising conformer:   7%|█▌                    | 1/14 [00:04<01:03,  4.89s/it]Optimising conformer:  14%|███▏                  | 2/14 [00:07<00:39,  3.32s/it]Optimising conformer:  21%|████▋                 | 3/14 [00:10<00:37,  3.38s/it]Optimising conformer:  29%|██████▎               | 4/14 [00:12<00:28,  2.86s/it]Optimising conformer:  36%|███████▊              | 5/14 [00:15<00:24,  2.71s/it]Optimising conformer:  43%|█████████▍            | 6/14 [00:16<00:19,  2.42s/it]Optimising conformer:  50%|███████████           | 7/14 [00:19<00:18,  2.61s/it]Optimising conformer:  57%|████████████▌         | 8/14 [00:21<00:13,  2.30s/it]Optimising conformer:  64%|██████████████▏       | 9/14 [00:23<00:10,  2.09s/it]Optimising conformer:  71%|███████████████      | 10/14 [00:25<00:08,  2.22s/it]Optimising conformer:  79%|████████████████▌    | 11/14 [00:29<00:07,  2.66s/it]Optimising conformer:  86%|██████████████████   | 12/14 [00:32<00:05,  2.74s/it]Optimising conformer:  93%|███████████████████▌ | 13/14 [00:33<00:02,  2.36s/it]Optimising conformer: 100%|█████████████████████| 14/14 [00:36<00:00,  2.60s/it]Optimising conformer: 100%|█████████████████████| 14/14 [00:36<00:00,  2.64s/it]
/mnt/storage/nobackup/nmb1063/code/gal/sars-cov-2-main-protease-al-study-plip/rsearcher.py:89: UserWarning: The ligand was an array (SDF?). Using the first frame. 
  warnings.warn("The ligand was an array (SDF?). Using the first frame. ")
/mnt/storage/nobackup/nmb1063/mamba/envs/fegrow/lib/python3.9/site-packages/parmed/structure.py:1775: UnitStrippedWarning: The unit of the quantity is stripped when downcasting to ndarray.
  coords = np.array(value, dtype=np.float64, copy=False, subok=True)
TIME Completed the molecule generation in 87.0s.
TIME changed dir: 0.0s
Generated 28 conformers. 
Removed 12 conformers. 
using ani2x
/mnt/storage/nobackup/nmb1063/mamba/envs/fegrow/lib/python3.9/site-packages/torchani/resources/
failed to equip `nnpops` with error: No module named 'NNPOps'
Optimising conformer:   0%|                              | 0/16 [00:00<?, ?it/s]Optimising conformer:   6%|█▍                    | 1/16 [00:02<00:42,  2.85s/it]Optimising conformer:  12%|██▊                   | 2/16 [00:04<00:34,  2.43s/it]Optimising conformer:  19%|████▏                 | 3/16 [00:27<02:28, 11.45s/it]Optimising conformer:  25%|█████▌                | 4/16 [00:29<01:33,  7.80s/it]Optimising conformer:  31%|██████▉               | 5/16 [00:32<01:05,  5.94s/it]Optimising conformer:  38%|████████▎             | 6/16 [00:33<00:45,  4.55s/it]Optimising conformer:  44%|█████████▋            | 7/16 [00:35<00:33,  3.73s/it]Optimising conformer:  50%|███████████           | 8/16 [00:39<00:28,  3.60s/it]Optimising conformer:  56%|████████████▍         | 9/16 [00:41<00:22,  3.15s/it]using ani2x
/mnt/storage/nobackup/nmb1063/mamba/envs/fegrow/lib/python3.9/site-packages/torchani/resources/
failed to equip `nnpops` with error: No module named 'NNPOps'

Optimising conformer:   0%|                               | 0/1 [00:00<?, ?it/s][AOptimising conformer:  62%|█████████████▏       | 10/16 [00:43<00:16,  2.83s/it]
Optimising conformer: 100%|███████████████████████| 1/1 [00:04<00:00,  4.21s/it][AOptimising conformer: 100%|███████████████████████| 1/1 [00:04<00:00,  4.21s/it]
/mnt/storage/nobackup/nmb1063/code/gal/sars-cov-2-main-protease-al-study-plip/rsearcher.py:89: UserWarning: The ligand was an array (SDF?). Using the first frame. 
  warnings.warn("The ligand was an array (SDF?). Using the first frame. ")
Optimising conformer:  69%|██████████████▍      | 11/16 [00:47<00:15,  3.07s/it]Optimising conformer:  75%|███████████████▊     | 12/16 [00:49<00:11,  2.84s/it]Optimising conformer:  81%|█████████████████    | 13/16 [01:16<00:30, 10.15s/it]Optimising conformer:  88%|██████████████████▍  | 14/16 [01:19<00:16,  8.15s/it]Optimising conformer:  94%|███████████████████▋ | 15/16 [01:22<00:06,  6.49s/it]Optimising conformer: 100%|█████████████████████| 16/16 [01:25<00:00,  5.49s/it]Optimising conformer: 100%|█████████████████████| 16/16 [01:25<00:00,  5.36s/it]
2024-01-29 01:19:39,441 - distributed.core - INFO - Event loop was unresponsive in Worker for 4.60s.  This is often caused by long-running GIL-holding functions or moving large chunks of data. This can cause timeouts and instability.
2024-01-29 01:19:39,441 [INFO] [core.py:595] distributed.core: Event loop was unresponsive in Worker for 4.60s.  This is often caused by long-running GIL-holding functions or moving large chunks of data. This can cause timeouts and instability.
/mnt/storage/nobackup/nmb1063/mamba/envs/fegrow/lib/python3.9/site-packages/parmed/structure.py:1775: UnitStrippedWarning: The unit of the quantity is stripped when downcasting to ndarray.
  coords = np.array(value, dtype=np.float64, copy=False, subok=True)
/mnt/storage/nobackup/nmb1063/mamba/envs/fegrow/lib/python3.9/site-packages/parmed/structure.py:1775: UnitStrippedWarning: The unit of the quantity is stripped when downcasting to ndarray.
  coords = np.array(value, dtype=np.float64, copy=False, subok=True)
TIME Completed the molecule generation in 173.1s.
TIME Completed the molecule generation in 126.1s.
TIME changed dir: 0.0s
TIME changed dir: 0.0s
Generated 38 conformers. 
Removed 29 conformers. 
Generated 41 conformers. 
Removed 31 conformers. 
using ani2x
/mnt/storage/nobackup/nmb1063/mamba/envs/fegrow/lib/python3.9/site-packages/torchani/resources/
failed to equip `nnpops` with error: No module named 'NNPOps'
Optimising conformer:   0%|                               | 0/9 [00:00<?, ?it/s]Optimising conformer:  11%|██▌                    | 1/9 [00:06<00:53,  6.70s/it]Optimising conformer:  22%|█████                  | 2/9 [00:10<00:33,  4.73s/it]Optimising conformer:  33%|███████▋               | 3/9 [00:13<00:24,  4.02s/it]Optimising conformer:  44%|██████████▏            | 4/9 [00:15<00:17,  3.48s/it]Optimising conformer:  56%|████████████▊          | 5/9 [00:18<00:12,  3.19s/it]Optimising conformer:  67%|███████████████▎       | 6/9 [00:22<00:09,  3.32s/it]Optimising conformer:  78%|█████████████████▉     | 7/9 [00:24<00:06,  3.03s/it]Optimising conformer:  89%|████████████████████▍  | 8/9 [00:27<00:02,  2.92s/it]using ani2x
/mnt/storage/nobackup/nmb1063/mamba/envs/fegrow/lib/python3.9/site-packages/torchani/resources/
failed to equip `nnpops` with error: No module named 'NNPOps'

Optimising conformer:   0%|                              | 0/10 [00:00<?, ?it/s][AOptimising conformer: 100%|███████████████████████| 9/9 [00:30<00:00,  3.12s/it]Optimising conformer: 100%|███████████████████████| 9/9 [00:30<00:00,  3.42s/it]
/mnt/storage/nobackup/nmb1063/code/gal/sars-cov-2-main-protease-al-study-plip/rsearcher.py:89: UserWarning: The ligand was an array (SDF?). Using the first frame. 
  warnings.warn("The ligand was an array (SDF?). Using the first frame. ")

Optimising conformer:  10%|██▏                   | 1/10 [00:05<00:47,  5.25s/it][A
Optimising conformer:  20%|████▍                 | 2/10 [00:19<01:22, 10.35s/it][A
Optimising conformer:  30%|██████▌               | 3/10 [01:04<03:05, 26.44s/it][A
Optimising conformer:  40%|████████▊             | 4/10 [01:07<01:43, 17.25s/it][A
Optimising conformer:  50%|███████████           | 5/10 [01:16<01:10, 14.00s/it][A
Optimising conformer:  60%|█████████████▏        | 6/10 [01:31<00:57, 14.46s/it][A
Optimising conformer:  70%|███████████████▍      | 7/10 [01:37<00:34, 11.63s/it][A
Optimising conformer:  80%|█████████████████▌    | 8/10 [01:41<00:18,  9.23s/it][A
Optimising conformer:  90%|███████████████████▊  | 9/10 [01:43<00:07,  7.05s/it][A
Optimising conformer: 100%|█████████████████████| 10/10 [01:46<00:00,  5.68s/it][AOptimising conformer: 100%|█████████████████████| 10/10 [01:46<00:00, 10.63s/it]
2024-01-29 01:53:29,644 - distributed.core - INFO - Event loop was unresponsive in Worker for 4.30s.  This is often caused by long-running GIL-holding functions or moving large chunks of data. This can cause timeouts and instability.
2024-01-29 01:53:29,644 [INFO] [core.py:595] distributed.core: Event loop was unresponsive in Worker for 4.30s.  This is often caused by long-running GIL-holding functions or moving large chunks of data. This can cause timeouts and instability.
2024-01-29 01:53:49,868 - distributed.core - INFO - Event loop was unresponsive in Worker for 5.03s.  This is often caused by long-running GIL-holding functions or moving large chunks of data. This can cause timeouts and instability.
2024-01-29 01:53:49,868 [INFO] [core.py:595] distributed.core: Event loop was unresponsive in Worker for 5.03s.  This is often caused by long-running GIL-holding functions or moving large chunks of data. This can cause timeouts and instability.
2024-01-29 02:10:27,520 [WARNING] [rdkit_wrapper.py:3213] openff.toolkit.utils.rdkit_wrapper: Warning (not error because allow_undefined_stereo=True): RDMol has unspecified stereochemistry. Bonds with undefined stereochemistry are:
 - Bond 1 (atoms 1-2 of element (C-C)

/mnt/storage/nobackup/nmb1063/mamba/envs/fegrow/lib/python3.9/site-packages/parmed/structure.py:1775: UnitStrippedWarning: The unit of the quantity is stripped when downcasting to ndarray.
  coords = np.array(value, dtype=np.float64, copy=False, subok=True)
2024-01-29 02:10:31,207 [WARNING] [rdkit_wrapper.py:3213] openff.toolkit.utils.rdkit_wrapper: Warning (not error because allow_undefined_stereo=True): RDMol has unspecified stereochemistry. Bonds with undefined stereochemistry are:
 - Bond 1 (atoms 1-2 of element (C-C)

/mnt/storage/nobackup/nmb1063/mamba/envs/fegrow/lib/python3.9/site-packages/parmed/structure.py:1775: UnitStrippedWarning: The unit of the quantity is stripped when downcasting to ndarray.
  coords = np.array(value, dtype=np.float64, copy=False, subok=True)
TIME Completed the molecule generation in 119.9s.
TIME Completed the molecule generation in 222.3s.
TIME changed dir: 0.0s
TIME changed dir: 0.0s
Generated 33 conformers. 
Removed 28 conformers. 
Generated 40 conformers. 
Removed 36 conformers. 
using ani2x
/mnt/storage/nobackup/nmb1063/mamba/envs/fegrow/lib/python3.9/site-packages/torchani/resources/
failed to equip `nnpops` with error: No module named 'NNPOps'
Optimising conformer:   0%|                               | 0/4 [00:00<?, ?it/s]Optimising conformer:  25%|█████▊                 | 1/4 [00:03<00:11,  3.91s/it]Optimising conformer:  50%|███████████▌           | 2/4 [00:11<00:12,  6.03s/it]Optimising conformer:  75%|█████████████████▎     | 3/4 [00:13<00:04,  4.45s/it]Optimising conformer: 100%|███████████████████████| 4/4 [00:16<00:00,  3.80s/it]Optimising conformer: 100%|███████████████████████| 4/4 [00:16<00:00,  4.20s/it]
/mnt/storage/nobackup/nmb1063/code/gal/sars-cov-2-main-protease-al-study-plip/rsearcher.py:89: UserWarning: The ligand was an array (SDF?). Using the first frame. 
  warnings.warn("The ligand was an array (SDF?). Using the first frame. ")
using ani2x
/mnt/storage/nobackup/nmb1063/mamba/envs/fegrow/lib/python3.9/site-packages/torchani/resources/
failed to equip `nnpops` with error: No module named 'NNPOps'
TIME Completed the molecule generation in 118.4s.
Optimising conformer:   0%|                               | 0/5 [00:00<?, ?it/s]Optimising conformer:  20%|████▌                  | 1/5 [00:02<00:10,  2.62s/it]Optimising conformer:  40%|█████████▏             | 2/5 [00:03<00:05,  1.88s/it]Optimising conformer:  60%|█████████████▊         | 3/5 [00:05<00:03,  1.85s/it]Optimising conformer:  80%|██████████████████▍    | 4/5 [00:07<00:01,  1.63s/it]Optimising conformer: 100%|███████████████████████| 5/5 [00:08<00:00,  1.52s/it]Optimising conformer: 100%|███████████████████████| 5/5 [00:08<00:00,  1.68s/it]
2024-01-29 02:30:08,370 - distributed.worker - ERROR - Worker stream died during communication: tcp://10.3.89.123:41592
Traceback (most recent call last):
  File "/mnt/storage/nobackup/nmb1063/mamba/envs/fegrow/lib/python3.9/site-packages/tornado/iostream.py", line 861, in _read_to_buffer
    bytes_read = self.read_from_fd(buf)
  File "/mnt/storage/nobackup/nmb1063/mamba/envs/fegrow/lib/python3.9/site-packages/tornado/iostream.py", line 1116, in read_from_fd
    return self.socket.recv_into(buf, len(buf))
ConnectionResetError: [Errno 104] Connection reset by peer

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/mnt/storage/nobackup/nmb1063/mamba/envs/fegrow/lib/python3.9/site-packages/distributed/worker.py", line 2081, in gather_dep
    response = await get_data_from_worker(
  File "/mnt/storage/nobackup/nmb1063/mamba/envs/fegrow/lib/python3.9/site-packages/distributed/worker.py", line 2903, in get_data_from_worker
    response = await send_recv(
  File "/mnt/storage/nobackup/nmb1063/mamba/envs/fegrow/lib/python3.9/site-packages/distributed/core.py", line 986, in send_recv
    response = await comm.read(deserializers=deserializers)
  File "/mnt/storage/nobackup/nmb1063/mamba/envs/fegrow/lib/python3.9/site-packages/distributed/comm/tcp.py", line 241, in read
    convert_stream_closed_error(self, e)
  File "/mnt/storage/nobackup/nmb1063/mamba/envs/fegrow/lib/python3.9/site-packages/distributed/comm/tcp.py", line 142, in convert_stream_closed_error
    raise CommClosedError(f"in {obj}: {exc.__class__.__name__}: {exc}") from exc
distributed.comm.core.CommClosedError: in <TCP (closed) Ephemeral Worker->Worker for gather local=tcp://10.3.89.110:53578 remote=tcp://10.3.89.123:41592>: ConnectionResetError: [Errno 104] Connection reset by peer
2024-01-29 02:30:08,370 [ERROR] [worker.py:2115] distributed.worker: Worker stream died during communication: tcp://10.3.89.123:41592
Traceback (most recent call last):
  File "/mnt/storage/nobackup/nmb1063/mamba/envs/fegrow/lib/python3.9/site-packages/tornado/iostream.py", line 861, in _read_to_buffer
    bytes_read = self.read_from_fd(buf)
  File "/mnt/storage/nobackup/nmb1063/mamba/envs/fegrow/lib/python3.9/site-packages/tornado/iostream.py", line 1116, in read_from_fd
    return self.socket.recv_into(buf, len(buf))
ConnectionResetError: [Errno 104] Connection reset by peer

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/mnt/storage/nobackup/nmb1063/mamba/envs/fegrow/lib/python3.9/site-packages/distributed/worker.py", line 2081, in gather_dep
    response = await get_data_from_worker(
  File "/mnt/storage/nobackup/nmb1063/mamba/envs/fegrow/lib/python3.9/site-packages/distributed/worker.py", line 2903, in get_data_from_worker
    response = await send_recv(
  File "/mnt/storage/nobackup/nmb1063/mamba/envs/fegrow/lib/python3.9/site-packages/distributed/core.py", line 986, in send_recv
    response = await comm.read(deserializers=deserializers)
  File "/mnt/storage/nobackup/nmb1063/mamba/envs/fegrow/lib/python3.9/site-packages/distributed/comm/tcp.py", line 241, in read
    convert_stream_closed_error(self, e)
  File "/mnt/storage/nobackup/nmb1063/mamba/envs/fegrow/lib/python3.9/site-packages/distributed/comm/tcp.py", line 142, in convert_stream_closed_error
    raise CommClosedError(f"in {obj}: {exc.__class__.__name__}: {exc}") from exc
distributed.comm.core.CommClosedError: in <TCP (closed) Ephemeral Worker->Worker for gather local=tcp://10.3.89.110:53578 remote=tcp://10.3.89.123:41592>: ConnectionResetError: [Errno 104] Connection reset by peer
2024-01-29 02:30:38,358 - distributed.worker - ERROR - Worker stream died during communication: tcp://10.3.89.127:39426
Traceback (most recent call last):
  File "/mnt/storage/nobackup/nmb1063/mamba/envs/fegrow/lib/python3.9/site-packages/distributed/comm/tcp.py", line 498, in connect
    stream = await self.client.connect(
  File "/mnt/storage/nobackup/nmb1063/mamba/envs/fegrow/lib/python3.9/site-packages/tornado/tcpclient.py", line 279, in connect
    af, addr, stream = await connector.start(connect_timeout=timeout)
asyncio.exceptions.CancelledError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/mnt/storage/nobackup/nmb1063/mamba/envs/fegrow/lib/python3.9/asyncio/tasks.py", line 490, in wait_for
    return fut.result()
asyncio.exceptions.CancelledError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/mnt/storage/nobackup/nmb1063/mamba/envs/fegrow/lib/python3.9/site-packages/distributed/comm/core.py", line 291, in connect
    comm = await asyncio.wait_for(
  File "/mnt/storage/nobackup/nmb1063/mamba/envs/fegrow/lib/python3.9/asyncio/tasks.py", line 492, in wait_for
    raise exceptions.TimeoutError() from exc
asyncio.exceptions.TimeoutError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/mnt/storage/nobackup/nmb1063/mamba/envs/fegrow/lib/python3.9/site-packages/distributed/worker.py", line 2081, in gather_dep
    response = await get_data_from_worker(
  File "/mnt/storage/nobackup/nmb1063/mamba/envs/fegrow/lib/python3.9/site-packages/distributed/worker.py", line 2900, in get_data_from_worker
    comm = await rpc.connect(worker)
  File "/mnt/storage/nobackup/nmb1063/mamba/envs/fegrow/lib/python3.9/site-packages/distributed/core.py", line 1468, in connect
    return await connect_attempt
  File "/mnt/storage/nobackup/nmb1063/mamba/envs/fegrow/lib/python3.9/site-packages/distributed/core.py", line 1389, in _connect
    comm = await connect(
  File "/mnt/storage/nobackup/nmb1063/mamba/envs/fegrow/lib/python3.9/site-packages/distributed/comm/core.py", line 317, in connect
    raise OSError(
OSError: Timed out trying to connect to tcp://10.3.89.127:39426 after 30 s
2024-01-29 02:30:38,358 [ERROR] [worker.py:2115] distributed.worker: Worker stream died during communication: tcp://10.3.89.127:39426
Traceback (most recent call last):
  File "/mnt/storage/nobackup/nmb1063/mamba/envs/fegrow/lib/python3.9/site-packages/distributed/comm/tcp.py", line 498, in connect
    stream = await self.client.connect(
  File "/mnt/storage/nobackup/nmb1063/mamba/envs/fegrow/lib/python3.9/site-packages/tornado/tcpclient.py", line 279, in connect
    af, addr, stream = await connector.start(connect_timeout=timeout)
asyncio.exceptions.CancelledError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/mnt/storage/nobackup/nmb1063/mamba/envs/fegrow/lib/python3.9/asyncio/tasks.py", line 490, in wait_for
    return fut.result()
asyncio.exceptions.CancelledError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/mnt/storage/nobackup/nmb1063/mamba/envs/fegrow/lib/python3.9/site-packages/distributed/comm/core.py", line 291, in connect
    comm = await asyncio.wait_for(
  File "/mnt/storage/nobackup/nmb1063/mamba/envs/fegrow/lib/python3.9/asyncio/tasks.py", line 492, in wait_for
    raise exceptions.TimeoutError() from exc
asyncio.exceptions.TimeoutError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/mnt/storage/nobackup/nmb1063/mamba/envs/fegrow/lib/python3.9/site-packages/distributed/worker.py", line 2081, in gather_dep
    response = await get_data_from_worker(
  File "/mnt/storage/nobackup/nmb1063/mamba/envs/fegrow/lib/python3.9/site-packages/distributed/worker.py", line 2900, in get_data_from_worker
    comm = await rpc.connect(worker)
  File "/mnt/storage/nobackup/nmb1063/mamba/envs/fegrow/lib/python3.9/site-packages/distributed/core.py", line 1468, in connect
    return await connect_attempt
  File "/mnt/storage/nobackup/nmb1063/mamba/envs/fegrow/lib/python3.9/site-packages/distributed/core.py", line 1389, in _connect
    comm = await connect(
  File "/mnt/storage/nobackup/nmb1063/mamba/envs/fegrow/lib/python3.9/site-packages/distributed/comm/core.py", line 317, in connect
    raise OSError(
OSError: Timed out trying to connect to tcp://10.3.89.127:39426 after 30 s
2024-01-29 02:30:38,732 - distributed.worker - ERROR - Worker stream died during communication: tcp://10.3.89.182:33543
ConnectionRefusedError: [Errno 111] Connection refused

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/mnt/storage/nobackup/nmb1063/mamba/envs/fegrow/lib/python3.9/site-packages/distributed/comm/core.py", line 291, in connect
    comm = await asyncio.wait_for(
  File "/mnt/storage/nobackup/nmb1063/mamba/envs/fegrow/lib/python3.9/asyncio/tasks.py", line 479, in wait_for
    return fut.result()
  File "/mnt/storage/nobackup/nmb1063/mamba/envs/fegrow/lib/python3.9/site-packages/distributed/comm/tcp.py", line 511, in connect
    convert_stream_closed_error(self, e)
  File "/mnt/storage/nobackup/nmb1063/mamba/envs/fegrow/lib/python3.9/site-packages/distributed/comm/tcp.py", line 142, in convert_stream_closed_error
    raise CommClosedError(f"in {obj}: {exc.__class__.__name__}: {exc}") from exc
distributed.comm.core.CommClosedError: in <distributed.comm.tcp.TCPConnector object at 0x2b308cc3ac10>: ConnectionRefusedError: [Errno 111] Connection refused

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/mnt/storage/nobackup/nmb1063/mamba/envs/fegrow/lib/python3.9/site-packages/distributed/worker.py", line 2081, in gather_dep
    response = await get_data_from_worker(
  File "/mnt/storage/nobackup/nmb1063/mamba/envs/fegrow/lib/python3.9/site-packages/distributed/worker.py", line 2900, in get_data_from_worker
    comm = await rpc.connect(worker)
  File "/mnt/storage/nobackup/nmb1063/mamba/envs/fegrow/lib/python3.9/site-packages/distributed/core.py", line 1468, in connect
    return await connect_attempt
  File "/mnt/storage/nobackup/nmb1063/mamba/envs/fegrow/lib/python3.9/site-packages/distributed/core.py", line 1389, in _connect
    comm = await connect(
  File "/mnt/storage/nobackup/nmb1063/mamba/envs/fegrow/lib/python3.9/site-packages/distributed/comm/core.py", line 317, in connect
    raise OSError(
OSError: Timed out trying to connect to tcp://10.3.89.182:33543 after 30 s
2024-01-29 02:30:38,732 [ERROR] [worker.py:2115] distributed.worker: Worker stream died during communication: tcp://10.3.89.182:33543
ConnectionRefusedError: [Errno 111] Connection refused

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/mnt/storage/nobackup/nmb1063/mamba/envs/fegrow/lib/python3.9/site-packages/distributed/comm/core.py", line 291, in connect
    comm = await asyncio.wait_for(
  File "/mnt/storage/nobackup/nmb1063/mamba/envs/fegrow/lib/python3.9/asyncio/tasks.py", line 479, in wait_for
    return fut.result()
  File "/mnt/storage/nobackup/nmb1063/mamba/envs/fegrow/lib/python3.9/site-packages/distributed/comm/tcp.py", line 511, in connect
    convert_stream_closed_error(self, e)
  File "/mnt/storage/nobackup/nmb1063/mamba/envs/fegrow/lib/python3.9/site-packages/distributed/comm/tcp.py", line 142, in convert_stream_closed_error
    raise CommClosedError(f"in {obj}: {exc.__class__.__name__}: {exc}") from exc
distributed.comm.core.CommClosedError: in <distributed.comm.tcp.TCPConnector object at 0x2b308cc3ac10>: ConnectionRefusedError: [Errno 111] Connection refused

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/mnt/storage/nobackup/nmb1063/mamba/envs/fegrow/lib/python3.9/site-packages/distributed/worker.py", line 2081, in gather_dep
    response = await get_data_from_worker(
  File "/mnt/storage/nobackup/nmb1063/mamba/envs/fegrow/lib/python3.9/site-packages/distributed/worker.py", line 2900, in get_data_from_worker
    comm = await rpc.connect(worker)
  File "/mnt/storage/nobackup/nmb1063/mamba/envs/fegrow/lib/python3.9/site-packages/distributed/core.py", line 1468, in connect
    return await connect_attempt
  File "/mnt/storage/nobackup/nmb1063/mamba/envs/fegrow/lib/python3.9/site-packages/distributed/core.py", line 1389, in _connect
    comm = await connect(
  File "/mnt/storage/nobackup/nmb1063/mamba/envs/fegrow/lib/python3.9/site-packages/distributed/comm/core.py", line 317, in connect
    raise OSError(
OSError: Timed out trying to connect to tcp://10.3.89.182:33543 after 30 s
2024-01-29 02:31:28,090 - distributed.core - INFO - Event loop was unresponsive in Worker for 3.74s.  This is often caused by long-running GIL-holding functions or moving large chunks of data. This can cause timeouts and instability.
2024-01-29 02:31:28,090 [INFO] [core.py:595] distributed.core: Event loop was unresponsive in Worker for 3.74s.  This is often caused by long-running GIL-holding functions or moving large chunks of data. This can cause timeouts and instability.
2024-01-29 02:52:40,169 - distributed.worker - ERROR - Worker stream died during communication: tcp://10.3.89.129:46774
Traceback (most recent call last):
  File "/mnt/storage/nobackup/nmb1063/mamba/envs/fegrow/lib/python3.9/site-packages/distributed/comm/tcp.py", line 225, in read
    frames_nbytes = await stream.read_bytes(fmt_size)
asyncio.exceptions.CancelledError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/mnt/storage/nobackup/nmb1063/mamba/envs/fegrow/lib/python3.9/asyncio/tasks.py", line 490, in wait_for
    return fut.result()
asyncio.exceptions.CancelledError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/mnt/storage/nobackup/nmb1063/mamba/envs/fegrow/lib/python3.9/site-packages/distributed/comm/core.py", line 328, in connect
    handshake = await asyncio.wait_for(comm.read(), time_left())
  File "/mnt/storage/nobackup/nmb1063/mamba/envs/fegrow/lib/python3.9/asyncio/tasks.py", line 492, in wait_for
    raise exceptions.TimeoutError() from exc
asyncio.exceptions.TimeoutError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/mnt/storage/nobackup/nmb1063/mamba/envs/fegrow/lib/python3.9/site-packages/distributed/worker.py", line 2081, in gather_dep
    response = await get_data_from_worker(
  File "/mnt/storage/nobackup/nmb1063/mamba/envs/fegrow/lib/python3.9/site-packages/distributed/worker.py", line 2900, in get_data_from_worker
    comm = await rpc.connect(worker)
  File "/mnt/storage/nobackup/nmb1063/mamba/envs/fegrow/lib/python3.9/site-packages/distributed/core.py", line 1468, in connect
    return await connect_attempt
  File "/mnt/storage/nobackup/nmb1063/mamba/envs/fegrow/lib/python3.9/site-packages/distributed/core.py", line 1389, in _connect
    comm = await connect(
  File "/mnt/storage/nobackup/nmb1063/mamba/envs/fegrow/lib/python3.9/site-packages/distributed/comm/core.py", line 333, in connect
    raise OSError(
OSError: Timed out during handshake while connecting to tcp://10.3.89.129:46774 after 30 s
2024-01-29 02:52:40,169 [ERROR] [worker.py:2115] distributed.worker: Worker stream died during communication: tcp://10.3.89.129:46774
Traceback (most recent call last):
  File "/mnt/storage/nobackup/nmb1063/mamba/envs/fegrow/lib/python3.9/site-packages/distributed/comm/tcp.py", line 225, in read
    frames_nbytes = await stream.read_bytes(fmt_size)
asyncio.exceptions.CancelledError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/mnt/storage/nobackup/nmb1063/mamba/envs/fegrow/lib/python3.9/asyncio/tasks.py", line 490, in wait_for
    return fut.result()
asyncio.exceptions.CancelledError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/mnt/storage/nobackup/nmb1063/mamba/envs/fegrow/lib/python3.9/site-packages/distributed/comm/core.py", line 328, in connect
    handshake = await asyncio.wait_for(comm.read(), time_left())
  File "/mnt/storage/nobackup/nmb1063/mamba/envs/fegrow/lib/python3.9/asyncio/tasks.py", line 492, in wait_for
    raise exceptions.TimeoutError() from exc
asyncio.exceptions.TimeoutError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/mnt/storage/nobackup/nmb1063/mamba/envs/fegrow/lib/python3.9/site-packages/distributed/worker.py", line 2081, in gather_dep
    response = await get_data_from_worker(
  File "/mnt/storage/nobackup/nmb1063/mamba/envs/fegrow/lib/python3.9/site-packages/distributed/worker.py", line 2900, in get_data_from_worker
    comm = await rpc.connect(worker)
  File "/mnt/storage/nobackup/nmb1063/mamba/envs/fegrow/lib/python3.9/site-packages/distributed/core.py", line 1468, in connect
    return await connect_attempt
  File "/mnt/storage/nobackup/nmb1063/mamba/envs/fegrow/lib/python3.9/site-packages/distributed/core.py", line 1389, in _connect
    comm = await connect(
  File "/mnt/storage/nobackup/nmb1063/mamba/envs/fegrow/lib/python3.9/site-packages/distributed/comm/core.py", line 333, in connect
    raise OSError(
OSError: Timed out during handshake while connecting to tcp://10.3.89.129:46774 after 30 s
2024-01-29 02:53:10,363 - distributed.worker - ERROR - Worker stream died during communication: tcp://10.3.89.129:46774
Traceback (most recent call last):
  File "/mnt/storage/nobackup/nmb1063/mamba/envs/fegrow/lib/python3.9/site-packages/distributed/comm/tcp.py", line 225, in read
    frames_nbytes = await stream.read_bytes(fmt_size)
asyncio.exceptions.CancelledError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/mnt/storage/nobackup/nmb1063/mamba/envs/fegrow/lib/python3.9/asyncio/tasks.py", line 490, in wait_for
    return fut.result()
asyncio.exceptions.CancelledError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/mnt/storage/nobackup/nmb1063/mamba/envs/fegrow/lib/python3.9/site-packages/distributed/comm/core.py", line 328, in connect
    handshake = await asyncio.wait_for(comm.read(), time_left())
  File "/mnt/storage/nobackup/nmb1063/mamba/envs/fegrow/lib/python3.9/asyncio/tasks.py", line 492, in wait_for
    raise exceptions.TimeoutError() from exc
asyncio.exceptions.TimeoutError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/mnt/storage/nobackup/nmb1063/mamba/envs/fegrow/lib/python3.9/site-packages/distributed/worker.py", line 2081, in gather_dep
    response = await get_data_from_worker(
  File "/mnt/storage/nobackup/nmb1063/mamba/envs/fegrow/lib/python3.9/site-packages/distributed/worker.py", line 2900, in get_data_from_worker
    comm = await rpc.connect(worker)
  File "/mnt/storage/nobackup/nmb1063/mamba/envs/fegrow/lib/python3.9/site-packages/distributed/core.py", line 1468, in connect
    return await connect_attempt
  File "/mnt/storage/nobackup/nmb1063/mamba/envs/fegrow/lib/python3.9/site-packages/distributed/core.py", line 1389, in _connect
    comm = await connect(
  File "/mnt/storage/nobackup/nmb1063/mamba/envs/fegrow/lib/python3.9/site-packages/distributed/comm/core.py", line 333, in connect
    raise OSError(
OSError: Timed out during handshake while connecting to tcp://10.3.89.129:46774 after 30 s
2024-01-29 02:53:10,363 [ERROR] [worker.py:2115] distributed.worker: Worker stream died during communication: tcp://10.3.89.129:46774
Traceback (most recent call last):
  File "/mnt/storage/nobackup/nmb1063/mamba/envs/fegrow/lib/python3.9/site-packages/distributed/comm/tcp.py", line 225, in read
    frames_nbytes = await stream.read_bytes(fmt_size)
asyncio.exceptions.CancelledError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/mnt/storage/nobackup/nmb1063/mamba/envs/fegrow/lib/python3.9/asyncio/tasks.py", line 490, in wait_for
    return fut.result()
asyncio.exceptions.CancelledError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/mnt/storage/nobackup/nmb1063/mamba/envs/fegrow/lib/python3.9/site-packages/distributed/comm/core.py", line 328, in connect
    handshake = await asyncio.wait_for(comm.read(), time_left())
  File "/mnt/storage/nobackup/nmb1063/mamba/envs/fegrow/lib/python3.9/asyncio/tasks.py", line 492, in wait_for
    raise exceptions.TimeoutError() from exc
asyncio.exceptions.TimeoutError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/mnt/storage/nobackup/nmb1063/mamba/envs/fegrow/lib/python3.9/site-packages/distributed/worker.py", line 2081, in gather_dep
    response = await get_data_from_worker(
  File "/mnt/storage/nobackup/nmb1063/mamba/envs/fegrow/lib/python3.9/site-packages/distributed/worker.py", line 2900, in get_data_from_worker
    comm = await rpc.connect(worker)
  File "/mnt/storage/nobackup/nmb1063/mamba/envs/fegrow/lib/python3.9/site-packages/distributed/core.py", line 1468, in connect
    return await connect_attempt
  File "/mnt/storage/nobackup/nmb1063/mamba/envs/fegrow/lib/python3.9/site-packages/distributed/core.py", line 1389, in _connect
    comm = await connect(
  File "/mnt/storage/nobackup/nmb1063/mamba/envs/fegrow/lib/python3.9/site-packages/distributed/comm/core.py", line 333, in connect
    raise OSError(
OSError: Timed out during handshake while connecting to tcp://10.3.89.129:46774 after 30 s
/mnt/storage/nobackup/nmb1063/mamba/envs/fegrow/lib/python3.9/site-packages/parmed/structure.py:1775: UnitStrippedWarning: The unit of the quantity is stripped when downcasting to ndarray.
  coords = np.array(value, dtype=np.float64, copy=False, subok=True)
/mnt/storage/nobackup/nmb1063/mamba/envs/fegrow/lib/python3.9/site-packages/parmed/structure.py:1775: UnitStrippedWarning: The unit of the quantity is stripped when downcasting to ndarray.
  coords = np.array(value, dtype=np.float64, copy=False, subok=True)
TIME Completed the molecule generation in 130.2s.
TIME changed dir: 0.0s
TIME changed dir: 0.0s
Generated 23 conformers. 
Removed 19 conformers. 
Generated 29 conformers. 
Removed 24 conformers. 
using ani2x
/mnt/storage/nobackup/nmb1063/mamba/envs/fegrow/lib/python3.9/site-packages/torchani/resources/
failed to equip `nnpops` with error: No module named 'NNPOps'
Optimising conformer:   0%|                               | 0/5 [00:00<?, ?it/s]Optimising conformer:  20%|████▌                  | 1/5 [00:04<00:17,  4.30s/it]Optimising conformer:  40%|█████████▏             | 2/5 [00:08<00:13,  4.34s/it]Optimising conformer:  60%|█████████████▊         | 3/5 [00:15<00:10,  5.30s/it]Optimising conformer:  80%|██████████████████▍    | 4/5 [00:16<00:03,  3.90s/it]Optimising conformer: 100%|███████████████████████| 5/5 [00:19<00:00,  3.40s/it]Optimising conformer: 100%|███████████████████████| 5/5 [00:19<00:00,  3.88s/it]
/mnt/storage/nobackup/nmb1063/code/gal/sars-cov-2-main-protease-al-study-plip/rsearcher.py:89: UserWarning: The ligand was an array (SDF?). Using the first frame. 
  warnings.warn("The ligand was an array (SDF?). Using the first frame. ")
using ani2x
/mnt/storage/nobackup/nmb1063/mamba/envs/fegrow/lib/python3.9/site-packages/torchani/resources/
TIME Completed the molecule generation in 84.1s.
failed to equip `nnpops` with error: No module named 'NNPOps'
Optimising conformer:   0%|                               | 0/4 [00:00<?, ?it/s]Optimising conformer:  25%|█████▊                 | 1/4 [00:04<00:12,  4.11s/it]Optimising conformer:  50%|███████████▌           | 2/4 [00:06<00:05,  2.85s/it]Optimising conformer:  75%|█████████████████▎     | 3/4 [00:11<00:04,  4.02s/it]Optimising conformer: 100%|███████████████████████| 4/4 [00:38<00:00, 13.29s/it]Optimising conformer: 100%|███████████████████████| 4/4 [00:38<00:00,  9.75s/it]
2024-01-29 03:12:31,768 - distributed.core - INFO - Event loop was unresponsive in Worker for 3.42s.  This is often caused by long-running GIL-holding functions or moving large chunks of data. This can cause timeouts and instability.
2024-01-29 03:12:31,768 [INFO] [core.py:595] distributed.core: Event loop was unresponsive in Worker for 3.42s.  This is often caused by long-running GIL-holding functions or moving large chunks of data. This can cause timeouts and instability.
2024-01-29 03:12:55,037 - distributed.core - INFO - Event loop was unresponsive in Worker for 3.53s.  This is often caused by long-running GIL-holding functions or moving large chunks of data. This can cause timeouts and instability.
2024-01-29 03:12:55,037 [INFO] [core.py:595] distributed.core: Event loop was unresponsive in Worker for 3.53s.  This is often caused by long-running GIL-holding functions or moving large chunks of data. This can cause timeouts and instability.
2024-01-29 03:33:36,758 [WARNING] [rdkit_wrapper.py:3213] openff.toolkit.utils.rdkit_wrapper: Warning (not error because allow_undefined_stereo=True): RDMol has unspecified stereochemistry. Bonds with undefined stereochemistry are:
 - Bond 1 (atoms 1-2 of element (C-C)

/mnt/storage/nobackup/nmb1063/mamba/envs/fegrow/lib/python3.9/site-packages/parmed/structure.py:1775: UnitStrippedWarning: The unit of the quantity is stripped when downcasting to ndarray.
  coords = np.array(value, dtype=np.float64, copy=False, subok=True)
2024-01-29 03:33:40,187 [WARNING] [rdkit_wrapper.py:3213] openff.toolkit.utils.rdkit_wrapper: Warning (not error because allow_undefined_stereo=True): RDMol has unspecified stereochemistry. Bonds with undefined stereochemistry are:
 - Bond 1 (atoms 1-2 of element (C-C)

2024-01-29 03:33:40,691 [WARNING] [rdkit_wrapper.py:3213] openff.toolkit.utils.rdkit_wrapper: Warning (not error because allow_undefined_stereo=True): RDMol has unspecified stereochemistry. Undefined chiral centers are:
 - Atom C (index 8)

/mnt/storage/nobackup/nmb1063/mamba/envs/fegrow/lib/python3.9/site-packages/parmed/structure.py:1775: UnitStrippedWarning: The unit of the quantity is stripped when downcasting to ndarray.
  coords = np.array(value, dtype=np.float64, copy=False, subok=True)
2024-01-29 03:33:43,537 [WARNING] [rdkit_wrapper.py:3213] openff.toolkit.utils.rdkit_wrapper: Warning (not error because allow_undefined_stereo=True): RDMol has unspecified stereochemistry. Undefined chiral centers are:
 - Atom C (index 8)

TIME Completed the molecule generation in 131.7s.
TIME changed dir: 0.0s
TIME changed dir: 0.0s
Generated 19 conformers. 
Removed 12 conformers. 
Generated 49 conformers. 
Removed 38 conformers. 
using ani2x
/mnt/storage/nobackup/nmb1063/mamba/envs/fegrow/lib/python3.9/site-packages/torchani/resources/
failed to equip `nnpops` with error: No module named 'NNPOps'
Optimising conformer:   0%|                              | 0/11 [00:00<?, ?it/s]Optimising conformer:   9%|██                    | 1/11 [00:03<00:34,  3.46s/it]Optimising conformer:  18%|████                  | 2/11 [00:10<00:51,  5.71s/it]using ani2x
/mnt/storage/nobackup/nmb1063/mamba/envs/fegrow/lib/python3.9/site-packages/torchani/resources/
failed to equip `nnpops` with error: No module named 'NNPOps'

Optimising conformer:   0%|                               | 0/7 [00:00<?, ?it/s][AOptimising conformer:  27%|██████                | 3/11 [00:37<02:03, 15.40s/it]
Optimising conformer:  14%|███▎                   | 1/7 [00:04<00:26,  4.46s/it][A
Optimising conformer:  29%|██████▌                | 2/7 [00:07<00:17,  3.59s/it][AOptimising conformer:  36%|████████              | 4/11 [00:43<01:20, 11.48s/it]
Optimising conformer:  43%|█████████▊             | 3/7 [00:12<00:17,  4.46s/it][AOptimising conformer:  45%|██████████            | 5/11 [00:48<00:56,  9.44s/it]
Optimising conformer:  57%|█████████████▏         | 4/7 [00:19<00:16,  5.37s/it][AOptimising conformer:  55%|████████████          | 6/11 [00:56<00:44,  8.80s/it]
Optimising conformer:  71%|████████████████▍      | 5/7 [00:23<00:09,  4.73s/it][A
Optimising conformer:  86%|███████████████████▋   | 6/7 [00:25<00:03,  3.78s/it][A
Optimising conformer: 100%|███████████████████████| 7/7 [00:27<00:00,  3.31s/it][AOptimising conformer: 100%|███████████████████████| 7/7 [00:27<00:00,  3.94s/it]
/mnt/storage/nobackup/nmb1063/code/gal/sars-cov-2-main-protease-al-study-plip/rsearcher.py:89: UserWarning: The ligand was an array (SDF?). Using the first frame. 
  warnings.warn("The ligand was an array (SDF?). Using the first frame. ")
Optimising conformer:  64%|██████████████        | 7/11 [01:03<00:33,  8.31s/it]Optimising conformer:  73%|████████████████      | 8/11 [01:08<00:21,  7.26s/it]Optimising conformer:  82%|██████████████████    | 9/11 [01:12<00:12,  6.22s/it]Optimising conformer:  91%|███████████████████  | 10/11 [01:16<00:05,  5.59s/it]Optimising conformer: 100%|█████████████████████| 11/11 [01:22<00:00,  5.52s/it]Optimising conformer: 100%|█████████████████████| 11/11 [01:22<00:00,  7.48s/it]
2024-01-29 04:00:36,023 - distributed.core - INFO - Event loop was unresponsive in Worker for 4.19s.  This is often caused by long-running GIL-holding functions or moving large chunks of data. This can cause timeouts and instability.
2024-01-29 04:00:36,023 [INFO] [core.py:595] distributed.core: Event loop was unresponsive in Worker for 4.19s.  This is often caused by long-running GIL-holding functions or moving large chunks of data. This can cause timeouts and instability.
/mnt/storage/nobackup/nmb1063/mamba/envs/fegrow/lib/python3.9/site-packages/parmed/structure.py:1775: UnitStrippedWarning: The unit of the quantity is stripped when downcasting to ndarray.
  coords = np.array(value, dtype=np.float64, copy=False, subok=True)
/mnt/storage/nobackup/nmb1063/mamba/envs/fegrow/lib/python3.9/site-packages/parmed/structure.py:1775: UnitStrippedWarning: The unit of the quantity is stripped when downcasting to ndarray.
  coords = np.array(value, dtype=np.float64, copy=False, subok=True)
TIME Completed the molecule generation in 141.7s.
TIME Completed the molecule generation in 161.7s.
TIME changed dir: 0.0s
TIME changed dir: 0.0s
Generated 13 conformers. 
Removed 4 conformers. 
Generated 25 conformers. 
Removed 19 conformers. 
using ani2x
/mnt/storage/nobackup/nmb1063/mamba/envs/fegrow/lib/python3.9/site-packages/torchani/resources/
failed to equip `nnpops` with error: No module named 'NNPOps'
Optimising conformer:   0%|                               | 0/9 [00:00<?, ?it/s]Optimising conformer:  11%|██▌                    | 1/9 [00:02<00:22,  2.86s/it]Optimising conformer:  22%|█████                  | 2/9 [00:06<00:21,  3.13s/it]Optimising conformer:  33%|███████▋               | 3/9 [00:08<00:15,  2.60s/it]Optimising conformer:  44%|██████████▏            | 4/9 [00:09<00:11,  2.20s/it]Optimising conformer:  56%|████████████▊          | 5/9 [00:13<00:11,  2.92s/it]Optimising conformer:  67%|███████████████▎       | 6/9 [00:15<00:07,  2.55s/it]using ani2x
/mnt/storage/nobackup/nmb1063/mamba/envs/fegrow/lib/python3.9/site-packages/torchani/resources/
failed to equip `nnpops` with error: No module named 'NNPOps'
Optimising conformer:  78%|█████████████████▉     | 7/9 [00:17<00:04,  2.23s/it]
Optimising conformer:   0%|                               | 0/6 [00:00<?, ?it/s][AOptimising conformer:  89%|████████████████████▍  | 8/9 [00:18<00:01,  2.00s/it]Optimising conformer: 100%|███████████████████████| 9/9 [00:20<00:00,  1.85s/it]Optimising conformer: 100%|███████████████████████| 9/9 [00:20<00:00,  2.26s/it]
/mnt/storage/nobackup/nmb1063/code/gal/sars-cov-2-main-protease-al-study-plip/rsearcher.py:89: UserWarning: The ligand was an array (SDF?). Using the first frame. 
  warnings.warn("The ligand was an array (SDF?). Using the first frame. ")

Optimising conformer:  17%|███▊                   | 1/6 [00:03<00:19,  3.92s/it][A
Optimising conformer:  33%|███████▋               | 2/6 [00:06<00:12,  3.01s/it][A
Optimising conformer:  50%|███████████▌           | 3/6 [00:08<00:08,  2.74s/it][A
Optimising conformer:  67%|███████████████▎       | 4/6 [00:11<00:05,  2.69s/it][A/mnt/storage/nobackup/nmb1063/mamba/envs/fegrow/lib/python3.9/site-packages/parmed/structure.py:1775: UnitStrippedWarning: The unit of the quantity is stripped when downcasting to ndarray.
  coords = np.array(value, dtype=np.float64, copy=False, subok=True)

Optimising conformer:  83%|███████████████████▏   | 5/6 [00:13<00:02,  2.61s/it][A
Optimising conformer: 100%|███████████████████████| 6/6 [00:15<00:00,  2.39s/it][AOptimising conformer: 100%|███████████████████████| 6/6 [00:15<00:00,  2.63s/it]
/mnt/storage/nobackup/nmb1063/code/gal/sars-cov-2-main-protease-al-study-plip/rsearcher.py:89: UserWarning: The ligand was an array (SDF?). Using the first frame. 
  warnings.warn("The ligand was an array (SDF?). Using the first frame. ")
2024-01-29 04:23:08,847 [WARNING] [rdkit_wrapper.py:3213] openff.toolkit.utils.rdkit_wrapper: Warning (not error because allow_undefined_stereo=True): RDMol has unspecified stereochemistry. Undefined chiral centers are:
 - Atom N (index 1)

/mnt/storage/nobackup/nmb1063/mamba/envs/fegrow/lib/python3.9/site-packages/parmed/structure.py:1775: UnitStrippedWarning: The unit of the quantity is stripped when downcasting to ndarray.
  coords = np.array(value, dtype=np.float64, copy=False, subok=True)
2024-01-29 04:23:10,544 [WARNING] [rdkit_wrapper.py:3213] openff.toolkit.utils.rdkit_wrapper: Warning (not error because allow_undefined_stereo=True): RDMol has unspecified stereochemistry. Undefined chiral centers are:
 - Atom N (index 1)

TIME Completed the molecule generation in 53.0s.
TIME changed dir: 0.0s
Generated 30 conformers. 
Removed 17 conformers. 
TIME Completed the molecule generation in 65.7s.
TIME changed dir: 0.0s
Generated 39 conformers. 
Removed 31 conformers. 
using ani2x
/mnt/storage/nobackup/nmb1063/mamba/envs/fegrow/lib/python3.9/site-packages/torchani/resources/
failed to equip `nnpops` with error: No module named 'NNPOps'
Optimising conformer:   0%|                              | 0/13 [00:00<?, ?it/s]Optimising conformer:   8%|█▋                    | 1/13 [00:03<00:45,  3.79s/it]Optimising conformer:  15%|███▍                  | 2/13 [00:06<00:37,  3.39s/it]Optimising conformer:  23%|█████                 | 3/13 [00:09<00:29,  2.91s/it]Optimising conformer:  31%|██████▊               | 4/13 [00:20<00:57,  6.36s/it]Optimising conformer:  38%|████████▍             | 5/13 [00:23<00:39,  4.97s/it]using ani2x
/mnt/storage/nobackup/nmb1063/mamba/envs/fegrow/lib/python3.9/site-packages/torchani/resources/
failed to equip `nnpops` with error: No module named 'NNPOps'

Optimising conformer:   0%|                               | 0/8 [00:00<?, ?it/s][AOptimising conformer:  46%|██████████▏           | 6/13 [00:26<00:30,  4.32s/it]
Optimising conformer:  12%|██▉                    | 1/8 [00:03<00:26,  3.81s/it][AOptimising conformer:  54%|███████████▊          | 7/13 [00:29<00:23,  3.88s/it]
Optimising conformer:  25%|█████▊                 | 2/8 [00:05<00:16,  2.83s/it][A
Optimising conformer:  38%|████████▋              | 3/8 [00:08<00:12,  2.57s/it][AOptimising conformer:  62%|█████████████▌        | 8/13 [00:32<00:18,  3.70s/it]
Optimising conformer:  50%|███████████▌           | 4/8 [00:10<00:09,  2.48s/it][AOptimising conformer:  69%|███████████████▏      | 9/13 [00:34<00:12,  3.22s/it]
Optimising conformer:  62%|██████████████▍        | 5/8 [00:12<00:06,  2.12s/it][AOptimising conformer:  77%|████████████████▏    | 10/13 [00:37<00:08,  2.89s/it]
Optimising conformer:  75%|█████████████████▎     | 6/8 [00:15<00:04,  2.43s/it][AOptimising conformer:  85%|█████████████████▊   | 11/13 [00:41<00:06,  3.32s/it]Optimising conformer:  92%|███████████████████▍ | 12/13 [00:44<00:03,  3.30s/it]
Optimising conformer:  88%|████████████████████▏  | 7/8 [00:21<00:03,  3.71s/it][AOptimising conformer: 100%|█████████████████████| 13/13 [00:46<00:00,  2.97s/it]Optimising conformer: 100%|█████████████████████| 13/13 [00:46<00:00,  3.60s/it]
/mnt/storage/nobackup/nmb1063/code/gal/sars-cov-2-main-protease-al-study-plip/rsearcher.py:89: UserWarning: The ligand was an array (SDF?). Using the first frame. 
  warnings.warn("The ligand was an array (SDF?). Using the first frame. ")

Optimising conformer: 100%|███████████████████████| 8/8 [00:24<00:00,  3.42s/it][AOptimising conformer: 100%|███████████████████████| 8/8 [00:24<00:00,  3.03s/it]
2024-01-29 04:44:53,538 - distributed.core - INFO - Event loop was unresponsive in Worker for 3.81s.  This is often caused by long-running GIL-holding functions or moving large chunks of data. This can cause timeouts and instability.
2024-01-29 04:44:53,538 [INFO] [core.py:595] distributed.core: Event loop was unresponsive in Worker for 3.81s.  This is often caused by long-running GIL-holding functions or moving large chunks of data. This can cause timeouts and instability.
/mnt/storage/nobackup/nmb1063/mamba/envs/fegrow/lib/python3.9/site-packages/parmed/structure.py:1775: UnitStrippedWarning: The unit of the quantity is stripped when downcasting to ndarray.
  coords = np.array(value, dtype=np.float64, copy=False, subok=True)
TIME Completed the molecule generation in 95.2s.
TIME Completed the molecule generation in 83.0s.
TIME changed dir: 0.0s
TIME changed dir: 0.0s
Generated 8 conformers. 
Generated 8 conformers. 
Removed 5 conformers. 
Removed 5 conformers. 
using ani2x
/mnt/storage/nobackup/nmb1063/mamba/envs/fegrow/lib/python3.9/site-packages/torchani/resources/
failed to equip `nnpops` with error: No module named 'NNPOps'
Optimising conformer:   0%|                               | 0/3 [00:00<?, ?it/s]Optimising conformer:  33%|███████▋               | 1/3 [00:04<00:08,  4.41s/it]Optimising conformer:  67%|███████████████▎       | 2/3 [00:07<00:03,  3.77s/it]Optimising conformer: 100%|███████████████████████| 3/3 [00:09<00:00,  2.90s/it]Optimising conformer: 100%|███████████████████████| 3/3 [00:09<00:00,  3.20s/it]
/mnt/storage/nobackup/nmb1063/code/gal/sars-cov-2-main-protease-al-study-plip/rsearcher.py:89: UserWarning: The ligand was an array (SDF?). Using the first frame. 
  warnings.warn("The ligand was an array (SDF?). Using the first frame. ")
/mnt/storage/nobackup/nmb1063/mamba/envs/fegrow/lib/python3.9/site-packages/parmed/structure.py:1775: UnitStrippedWarning: The unit of the quantity is stripped when downcasting to ndarray.
  coords = np.array(value, dtype=np.float64, copy=False, subok=True)
TIME Completed the molecule generation in 52.7s.
TIME changed dir: 0.0s
Generated 45 conformers. 
Removed 21 conformers. 
using ani2x
/mnt/storage/nobackup/nmb1063/mamba/envs/fegrow/lib/python3.9/site-packages/torchani/resources/
failed to equip `nnpops` with error: No module named 'NNPOps'
Optimising conformer:   0%|                               | 0/3 [00:00<?, ?it/s]Optimising conformer:  33%|███████▋               | 1/3 [00:03<00:06,  3.46s/it]Optimising conformer:  67%|███████████████▎       | 2/3 [00:06<00:02,  2.96s/it]Optimising conformer: 100%|███████████████████████| 3/3 [00:17<00:00,  6.78s/it]Optimising conformer: 100%|███████████████████████| 3/3 [00:17<00:00,  5.80s/it]
/mnt/storage/nobackup/nmb1063/code/gal/sars-cov-2-main-protease-al-study-plip/rsearcher.py:89: UserWarning: The ligand was an array (SDF?). Using the first frame. 
  warnings.warn("The ligand was an array (SDF?). Using the first frame. ")
TIME Completed the molecule generation in 111.6s.
using ani2x
/mnt/storage/nobackup/nmb1063/mamba/envs/fegrow/lib/python3.9/site-packages/torchani/resources/
failed to equip `nnpops` with error: No module named 'NNPOps'
Optimising conformer:   0%|                              | 0/24 [00:00<?, ?it/s]Optimising conformer:   4%|▉                     | 1/24 [00:04<01:46,  4.65s/it]Optimising conformer:   8%|█▊                    | 2/24 [00:07<01:18,  3.56s/it]Optimising conformer:  12%|██▊                   | 3/24 [00:09<00:59,  2.83s/it]Optimising conformer:  17%|███▋                  | 4/24 [00:12<01:01,  3.09s/it]Optimising conformer:  21%|████▌                 | 5/24 [00:16<01:00,  3.20s/it]Optimising conformer:  25%|█████▌                | 6/24 [00:18<00:52,  2.92s/it]Optimising conformer:  29%|██████▍               | 7/24 [00:22<00:55,  3.27s/it]Optimising conformer:  33%|███████▎              | 8/24 [00:25<00:51,  3.21s/it]Optimising conformer:  38%|████████▎             | 9/24 [00:28<00:44,  2.99s/it]Optimising conformer:  42%|████████▊            | 10/24 [00:31<00:43,  3.11s/it]Optimising conformer:  46%|█████████▋           | 11/24 [00:35<00:43,  3.34s/it]Optimising conformer:  50%|██████████▌          | 12/24 [00:37<00:35,  2.93s/it]Optimising conformer:  54%|███████████▍         | 13/24 [00:39<00:28,  2.56s/it]Optimising conformer:  58%|████████████▎        | 14/24 [00:41<00:25,  2.56s/it]Optimising conformer:  62%|█████████████▏       | 15/24 [00:43<00:20,  2.29s/it]Optimising conformer:  67%|██████████████       | 16/24 [00:45<00:18,  2.31s/it]Optimising conformer:  71%|██████████████▉      | 17/24 [00:48<00:17,  2.48s/it]Optimising conformer:  75%|███████████████▊     | 18/24 [00:50<00:14,  2.42s/it]Optimising conformer:  79%|████████████████▋    | 19/24 [00:53<00:11,  2.39s/it]Optimising conformer:  83%|█████████████████▌   | 20/24 [00:58<00:13,  3.38s/it]Optimising conformer:  88%|██████████████████▍  | 21/24 [01:02<00:10,  3.35s/it]Optimising conformer:  92%|███████████████████▎ | 22/24 [01:03<00:05,  2.78s/it]Optimising conformer:  96%|████████████████████▏| 23/24 [01:05<00:02,  2.46s/it]Optimising conformer: 100%|█████████████████████| 24/24 [01:06<00:00,  2.14s/it]Optimising conformer: 100%|█████████████████████| 24/24 [01:06<00:00,  2.78s/it]
/mnt/storage/nobackup/nmb1063/code/gal/sars-cov-2-main-protease-al-study-plip/rsearcher.py:89: UserWarning: The ligand was an array (SDF?). Using the first frame. 
  warnings.warn("The ligand was an array (SDF?). Using the first frame. ")
slurmstepd: error: *** JOB 19877660 ON sb030 CANCELLED AT 2024-01-29T05:20:39 DUE TO TIME LIMIT ***
