hostname sb082.cluster
ipconfig 1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN group default qlen 1000 link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00 inet 127.0.0.1/8 scope host lo valid_lft forever preferred_lft forever inet6 ::1/128 scope host valid_lft forever preferred_lft forever 2: enp4s0f0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 9000 qdisc mq state UP group default qlen 1000 link/ether a0:8c:f8:61:07:4a brd ff:ff:ff:ff:ff:ff inet 10.3.81.162/22 brd 10.3.83.255 scope global enp4s0f0 valid_lft forever preferred_lft forever inet6 fe80::a28c:f8ff:fe61:74a/64 scope link valid_lft forever preferred_lft forever 3: enp4s0f1: <BROADCAST,MULTICAST> mtu 1500 qdisc noop state DOWN group default qlen 1000 link/ether a0:8c:f8:61:07:4b brd ff:ff:ff:ff:ff:ff 4: enp4s0f2: <BROADCAST,MULTICAST> mtu 1500 qdisc noop state DOWN group default qlen 1000 link/ether a0:8c:f8:61:07:4c brd ff:ff:ff:ff:ff:ff 5: enp4s0f3: <BROADCAST,MULTICAST> mtu 1500 qdisc noop state DOWN group default qlen 1000 link/ether a0:8c:f8:61:07:4d brd ff:ff:ff:ff:ff:ff 6: ib0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 4092 qdisc pfifo_fast state UP group default qlen 256 link/infiniband 80:00:00:29:fe:80:00:00:00:00:00:00:38:bc:01:03:00:4c:f5:90 brd 00:ff:ff:ff:ff:12:40:1b:ff:ff:00:00:00:00:00:00:ff:ff:ff:ff inet 10.3.89.162/22 brd 10.3.91.255 scope global ib0 valid_lft forever preferred_lft forever inet 10.3.97.162/22 brd 10.3.99.255 scope global ib0:1 valid_lft forever preferred_lft forever inet6 fe80::3abc:103:4c:f590/64 scope link valid_lft forever preferred_lft forever 7: ib1: <BROADCAST,MULTICAST> mtu 4092 qdisc noop state DOWN group default qlen 256 link/infiniband 80:00:00:29:fe:80:00:00:00:00:00:00:38:bc:01:03:00:4c:f5:91 brd 00:ff:ff:ff:ff:12:40:1b:ff:ff:00:00:00:00:00:00:ff:ff:ff:ff
2024-01-19 04:43:34,831 - distributed.nanny - INFO -         Start Nanny at: 'tcp://10.3.89.162:38893'
2024-01-19 04:43:34,904 - distributed.nanny - INFO -         Start Nanny at: 'tcp://10.3.89.162:37252'
2024-01-19 04:43:37,505 - distributed.diskutils - INFO - Found stale lock file and directory '/scratch/dask-worker-space/worker-h1p48qbx', purging
2024-01-19 04:43:37,508 - distributed.diskutils - INFO - Found stale lock file and directory '/scratch/dask-worker-space/worker-dqedmnlc', purging
2024-01-19 04:43:50,485 - distributed.worker - INFO -       Start worker at:    tcp://10.3.89.162:36830
2024-01-19 04:43:50,486 - distributed.worker - INFO -          Listening to:    tcp://10.3.89.162:36830
2024-01-19 04:43:50,486 - distributed.worker - INFO -           Worker name:         SLURMCluster-455-1
2024-01-19 04:43:50,486 - distributed.worker - INFO -          dashboard at:          10.3.89.162:33912
2024-01-19 04:43:50,486 - distributed.worker - INFO - Waiting to connect to:     tcp://10.3.88.12:42763
2024-01-19 04:43:50,486 - distributed.worker - INFO - -------------------------------------------------
2024-01-19 04:43:50,486 - distributed.worker - INFO -               Threads:                          2
2024-01-19 04:43:50,487 - distributed.worker - INFO -                Memory:                  10.24 GiB
2024-01-19 04:43:50,487 - distributed.worker - INFO -       Local Directory: /scratch/dask-worker-space/worker-fvjy5mck
2024-01-19 04:43:50,487 - distributed.worker - INFO - -------------------------------------------------
2024-01-19 04:43:50,487 - distributed.worker - INFO -       Start worker at:    tcp://10.3.89.162:46465
2024-01-19 04:43:50,488 - distributed.worker - INFO -          Listening to:    tcp://10.3.89.162:46465
2024-01-19 04:43:50,488 - distributed.worker - INFO -           Worker name:         SLURMCluster-455-0
2024-01-19 04:43:50,488 - distributed.worker - INFO -          dashboard at:          10.3.89.162:44969
2024-01-19 04:43:50,488 - distributed.worker - INFO - Waiting to connect to:     tcp://10.3.88.12:42763
2024-01-19 04:43:50,488 - distributed.worker - INFO - -------------------------------------------------
2024-01-19 04:43:50,488 - distributed.worker - INFO -               Threads:                          2
2024-01-19 04:43:50,488 - distributed.worker - INFO -                Memory:                  10.24 GiB
2024-01-19 04:43:50,488 - distributed.worker - INFO -       Local Directory: /scratch/dask-worker-space/worker-dplrj0f9
2024-01-19 04:43:50,488 - distributed.worker - INFO - -------------------------------------------------
2024-01-19 04:43:50,556 - distributed.worker - INFO -         Registered to:     tcp://10.3.88.12:42763
2024-01-19 04:43:50,557 - distributed.worker - INFO - -------------------------------------------------
2024-01-19 04:43:50,557 - distributed.core - INFO - Starting established connection to tcp://10.3.88.12:42763
2024-01-19 04:43:50,561 - distributed.worker - INFO -         Registered to:     tcp://10.3.88.12:42763
2024-01-19 04:43:50,561 - distributed.worker - INFO - -------------------------------------------------
2024-01-19 04:43:50,561 - distributed.core - INFO - Starting established connection to tcp://10.3.88.12:42763
2024-01-19 05:37:21,224 - distributed.worker - ERROR - Worker stream died during communication: tcp://10.3.89.134:36679
Traceback (most recent call last):
  File "/mnt/storage/nobackup/nmb1063/mamba/envs/fegrow/lib/python3.9/site-packages/distributed/comm/tcp.py", line 225, in read
    frames_nbytes = await stream.read_bytes(fmt_size)
asyncio.exceptions.CancelledError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/mnt/storage/nobackup/nmb1063/mamba/envs/fegrow/lib/python3.9/asyncio/tasks.py", line 490, in wait_for
    return fut.result()
asyncio.exceptions.CancelledError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/mnt/storage/nobackup/nmb1063/mamba/envs/fegrow/lib/python3.9/site-packages/distributed/comm/core.py", line 328, in connect
    handshake = await asyncio.wait_for(comm.read(), time_left())
  File "/mnt/storage/nobackup/nmb1063/mamba/envs/fegrow/lib/python3.9/asyncio/tasks.py", line 492, in wait_for
    raise exceptions.TimeoutError() from exc
asyncio.exceptions.TimeoutError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/mnt/storage/nobackup/nmb1063/mamba/envs/fegrow/lib/python3.9/site-packages/distributed/worker.py", line 2081, in gather_dep
    response = await get_data_from_worker(
  File "/mnt/storage/nobackup/nmb1063/mamba/envs/fegrow/lib/python3.9/site-packages/distributed/worker.py", line 2900, in get_data_from_worker
    comm = await rpc.connect(worker)
  File "/mnt/storage/nobackup/nmb1063/mamba/envs/fegrow/lib/python3.9/site-packages/distributed/core.py", line 1468, in connect
    return await connect_attempt
  File "/mnt/storage/nobackup/nmb1063/mamba/envs/fegrow/lib/python3.9/site-packages/distributed/core.py", line 1389, in _connect
    comm = await connect(
  File "/mnt/storage/nobackup/nmb1063/mamba/envs/fegrow/lib/python3.9/site-packages/distributed/comm/core.py", line 333, in connect
    raise OSError(
OSError: Timed out during handshake while connecting to tcp://10.3.89.134:36679 after 30 s
2024-01-19 05:37:21,245 - distributed.worker - ERROR - Worker stream died during communication: tcp://10.3.89.129:41350
Traceback (most recent call last):
  File "/mnt/storage/nobackup/nmb1063/mamba/envs/fegrow/lib/python3.9/site-packages/distributed/comm/tcp.py", line 225, in read
    frames_nbytes = await stream.read_bytes(fmt_size)
asyncio.exceptions.CancelledError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/mnt/storage/nobackup/nmb1063/mamba/envs/fegrow/lib/python3.9/asyncio/tasks.py", line 490, in wait_for
    return fut.result()
asyncio.exceptions.CancelledError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/mnt/storage/nobackup/nmb1063/mamba/envs/fegrow/lib/python3.9/site-packages/distributed/comm/core.py", line 328, in connect
    handshake = await asyncio.wait_for(comm.read(), time_left())
  File "/mnt/storage/nobackup/nmb1063/mamba/envs/fegrow/lib/python3.9/asyncio/tasks.py", line 492, in wait_for
    raise exceptions.TimeoutError() from exc
asyncio.exceptions.TimeoutError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/mnt/storage/nobackup/nmb1063/mamba/envs/fegrow/lib/python3.9/site-packages/distributed/worker.py", line 2081, in gather_dep
    response = await get_data_from_worker(
  File "/mnt/storage/nobackup/nmb1063/mamba/envs/fegrow/lib/python3.9/site-packages/distributed/worker.py", line 2900, in get_data_from_worker
    comm = await rpc.connect(worker)
  File "/mnt/storage/nobackup/nmb1063/mamba/envs/fegrow/lib/python3.9/site-packages/distributed/core.py", line 1468, in connect
    return await connect_attempt
  File "/mnt/storage/nobackup/nmb1063/mamba/envs/fegrow/lib/python3.9/site-packages/distributed/core.py", line 1389, in _connect
    comm = await connect(
  File "/mnt/storage/nobackup/nmb1063/mamba/envs/fegrow/lib/python3.9/site-packages/distributed/comm/core.py", line 333, in connect
    raise OSError(
OSError: Timed out during handshake while connecting to tcp://10.3.89.129:41350 after 30 s
2024-01-19 05:37:54,409 - distributed.core - INFO - Event loop was unresponsive in Worker for 33.16s.  This is often caused by long-running GIL-holding functions or moving large chunks of data. This can cause timeouts and instability.
/mnt/storage/nobackup/nmb1063/mamba/envs/fegrow/lib/python3.9/site-packages/parmed/structure.py:1775: UnitStrippedWarning: The unit of the quantity is stripped when downcasting to ndarray.
  coords = np.array(value, dtype=np.float64, copy=False, subok=True)
2024-01-19 05:38:03,567 - distributed.core - INFO - Event loop was unresponsive in Worker for 8.71s.  This is often caused by long-running GIL-holding functions or moving large chunks of data. This can cause timeouts and instability.
/mnt/storage/nobackup/nmb1063/mamba/envs/fegrow/lib/python3.9/site-packages/parmed/structure.py:1775: UnitStrippedWarning: The unit of the quantity is stripped when downcasting to ndarray.
  coords = np.array(value, dtype=np.float64, copy=False, subok=True)
/mnt/storage/nobackup/nmb1063/mamba/envs/fegrow/lib/python3.9/site-packages/torchani/__init__.py:55: UserWarning: Dependency not satisfied, torchani.ase will not be available
  warnings.warn("Dependency not satisfied, torchani.ase will not be available")
Warning: importing 'simtk.openmm' is deprecated.  Import 'openmm' instead.
/mnt/storage/nobackup/nmb1063/mamba/envs/fegrow/lib/python3.9/site-packages/torchani/__init__.py:55: UserWarning: Dependency not satisfied, torchani.ase will not be available
  warnings.warn("Dependency not satisfied, torchani.ase will not be available")
Warning: importing 'simtk.openmm' is deprecated.  Import 'openmm' instead.
2024-01-19 05:38:50,059 - distributed.nanny - INFO - Worker process 27878 was killed by signal 11
2024-01-19 05:38:50,066 - distributed.nanny - WARNING - Restarting worker
TIME changed dir: 0.0s
TIME changed dir: 0.0s
Generated 30 conformers. 
Generated 38 conformers. 
Removed 20 conformers. 
Removed 20 conformers. 
using ani2x
/mnt/storage/nobackup/nmb1063/mamba/envs/fegrow/lib/python3.9/site-packages/torchani/resources/
failed to equip `nnpops` with error: No module named 'NNPOps'
using ani2x
/mnt/storage/nobackup/nmb1063/mamba/envs/fegrow/lib/python3.9/site-packages/torchani/resources/
Optimising conformer:   0%|                              | 0/10 [00:00<?, ?it/s][W BinaryOps.cpp:601] Warning: floor_divide is deprecated, and will be removed in a future version of pytorch. It currently rounds toward 0 (like the 'trunc' function NOT 'floor'). This results in incorrect rounding for negative values.
To keep the current behavior, use torch.div(a, b, rounding_mode='trunc'), or for actual floor division, use torch.div(a, b, rounding_mode='floor'). (function operator())
Optimising conformer:  10%|██▏                   | 1/10 [00:03<00:27,  3.01s/it]2024-01-19 05:38:55,124 - distributed.worker - INFO -       Start worker at:    tcp://10.3.89.162:36578
2024-01-19 05:38:55,125 - distributed.worker - INFO -          Listening to:    tcp://10.3.89.162:36578
2024-01-19 05:38:55,125 - distributed.worker - INFO -           Worker name:         SLURMCluster-455-1
2024-01-19 05:38:55,125 - distributed.worker - INFO -          dashboard at:          10.3.89.162:45000
2024-01-19 05:38:55,125 - distributed.worker - INFO - Waiting to connect to:     tcp://10.3.88.12:42763
2024-01-19 05:38:55,125 - distributed.worker - INFO - -------------------------------------------------
2024-01-19 05:38:55,125 - distributed.worker - INFO -               Threads:                          2
2024-01-19 05:38:55,125 - distributed.worker - INFO -                Memory:                  10.24 GiB
2024-01-19 05:38:55,125 - distributed.worker - INFO -       Local Directory: /scratch/dask-worker-space/worker-uguv351q
2024-01-19 05:38:55,125 - distributed.worker - INFO - -------------------------------------------------
2024-01-19 05:38:55,167 - distributed.worker - INFO -         Registered to:     tcp://10.3.88.12:42763
2024-01-19 05:38:55,167 - distributed.worker - INFO - -------------------------------------------------
2024-01-19 05:38:55,168 - distributed.core - INFO - Starting established connection to tcp://10.3.88.12:42763
Optimising conformer:  20%|████▍                 | 2/10 [00:04<00:17,  2.14s/it]failed to equip `nnpops` with error: No module named 'NNPOps'

Optimising conformer:   0%|                              | 0/18 [00:00<?, ?it/s][AOptimising conformer:  30%|██████▌               | 3/10 [00:06<00:12,  1.83s/it]Optimising conformer:  40%|████████▊             | 4/10 [00:07<00:10,  1.69s/it]Optimising conformer:  50%|███████████           | 5/10 [00:09<00:08,  1.67s/it]Optimising conformer:  60%|█████████████▏        | 6/10 [00:11<00:07,  1.76s/it]Optimising conformer:  70%|███████████████▍      | 7/10 [00:13<00:05,  1.95s/it]Optimising conformer:  80%|█████████████████▌    | 8/10 [00:14<00:03,  1.72s/it]Optimising conformer:  90%|███████████████████▊  | 9/10 [00:16<00:01,  1.69s/it]Optimising conformer: 100%|█████████████████████| 10/10 [00:18<00:00,  1.92s/it]Optimising conformer: 100%|█████████████████████| 10/10 [00:18<00:00,  1.87s/it]

Optimising conformer:   6%|█▏                    | 1/18 [00:26<07:37, 26.94s/it][A
Optimising conformer:  11%|██▍                   | 2/18 [00:29<03:18, 12.42s/it][A
Optimising conformer:  17%|███▋                  | 3/18 [00:32<02:01,  8.08s/it][A
Optimising conformer:  22%|████▉                 | 4/18 [00:33<01:15,  5.40s/it][A
Optimising conformer:  28%|██████                | 5/18 [00:34<00:50,  3.91s/it][A
Optimising conformer:  33%|███████▎              | 6/18 [00:37<00:42,  3.56s/it][A
Optimising conformer:  39%|████████▌             | 7/18 [00:39<00:34,  3.11s/it][A
Optimising conformer:  44%|█████████▊            | 8/18 [00:43<00:33,  3.32s/it][A
Optimising conformer:  50%|███████████           | 9/18 [00:45<00:26,  2.92s/it][A
Optimising conformer:  56%|███████████▋         | 10/18 [00:47<00:21,  2.63s/it][A
Optimising conformer:  61%|████████████▊        | 11/18 [00:48<00:15,  2.26s/it][A
Optimising conformer:  67%|██████████████       | 12/18 [01:15<00:57,  9.64s/it][A
Optimising conformer:  72%|███████████████▏     | 13/18 [01:17<00:37,  7.40s/it][A
Optimising conformer:  78%|████████████████▎    | 14/18 [01:19<00:22,  5.70s/it][A
Optimising conformer:  83%|█████████████████▌   | 15/18 [01:20<00:13,  4.37s/it][A
Optimising conformer:  89%|██████████████████▋  | 16/18 [01:23<00:07,  3.74s/it][A
Optimising conformer:  94%|███████████████████▊ | 17/18 [01:24<00:03,  3.15s/it][A
Optimising conformer: 100%|█████████████████████| 18/18 [01:26<00:00,  2.59s/it][AOptimising conformer: 100%|█████████████████████| 18/18 [01:26<00:00,  4.79s/it]
2024-01-19 06:14:36,354 - distributed.utils_perf - INFO - full garbage collection released 10.02 MiB from 480372 reference cycles (threshold: 9.54 MiB)
Warning (not error because allow_undefined_stereo=True): RDMol has unspecified stereochemistry. Bonds with undefined stereochemistry are:
 - Bond 1 (atoms 1-2 of element (C-C)

/mnt/storage/nobackup/nmb1063/mamba/envs/fegrow/lib/python3.9/site-packages/parmed/structure.py:1775: UnitStrippedWarning: The unit of the quantity is stripped when downcasting to ndarray.
  coords = np.array(value, dtype=np.float64, copy=False, subok=True)
Warning (not error because allow_undefined_stereo=True): RDMol has unspecified stereochemistry. Bonds with undefined stereochemistry are:
 - Bond 1 (atoms 1-2 of element (C-C)

/mnt/storage/nobackup/nmb1063/mamba/envs/fegrow/lib/python3.9/site-packages/parmed/structure.py:1775: UnitStrippedWarning: The unit of the quantity is stripped when downcasting to ndarray.
  coords = np.array(value, dtype=np.float64, copy=False, subok=True)
TIME Completed the molecule generation in 85.3s.
TIME Completed the molecule generation in 156.3s.
TIME changed dir: 0.0s
TIME changed dir: 0.0s
Generated 36 conformers. 
Removed 25 conformers. 
Generated 27 conformers. 
Removed 21 conformers. 
using ani2x
/mnt/storage/nobackup/nmb1063/mamba/envs/fegrow/lib/python3.9/site-packages/torchani/resources/
failed to equip `nnpops` with error: No module named 'NNPOps'
Optimising conformer:   0%|                              | 0/11 [00:00<?, ?it/s]2024-01-19 06:15:35,939 - distributed.core - INFO - Event loop was unresponsive in Worker for 8.91s.  This is often caused by long-running GIL-holding functions or moving large chunks of data. This can cause timeouts and instability.
Optimising conformer:   9%|██                    | 1/11 [00:03<00:33,  3.34s/it]/mnt/storage/nobackup/nmb1063/mamba/envs/fegrow/lib/python3.9/site-packages/parmed/structure.py:1775: UnitStrippedWarning: The unit of the quantity is stripped when downcasting to ndarray.
  coords = np.array(value, dtype=np.float64, copy=False, subok=True)
Optimising conformer:  18%|████                  | 2/11 [00:16<01:20,  8.89s/it]Optimising conformer:  27%|██████                | 3/11 [00:18<00:45,  5.72s/it]Optimising conformer:  36%|████████              | 4/11 [00:34<01:10, 10.00s/it]Optimising conformer:  45%|██████████            | 5/11 [00:36<00:42,  7.02s/it]using ani2x
/mnt/storage/nobackup/nmb1063/mamba/envs/fegrow/lib/python3.9/site-packages/torchani/resources/
failed to equip `nnpops` with error: No module named 'NNPOps'

Optimising conformer:   0%|                               | 0/6 [00:00<?, ?it/s][A
Optimising conformer:  17%|███▊                   | 1/6 [00:03<00:17,  3.49s/it][AOptimising conformer:  55%|████████████          | 6/11 [00:53<00:52, 10.56s/it]
Optimising conformer:  33%|███████▋               | 2/6 [00:10<00:21,  5.37s/it][AOptimising conformer:  64%|██████████████        | 7/11 [00:56<00:32,  8.03s/it]
Optimising conformer:  50%|███████████▌           | 3/6 [00:13<00:13,  4.35s/it][AOptimising conformer:  73%|████████████████      | 8/11 [01:00<00:19,  6.67s/it]
Optimising conformer:  67%|███████████████▎       | 4/6 [00:15<00:07,  3.51s/it][AOptimising conformer:  82%|██████████████████    | 9/11 [01:03<00:10,  5.45s/it]
Optimising conformer:  83%|███████████████████▏   | 5/6 [00:17<00:02,  2.98s/it][AOptimising conformer:  91%|███████████████████  | 10/11 [01:04<00:04,  4.30s/it]
Optimising conformer: 100%|███████████████████████| 6/6 [00:19<00:00,  2.68s/it][AOptimising conformer: 100%|███████████████████████| 6/6 [00:19<00:00,  3.28s/it]
Optimising conformer: 100%|█████████████████████| 11/11 [01:06<00:00,  3.55s/it]Optimising conformer: 100%|█████████████████████| 11/11 [01:06<00:00,  6.06s/it]
/mnt/storage/nobackup/nmb1063/mamba/envs/fegrow/lib/python3.9/site-packages/torchani/__init__.py:55: UserWarning: Dependency not satisfied, torchani.ase will not be available
  warnings.warn("Dependency not satisfied, torchani.ase will not be available")
Warning: importing 'simtk.openmm' is deprecated.  Import 'openmm' instead.
TIME changed dir: 0.0s
TIME changed dir: 0.0s
Generated 8 conformers. 
Removed 6 conformers. 
Generated 25 conformers. 
Removed 18 conformers. 
using ani2x
/mnt/storage/nobackup/nmb1063/mamba/envs/fegrow/lib/python3.9/site-packages/torchani/resources/
failed to equip `nnpops` with error: No module named 'NNPOps'
Optimising conformer:   0%|                               | 0/2 [00:00<?, ?it/s][W BinaryOps.cpp:601] Warning: floor_divide is deprecated, and will be removed in a future version of pytorch. It currently rounds toward 0 (like the 'trunc' function NOT 'floor'). This results in incorrect rounding for negative values.
To keep the current behavior, use torch.div(a, b, rounding_mode='trunc'), or for actual floor division, use torch.div(a, b, rounding_mode='floor'). (function operator())
Optimising conformer:  50%|███████████▌           | 1/2 [00:02<00:02,  2.20s/it]Optimising conformer: 100%|███████████████████████| 2/2 [00:03<00:00,  1.49s/it]Optimising conformer: 100%|███████████████████████| 2/2 [00:03<00:00,  1.59s/it]
TIME Completed the molecule generation in 128.1s.
using ani2x
/mnt/storage/nobackup/nmb1063/mamba/envs/fegrow/lib/python3.9/site-packages/torchani/resources/
failed to equip `nnpops` with error: No module named 'NNPOps'
Optimising conformer:   0%|                               | 0/7 [00:00<?, ?it/s]Optimising conformer:  14%|███▎                   | 1/7 [00:03<00:20,  3.34s/it]Optimising conformer:  29%|██████▌                | 2/7 [00:05<00:12,  2.48s/it]Optimising conformer:  43%|█████████▊             | 3/7 [00:07<00:09,  2.44s/it]Optimising conformer:  57%|█████████████▏         | 4/7 [00:09<00:06,  2.31s/it]Optimising conformer:  71%|████████████████▍      | 5/7 [00:11<00:04,  2.29s/it]Optimising conformer:  86%|███████████████████▋   | 6/7 [00:14<00:02,  2.38s/it]Optimising conformer: 100%|███████████████████████| 7/7 [00:16<00:00,  2.15s/it]Optimising conformer: 100%|███████████████████████| 7/7 [00:16<00:00,  2.32s/it]
2024-01-19 07:42:06,864 - distributed.worker - ERROR - Worker stream died during communication: tcp://10.3.89.95:35361
Traceback (most recent call last):
  File "/mnt/storage/nobackup/nmb1063/mamba/envs/fegrow/lib/python3.9/site-packages/distributed/comm/tcp.py", line 225, in read
    frames_nbytes = await stream.read_bytes(fmt_size)
asyncio.exceptions.CancelledError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/mnt/storage/nobackup/nmb1063/mamba/envs/fegrow/lib/python3.9/asyncio/tasks.py", line 490, in wait_for
    return fut.result()
asyncio.exceptions.CancelledError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/mnt/storage/nobackup/nmb1063/mamba/envs/fegrow/lib/python3.9/site-packages/distributed/comm/core.py", line 328, in connect
    handshake = await asyncio.wait_for(comm.read(), time_left())
  File "/mnt/storage/nobackup/nmb1063/mamba/envs/fegrow/lib/python3.9/asyncio/tasks.py", line 492, in wait_for
    raise exceptions.TimeoutError() from exc
asyncio.exceptions.TimeoutError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/mnt/storage/nobackup/nmb1063/mamba/envs/fegrow/lib/python3.9/site-packages/distributed/worker.py", line 2081, in gather_dep
    response = await get_data_from_worker(
  File "/mnt/storage/nobackup/nmb1063/mamba/envs/fegrow/lib/python3.9/site-packages/distributed/worker.py", line 2900, in get_data_from_worker
    comm = await rpc.connect(worker)
  File "/mnt/storage/nobackup/nmb1063/mamba/envs/fegrow/lib/python3.9/site-packages/distributed/core.py", line 1468, in connect
    return await connect_attempt
  File "/mnt/storage/nobackup/nmb1063/mamba/envs/fegrow/lib/python3.9/site-packages/distributed/core.py", line 1389, in _connect
    comm = await connect(
  File "/mnt/storage/nobackup/nmb1063/mamba/envs/fegrow/lib/python3.9/site-packages/distributed/comm/core.py", line 333, in connect
    raise OSError(
OSError: Timed out during handshake while connecting to tcp://10.3.89.95:35361 after 30 s
2024-01-19 07:42:06,887 - distributed.worker - ERROR - Worker stream died during communication: tcp://10.3.89.95:33957
Traceback (most recent call last):
  File "/mnt/storage/nobackup/nmb1063/mamba/envs/fegrow/lib/python3.9/site-packages/distributed/comm/tcp.py", line 225, in read
    frames_nbytes = await stream.read_bytes(fmt_size)
asyncio.exceptions.CancelledError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/mnt/storage/nobackup/nmb1063/mamba/envs/fegrow/lib/python3.9/asyncio/tasks.py", line 490, in wait_for
    return fut.result()
asyncio.exceptions.CancelledError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/mnt/storage/nobackup/nmb1063/mamba/envs/fegrow/lib/python3.9/site-packages/distributed/comm/core.py", line 328, in connect
    handshake = await asyncio.wait_for(comm.read(), time_left())
  File "/mnt/storage/nobackup/nmb1063/mamba/envs/fegrow/lib/python3.9/asyncio/tasks.py", line 492, in wait_for
    raise exceptions.TimeoutError() from exc
asyncio.exceptions.TimeoutError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/mnt/storage/nobackup/nmb1063/mamba/envs/fegrow/lib/python3.9/site-packages/distributed/worker.py", line 2081, in gather_dep
    response = await get_data_from_worker(
  File "/mnt/storage/nobackup/nmb1063/mamba/envs/fegrow/lib/python3.9/site-packages/distributed/worker.py", line 2900, in get_data_from_worker
    comm = await rpc.connect(worker)
  File "/mnt/storage/nobackup/nmb1063/mamba/envs/fegrow/lib/python3.9/site-packages/distributed/core.py", line 1468, in connect
    return await connect_attempt
  File "/mnt/storage/nobackup/nmb1063/mamba/envs/fegrow/lib/python3.9/site-packages/distributed/core.py", line 1389, in _connect
    comm = await connect(
  File "/mnt/storage/nobackup/nmb1063/mamba/envs/fegrow/lib/python3.9/site-packages/distributed/comm/core.py", line 333, in connect
    raise OSError(
OSError: Timed out during handshake while connecting to tcp://10.3.89.95:33957 after 30 s
/mnt/storage/nobackup/nmb1063/mamba/envs/fegrow/lib/python3.9/site-packages/parmed/structure.py:1775: UnitStrippedWarning: The unit of the quantity is stripped when downcasting to ndarray.
  coords = np.array(value, dtype=np.float64, copy=False, subok=True)
/mnt/storage/nobackup/nmb1063/mamba/envs/fegrow/lib/python3.9/site-packages/parmed/structure.py:1775: UnitStrippedWarning: The unit of the quantity is stripped when downcasting to ndarray.
  coords = np.array(value, dtype=np.float64, copy=False, subok=True)
/mnt/storage/nobackup/nmb1063/mamba/envs/fegrow/lib/python3.9/site-packages/parmed/structure.py:1775: UnitStrippedWarning: The unit of the quantity is stripped when downcasting to ndarray.
  coords = np.array(value, dtype=np.float64, copy=False, subok=True)
/mnt/storage/nobackup/nmb1063/mamba/envs/fegrow/lib/python3.9/site-packages/parmed/structure.py:1775: UnitStrippedWarning: The unit of the quantity is stripped when downcasting to ndarray.
  coords = np.array(value, dtype=np.float64, copy=False, subok=True)
TIME Completed the molecule generation in 388.0s.
TIME changed dir: 0.0s
TIME changed dir: 0.0s
Generated 8 conformers. 
Generated 27 conformers. 
Removed 4 conformers. 
Removed 17 conformers. 
using ani2x
/mnt/storage/nobackup/nmb1063/mamba/envs/fegrow/lib/python3.9/site-packages/torchani/resources/
failed to equip `nnpops` with error: No module named 'NNPOps'
Optimising conformer:   0%|                              | 0/10 [00:00<?, ?it/s]Optimising conformer:  10%|██▏                   | 1/10 [00:02<00:24,  2.68s/it]Optimising conformer:  20%|████▍                 | 2/10 [00:04<00:17,  2.14s/it]Optimising conformer:  30%|██████▌               | 3/10 [00:06<00:13,  1.96s/it]Optimising conformer:  40%|████████▊             | 4/10 [00:07<00:10,  1.76s/it]TIME Completed the molecule generation in 146.6s.
TIME Completed the molecule generation in 157.3s.
TIME changed dir: 0.0s
TIME changed dir: 0.0s
Generated 42 conformers. 
Generated 36 conformers. 
Removed 28 conformers. 
Removed 22 conformers. 
using ani2x
using ani2x
/mnt/storage/nobackup/nmb1063/mamba/envs/fegrow/lib/python3.9/site-packages/torchani/resources/
/mnt/storage/nobackup/nmb1063/mamba/envs/fegrow/lib/python3.9/site-packages/torchani/resources/
failed to equip `nnpops` with error: No module named 'NNPOps'
failed to equip `nnpops` with error: No module named 'NNPOps'
Optimising conformer:   0%|                               | 0/8 [00:00<?, ?it/s]
Optimising conformer:   0%|                              | 0/20 [00:00<?, ?it/s][AOptimising conformer:  50%|███████████           | 5/10 [00:09<00:09,  1.81s/it]Optimising conformer:  12%|██▉                    | 1/8 [00:04<00:28,  4.13s/it]Optimising conformer:  25%|█████▊                 | 2/8 [00:06<00:19,  3.25s/it]using ani2x
/mnt/storage/nobackup/nmb1063/mamba/envs/fegrow/lib/python3.9/site-packages/torchani/resources/
failed to equip `nnpops` with error: No module named 'NNPOps'

Optimising conformer:   0%|                               | 0/4 [00:00<?, ?it/s][AOptimising conformer:  60%|█████████████▏        | 6/10 [00:19<00:18,  4.68s/it]
Optimising conformer:  25%|█████▊                 | 1/4 [00:03<00:09,  3.21s/it][A
Optimising conformer:  50%|███████████▌           | 2/4 [00:06<00:06,  3.22s/it][A
Optimising conformer:  75%|█████████████████▎     | 3/4 [00:10<00:03,  3.40s/it][A
Optimising conformer:   5%|█                     | 1/20 [00:20<06:36, 20.87s/it][A
Optimising conformer: 100%|███████████████████████| 4/4 [00:11<00:00,  2.76s/it][AOptimising conformer: 100%|███████████████████████| 4/4 [00:11<00:00,  2.96s/it]
Optimising conformer:  70%|███████████████▍      | 7/10 [00:31<00:21,  7.01s/it]
Optimising conformer:  10%|██▏                   | 2/20 [00:23<03:00, 10.02s/it][AOptimising conformer:  80%|█████████████████▌    | 8/10 [00:33<00:10,  5.39s/it]Optimising conformer:  90%|███████████████████▊  | 9/10 [00:35<00:04,  4.29s/it]
Optimising conformer:  15%|███▎                  | 3/20 [00:27<02:05,  7.35s/it][AOptimising conformer: 100%|█████████████████████| 10/10 [00:37<00:00,  3.62s/it]Optimising conformer: 100%|█████████████████████| 10/10 [00:37<00:00,  3.75s/it]

Optimising conformer:  20%|████▍                 | 4/20 [00:31<01:38,  6.14s/it][A
Optimising conformer:  25%|█████▌                | 5/20 [00:35<01:16,  5.13s/it][AOptimising conformer:  38%|████████▋              | 3/8 [00:37<01:20, 16.02s/it]
Optimising conformer:  30%|██████▌               | 6/20 [00:37<00:58,  4.18s/it][AOptimising conformer:  50%|███████████▌           | 4/8 [00:41<00:44, 11.22s/it]
Optimising conformer:  35%|███████▋              | 7/20 [00:42<00:58,  4.47s/it][AOptimising conformer:  62%|██████████████▍        | 5/8 [00:43<00:23,  7.80s/it]
Optimising conformer:  40%|████████▊             | 8/20 [00:45<00:49,  4.13s/it][AOptimising conformer:  75%|█████████████████▎     | 6/8 [00:47<00:12,  6.44s/it]Optimising conformer:  88%|████████████████████▏  | 7/8 [00:50<00:05,  5.48s/it]
Optimising conformer:  45%|█████████▉            | 9/20 [00:52<00:53,  4.90s/it][AOptimising conformer: 100%|███████████████████████| 8/8 [00:55<00:00,  5.13s/it]Optimising conformer: 100%|███████████████████████| 8/8 [00:55<00:00,  6.91s/it]

Optimising conformer:  50%|██████████▌          | 10/20 [00:54<00:40,  4.06s/it][A
Optimising conformer:  55%|███████████▌         | 11/20 [00:56<00:30,  3.35s/it][A
Optimising conformer:  60%|████████████▌        | 12/20 [00:58<00:23,  2.97s/it][A
Optimising conformer:  65%|█████████████▋       | 13/20 [01:01<00:20,  2.88s/it][A
Optimising conformer:  70%|██████████████▋      | 14/20 [01:02<00:14,  2.45s/it][A
Optimising conformer:  75%|███████████████▊     | 15/20 [01:04<00:11,  2.24s/it][A
Optimising conformer:  80%|████████████████▊    | 16/20 [01:07<00:09,  2.41s/it][A
Optimising conformer:  85%|█████████████████▊   | 17/20 [01:13<00:11,  3.71s/it][A
Optimising conformer:  90%|██████████████████▉  | 18/20 [01:17<00:07,  3.58s/it][A
Optimising conformer:  95%|███████████████████▉ | 19/20 [01:18<00:03,  3.03s/it][A
Optimising conformer: 100%|█████████████████████| 20/20 [01:20<00:00,  2.54s/it][AOptimising conformer: 100%|█████████████████████| 20/20 [01:20<00:00,  4.02s/it]
2024-01-19 08:03:39,333 - distributed.worker - ERROR - Worker stream died during communication: tcp://10.3.89.124:40469
Traceback (most recent call last):
  File "/mnt/storage/nobackup/nmb1063/mamba/envs/fegrow/lib/python3.9/site-packages/distributed/comm/tcp.py", line 225, in read
    frames_nbytes = await stream.read_bytes(fmt_size)
asyncio.exceptions.CancelledError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/mnt/storage/nobackup/nmb1063/mamba/envs/fegrow/lib/python3.9/asyncio/tasks.py", line 490, in wait_for
    return fut.result()
asyncio.exceptions.CancelledError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/mnt/storage/nobackup/nmb1063/mamba/envs/fegrow/lib/python3.9/site-packages/distributed/comm/core.py", line 328, in connect
    handshake = await asyncio.wait_for(comm.read(), time_left())
  File "/mnt/storage/nobackup/nmb1063/mamba/envs/fegrow/lib/python3.9/asyncio/tasks.py", line 492, in wait_for
    raise exceptions.TimeoutError() from exc
asyncio.exceptions.TimeoutError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/mnt/storage/nobackup/nmb1063/mamba/envs/fegrow/lib/python3.9/site-packages/distributed/worker.py", line 2081, in gather_dep
    response = await get_data_from_worker(
  File "/mnt/storage/nobackup/nmb1063/mamba/envs/fegrow/lib/python3.9/site-packages/distributed/worker.py", line 2900, in get_data_from_worker
    comm = await rpc.connect(worker)
  File "/mnt/storage/nobackup/nmb1063/mamba/envs/fegrow/lib/python3.9/site-packages/distributed/core.py", line 1468, in connect
    return await connect_attempt
  File "/mnt/storage/nobackup/nmb1063/mamba/envs/fegrow/lib/python3.9/site-packages/distributed/core.py", line 1389, in _connect
    comm = await connect(
  File "/mnt/storage/nobackup/nmb1063/mamba/envs/fegrow/lib/python3.9/site-packages/distributed/comm/core.py", line 333, in connect
    raise OSError(
OSError: Timed out during handshake while connecting to tcp://10.3.89.124:40469 after 30 s
2024-01-19 08:03:39,342 - distributed.worker - ERROR - Worker stream died during communication: tcp://10.3.89.124:44379
Traceback (most recent call last):
  File "/mnt/storage/nobackup/nmb1063/mamba/envs/fegrow/lib/python3.9/site-packages/distributed/comm/tcp.py", line 225, in read
    frames_nbytes = await stream.read_bytes(fmt_size)
asyncio.exceptions.CancelledError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/mnt/storage/nobackup/nmb1063/mamba/envs/fegrow/lib/python3.9/asyncio/tasks.py", line 490, in wait_for
    return fut.result()
asyncio.exceptions.CancelledError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/mnt/storage/nobackup/nmb1063/mamba/envs/fegrow/lib/python3.9/site-packages/distributed/comm/core.py", line 328, in connect
    handshake = await asyncio.wait_for(comm.read(), time_left())
  File "/mnt/storage/nobackup/nmb1063/mamba/envs/fegrow/lib/python3.9/asyncio/tasks.py", line 492, in wait_for
    raise exceptions.TimeoutError() from exc
asyncio.exceptions.TimeoutError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/mnt/storage/nobackup/nmb1063/mamba/envs/fegrow/lib/python3.9/site-packages/distributed/worker.py", line 2081, in gather_dep
    response = await get_data_from_worker(
  File "/mnt/storage/nobackup/nmb1063/mamba/envs/fegrow/lib/python3.9/site-packages/distributed/worker.py", line 2900, in get_data_from_worker
    comm = await rpc.connect(worker)
  File "/mnt/storage/nobackup/nmb1063/mamba/envs/fegrow/lib/python3.9/site-packages/distributed/core.py", line 1468, in connect
    return await connect_attempt
  File "/mnt/storage/nobackup/nmb1063/mamba/envs/fegrow/lib/python3.9/site-packages/distributed/core.py", line 1389, in _connect
    comm = await connect(
  File "/mnt/storage/nobackup/nmb1063/mamba/envs/fegrow/lib/python3.9/site-packages/distributed/comm/core.py", line 333, in connect
    raise OSError(
OSError: Timed out during handshake while connecting to tcp://10.3.89.124:44379 after 30 s
/mnt/storage/nobackup/nmb1063/mamba/envs/fegrow/lib/python3.9/site-packages/parmed/structure.py:1775: UnitStrippedWarning: The unit of the quantity is stripped when downcasting to ndarray.
  coords = np.array(value, dtype=np.float64, copy=False, subok=True)
/mnt/storage/nobackup/nmb1063/mamba/envs/fegrow/lib/python3.9/site-packages/parmed/structure.py:1775: UnitStrippedWarning: The unit of the quantity is stripped when downcasting to ndarray.
  coords = np.array(value, dtype=np.float64, copy=False, subok=True)
/mnt/storage/nobackup/nmb1063/mamba/envs/fegrow/lib/python3.9/site-packages/parmed/structure.py:1775: UnitStrippedWarning: The unit of the quantity is stripped when downcasting to ndarray.
  coords = np.array(value, dtype=np.float64, copy=False, subok=True)
/mnt/storage/nobackup/nmb1063/mamba/envs/fegrow/lib/python3.9/site-packages/parmed/structure.py:1775: UnitStrippedWarning: The unit of the quantity is stripped when downcasting to ndarray.
  coords = np.array(value, dtype=np.float64, copy=False, subok=True)
TIME Completed the molecule generation in 133.0s.
TIME Completed the molecule generation in 158.8s.
TIME changed dir: 0.0s
TIME changed dir: 0.0s
Generated 47 conformers. 
Generated 40 conformers. 
Removed 39 conformers. 
Removed 29 conformers. 
using ani2x
/mnt/storage/nobackup/nmb1063/mamba/envs/fegrow/lib/python3.9/site-packages/torchani/resources/
failed to equip `nnpops` with error: No module named 'NNPOps'
Optimising conformer:   0%|                               | 0/1 [00:00<?, ?it/s]TIME Completed the molecule generation in 93.7s.
TIME Completed the molecule generation in 117.6s.
TIME changed dir: 0.0s
TIME changed dir: 0.0s
Generated 8 conformers. 
Removed 6 conformers. 
Generated 22 conformers. 
Removed 16 conformers. 
using ani2x
/mnt/storage/nobackup/nmb1063/mamba/envs/fegrow/lib/python3.9/site-packages/torchani/resources/
failed to equip `nnpops` with error: No module named 'NNPOps'
Optimising conformer:   0%|                               | 0/2 [00:00<?, ?it/s]Optimising conformer: 100%|███████████████████████| 1/1 [00:04<00:00,  4.05s/it]Optimising conformer: 100%|███████████████████████| 1/1 [00:04<00:00,  4.05s/it]
Optimising conformer:  50%|███████████▌           | 1/2 [00:04<00:04,  4.03s/it]Optimising conformer: 100%|███████████████████████| 2/2 [00:06<00:00,  3.10s/it]Optimising conformer: 100%|███████████████████████| 2/2 [00:06<00:00,  3.24s/it]
TIME Completed the molecule generation in 79.6s.
using ani2x
/mnt/storage/nobackup/nmb1063/mamba/envs/fegrow/lib/python3.9/site-packages/torchani/resources/
failed to equip `nnpops` with error: No module named 'NNPOps'
Optimising conformer:   0%|                              | 0/18 [00:00<?, ?it/s]Optimising conformer:   6%|█▏                    | 1/18 [00:02<00:43,  2.57s/it]Optimising conformer:  11%|██▍                   | 2/18 [00:04<00:38,  2.43s/it]Optimising conformer:  17%|███▋                  | 3/18 [00:07<00:38,  2.57s/it]Optimising conformer:  22%|████▉                 | 4/18 [00:10<00:36,  2.60s/it]Optimising conformer:  28%|██████                | 5/18 [00:11<00:26,  2.05s/it]Optimising conformer:  33%|███████▎              | 6/18 [00:12<00:20,  1.74s/it]Optimising conformer:  39%|████████▌             | 7/18 [00:13<00:18,  1.64s/it]Optimising conformer:  44%|█████████▊            | 8/18 [00:15<00:15,  1.50s/it]Optimising conformer:  50%|███████████           | 9/18 [00:16<00:13,  1.49s/it]Optimising conformer:  56%|███████████▋         | 10/18 [00:18<00:11,  1.47s/it]Optimising conformer:  61%|████████████▊        | 11/18 [00:19<00:10,  1.53s/it]Optimising conformer:  67%|██████████████       | 12/18 [00:20<00:08,  1.41s/it]Optimising conformer:  72%|███████████████▏     | 13/18 [00:22<00:07,  1.40s/it]Optimising conformer:  78%|████████████████▎    | 14/18 [00:23<00:05,  1.33s/it]Optimising conformer:  83%|█████████████████▌   | 15/18 [00:25<00:04,  1.66s/it]Optimising conformer:  89%|██████████████████▋  | 16/18 [00:27<00:03,  1.59s/it]Optimising conformer:  94%|███████████████████▊ | 17/18 [00:29<00:01,  1.86s/it]Optimising conformer: 100%|█████████████████████| 18/18 [00:31<00:00,  1.74s/it]Optimising conformer: 100%|█████████████████████| 18/18 [00:31<00:00,  1.73s/it]
TIME Completed the molecule generation in 67.8s.
using ani2x
/mnt/storage/nobackup/nmb1063/mamba/envs/fegrow/lib/python3.9/site-packages/torchani/resources/
failed to equip `nnpops` with error: No module named 'NNPOps'
Optimising conformer:   0%|                               | 0/6 [00:00<?, ?it/s]Optimising conformer:  17%|███▊                   | 1/6 [00:02<00:11,  2.23s/it]Optimising conformer:  33%|███████▋               | 2/6 [00:03<00:06,  1.56s/it]Optimising conformer:  50%|███████████▌           | 3/6 [00:04<00:04,  1.60s/it]Optimising conformer:  67%|███████████████▎       | 4/6 [00:06<00:02,  1.40s/it]Optimising conformer:  83%|███████████████████▏   | 5/6 [00:07<00:01,  1.49s/it]Optimising conformer: 100%|███████████████████████| 6/6 [00:08<00:00,  1.36s/it]Optimising conformer: 100%|███████████████████████| 6/6 [00:08<00:00,  1.47s/it]
2024-01-19 09:24:31,119 - distributed.worker - ERROR - Failed to communicate with scheduler during heartbeat.
Traceback (most recent call last):
  File "/mnt/storage/nobackup/nmb1063/mamba/envs/fegrow/lib/python3.9/site-packages/tornado/iostream.py", line 861, in _read_to_buffer
    bytes_read = self.read_from_fd(buf)
  File "/mnt/storage/nobackup/nmb1063/mamba/envs/fegrow/lib/python3.9/site-packages/tornado/iostream.py", line 1116, in read_from_fd
    return self.socket.recv_into(buf, len(buf))
TimeoutError: [Errno 110] Connection timed out

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/mnt/storage/nobackup/nmb1063/mamba/envs/fegrow/lib/python3.9/site-packages/distributed/worker.py", line 1237, in heartbeat
    response = await retry_operation(
  File "/mnt/storage/nobackup/nmb1063/mamba/envs/fegrow/lib/python3.9/site-packages/distributed/utils_comm.py", line 434, in retry_operation
    return await retry(
  File "/mnt/storage/nobackup/nmb1063/mamba/envs/fegrow/lib/python3.9/site-packages/distributed/utils_comm.py", line 413, in retry
    return await coro()
  File "/mnt/storage/nobackup/nmb1063/mamba/envs/fegrow/lib/python3.9/site-packages/distributed/core.py", line 1227, in send_recv_from_rpc
    return await send_recv(comm=comm, op=key, **kwargs)
  File "/mnt/storage/nobackup/nmb1063/mamba/envs/fegrow/lib/python3.9/site-packages/distributed/core.py", line 986, in send_recv
    response = await comm.read(deserializers=deserializers)
  File "/mnt/storage/nobackup/nmb1063/mamba/envs/fegrow/lib/python3.9/site-packages/distributed/comm/tcp.py", line 241, in read
    convert_stream_closed_error(self, e)
  File "/mnt/storage/nobackup/nmb1063/mamba/envs/fegrow/lib/python3.9/site-packages/distributed/comm/tcp.py", line 142, in convert_stream_closed_error
    raise CommClosedError(f"in {obj}: {exc.__class__.__name__}: {exc}") from exc
distributed.comm.core.CommClosedError: in <TCP (closed) ConnectionPool.heartbeat_worker local=tcp://10.3.89.162:55610 remote=tcp://10.3.88.12:42763>: TimeoutError: [Errno 110] Connection timed out
2024-01-19 09:24:32,782 - distributed.worker - ERROR - Failed to communicate with scheduler during heartbeat.
Traceback (most recent call last):
  File "/mnt/storage/nobackup/nmb1063/mamba/envs/fegrow/lib/python3.9/site-packages/tornado/iostream.py", line 861, in _read_to_buffer
    bytes_read = self.read_from_fd(buf)
  File "/mnt/storage/nobackup/nmb1063/mamba/envs/fegrow/lib/python3.9/site-packages/tornado/iostream.py", line 1116, in read_from_fd
    return self.socket.recv_into(buf, len(buf))
TimeoutError: [Errno 110] Connection timed out

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/mnt/storage/nobackup/nmb1063/mamba/envs/fegrow/lib/python3.9/site-packages/distributed/worker.py", line 1237, in heartbeat
    response = await retry_operation(
  File "/mnt/storage/nobackup/nmb1063/mamba/envs/fegrow/lib/python3.9/site-packages/distributed/utils_comm.py", line 434, in retry_operation
    return await retry(
  File "/mnt/storage/nobackup/nmb1063/mamba/envs/fegrow/lib/python3.9/site-packages/distributed/utils_comm.py", line 413, in retry
    return await coro()
  File "/mnt/storage/nobackup/nmb1063/mamba/envs/fegrow/lib/python3.9/site-packages/distributed/core.py", line 1227, in send_recv_from_rpc
    return await send_recv(comm=comm, op=key, **kwargs)
  File "/mnt/storage/nobackup/nmb1063/mamba/envs/fegrow/lib/python3.9/site-packages/distributed/core.py", line 986, in send_recv
    response = await comm.read(deserializers=deserializers)
  File "/mnt/storage/nobackup/nmb1063/mamba/envs/fegrow/lib/python3.9/site-packages/distributed/comm/tcp.py", line 241, in read
    convert_stream_closed_error(self, e)
  File "/mnt/storage/nobackup/nmb1063/mamba/envs/fegrow/lib/python3.9/site-packages/distributed/comm/tcp.py", line 142, in convert_stream_closed_error
    raise CommClosedError(f"in {obj}: {exc.__class__.__name__}: {exc}") from exc
distributed.comm.core.CommClosedError: in <TCP (closed) ConnectionPool.heartbeat_worker local=tcp://10.3.89.162:55508 remote=tcp://10.3.88.12:42763>: TimeoutError: [Errno 110] Connection timed out
2024-01-19 09:24:42,126 - distributed.core - INFO - Connection to tcp://10.3.88.12:42763 has been closed.
2024-01-19 09:24:42,129 - distributed.worker - INFO - Stopping worker at tcp://10.3.89.162:46465. Reason: worker-handle-scheduler-connection-broken
2024-01-19 09:24:42,139 - distributed.nanny - INFO - Closing Nanny gracefully at 'tcp://10.3.89.162:38893'. Reason: worker-handle-scheduler-connection-broken
2024-01-19 09:24:42,157 - distributed.worker - ERROR - Failed to communicate with scheduler during heartbeat.
Traceback (most recent call last):
  File "/mnt/storage/nobackup/nmb1063/mamba/envs/fegrow/lib/python3.9/site-packages/distributed/core.py", line 1389, in _connect
    comm = await connect(
  File "/mnt/storage/nobackup/nmb1063/mamba/envs/fegrow/lib/python3.9/site-packages/distributed/comm/core.py", line 291, in connect
    comm = await asyncio.wait_for(
  File "/mnt/storage/nobackup/nmb1063/mamba/envs/fegrow/lib/python3.9/asyncio/tasks.py", line 466, in wait_for
    await waiter
asyncio.exceptions.CancelledError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/mnt/storage/nobackup/nmb1063/mamba/envs/fegrow/lib/python3.9/site-packages/distributed/worker.py", line 1237, in heartbeat
    response = await retry_operation(
  File "/mnt/storage/nobackup/nmb1063/mamba/envs/fegrow/lib/python3.9/site-packages/distributed/utils_comm.py", line 434, in retry_operation
    return await retry(
  File "/mnt/storage/nobackup/nmb1063/mamba/envs/fegrow/lib/python3.9/site-packages/distributed/utils_comm.py", line 413, in retry
    return await coro()
  File "/mnt/storage/nobackup/nmb1063/mamba/envs/fegrow/lib/python3.9/site-packages/distributed/core.py", line 1224, in send_recv_from_rpc
    comm = await self.pool.connect(self.addr)
  File "/mnt/storage/nobackup/nmb1063/mamba/envs/fegrow/lib/python3.9/site-packages/distributed/core.py", line 1468, in connect
    return await connect_attempt
  File "/mnt/storage/nobackup/nmb1063/mamba/envs/fegrow/lib/python3.9/site-packages/distributed/core.py", line 1412, in _connect
    raise CommClosedError(reason)
distributed.comm.core.CommClosedError: ConnectionPool closing.
2024-01-19 09:24:42,167 - distributed.nanny - INFO - Worker closed
2024-01-19 09:24:44,179 - distributed.nanny - ERROR - Worker process died unexpectedly
TIME Completed the molecule generation in 158.4s.
2024-01-19 09:24:46,734 - distributed.core - INFO - Connection to tcp://10.3.88.12:42763 has been closed.
2024-01-19 09:24:46,736 - distributed.worker - INFO - Stopping worker at tcp://10.3.89.162:36578. Reason: worker-handle-scheduler-connection-broken
2024-01-19 09:24:46,739 - distributed.nanny - INFO - Closing Nanny gracefully at 'tcp://10.3.89.162:37252'. Reason: worker-handle-scheduler-connection-broken
2024-01-19 09:24:46,747 - distributed.worker - ERROR - Failed to communicate with scheduler during heartbeat.
Traceback (most recent call last):
  File "/mnt/storage/nobackup/nmb1063/mamba/envs/fegrow/lib/python3.9/site-packages/distributed/core.py", line 1389, in _connect
    comm = await connect(
  File "/mnt/storage/nobackup/nmb1063/mamba/envs/fegrow/lib/python3.9/site-packages/distributed/comm/core.py", line 291, in connect
    comm = await asyncio.wait_for(
  File "/mnt/storage/nobackup/nmb1063/mamba/envs/fegrow/lib/python3.9/asyncio/tasks.py", line 466, in wait_for
    await waiter
asyncio.exceptions.CancelledError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/mnt/storage/nobackup/nmb1063/mamba/envs/fegrow/lib/python3.9/site-packages/distributed/worker.py", line 1237, in heartbeat
    response = await retry_operation(
  File "/mnt/storage/nobackup/nmb1063/mamba/envs/fegrow/lib/python3.9/site-packages/distributed/utils_comm.py", line 434, in retry_operation
    return await retry(
  File "/mnt/storage/nobackup/nmb1063/mamba/envs/fegrow/lib/python3.9/site-packages/distributed/utils_comm.py", line 413, in retry
    return await coro()
  File "/mnt/storage/nobackup/nmb1063/mamba/envs/fegrow/lib/python3.9/site-packages/distributed/core.py", line 1224, in send_recv_from_rpc
    comm = await self.pool.connect(self.addr)
  File "/mnt/storage/nobackup/nmb1063/mamba/envs/fegrow/lib/python3.9/site-packages/distributed/core.py", line 1468, in connect
    return await connect_attempt
  File "/mnt/storage/nobackup/nmb1063/mamba/envs/fegrow/lib/python3.9/site-packages/distributed/core.py", line 1412, in _connect
    raise CommClosedError(reason)
distributed.comm.core.CommClosedError: ConnectionPool closing.
2024-01-19 09:24:46,767 - distributed.nanny - INFO - Worker closed
2024-01-19 09:24:47,530 - distributed.nanny - INFO - Closing Nanny at 'tcp://10.3.89.162:38893'. Reason: nanny-close-gracefully
2024-01-19 09:24:48,770 - distributed.nanny - ERROR - Worker process died unexpectedly
TIME Completed the molecule generation in 211.8s.
2024-01-19 09:24:49,846 - distributed.nanny - INFO - Closing Nanny at 'tcp://10.3.89.162:37252'. Reason: nanny-close-gracefully
2024-01-19 09:24:49,848 - distributed.dask_worker - INFO - End worker
