hostname sb109.cluster
ipconfig 1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN group default qlen 1000 link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00 inet 127.0.0.1/8 scope host lo valid_lft forever preferred_lft forever inet6 ::1/128 scope host valid_lft forever preferred_lft forever 2: enp4s0f0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 9000 qdisc mq state UP group default qlen 1000 link/ether a0:8c:f8:34:c9:dc brd ff:ff:ff:ff:ff:ff inet 10.3.81.189/22 brd 10.3.83.255 scope global enp4s0f0 valid_lft forever preferred_lft forever inet6 fe80::a28c:f8ff:fe34:c9dc/64 scope link valid_lft forever preferred_lft forever 3: enp4s0f1: <BROADCAST,MULTICAST> mtu 1500 qdisc noop state DOWN group default qlen 1000 link/ether a0:8c:f8:34:c9:dd brd ff:ff:ff:ff:ff:ff 4: enp4s0f2: <BROADCAST,MULTICAST> mtu 1500 qdisc noop state DOWN group default qlen 1000 link/ether a0:8c:f8:34:c9:de brd ff:ff:ff:ff:ff:ff 5: enp4s0f3: <BROADCAST,MULTICAST> mtu 1500 qdisc noop state DOWN group default qlen 1000 link/ether a0:8c:f8:34:c9:df brd ff:ff:ff:ff:ff:ff 6: ib0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 4092 qdisc pfifo_fast state UP group default qlen 256 link/infiniband 80:00:00:29:fe:80:00:00:00:00:00:00:38:bc:01:03:00:4c:f5:e0 brd 00:ff:ff:ff:ff:12:40:1b:ff:ff:00:00:00:00:00:00:ff:ff:ff:ff inet 10.3.89.189/22 brd 10.3.91.255 scope global ib0 valid_lft forever preferred_lft forever inet 10.3.93.189/22 brd 10.3.95.255 scope global ib0:1 valid_lft forever preferred_lft forever inet6 fe80::3abc:103:4c:f5e0/64 scope link valid_lft forever preferred_lft forever 7: ib1: <NO-CARRIER,BROADCAST,MULTICAST,UP> mtu 4092 qdisc pfifo_fast state DOWN group default qlen 256 link/infiniband 80:00:00:29:fe:80:00:00:00:00:00:00:38:bc:01:03:00:4c:f5:e1 brd 00:ff:ff:ff:ff:12:40:1b:ff:ff:00:00:00:00:00:00:ff:ff:ff:ff
2024-01-19 08:19:24,871 - distributed.nanny - INFO -         Start Nanny at: 'tcp://10.3.89.189:44717'
2024-01-19 08:19:24,891 - distributed.nanny - INFO -         Start Nanny at: 'tcp://10.3.89.189:38326'
2024-01-19 08:19:26,683 - distributed.diskutils - INFO - Found stale lock file and directory '/scratch/dask-worker-space/worker-xc6d4m4a', purging
2024-01-19 08:19:26,683 - distributed.diskutils - INFO - Found stale lock file and directory '/scratch/dask-worker-space/worker-kx6qx4_t', purging
2024-01-19 08:19:33,522 - distributed.worker - INFO -       Start worker at:    tcp://10.3.89.189:37469
2024-01-19 08:19:33,523 - distributed.worker - INFO -          Listening to:    tcp://10.3.89.189:37469
2024-01-19 08:19:33,523 - distributed.worker - INFO -           Worker name:         SLURMCluster-170-1
2024-01-19 08:19:33,523 - distributed.worker - INFO -          dashboard at:          10.3.89.189:41641
2024-01-19 08:19:33,523 - distributed.worker - INFO - Waiting to connect to:     tcp://10.3.88.12:42763
2024-01-19 08:19:33,523 - distributed.worker - INFO - -------------------------------------------------
2024-01-19 08:19:33,523 - distributed.worker - INFO -       Start worker at:    tcp://10.3.89.189:38732
2024-01-19 08:19:33,523 - distributed.worker - INFO -               Threads:                          2
2024-01-19 08:19:33,523 - distributed.worker - INFO -          Listening to:    tcp://10.3.89.189:38732
2024-01-19 08:19:33,523 - distributed.worker - INFO -                Memory:                  10.24 GiB
2024-01-19 08:19:33,523 - distributed.worker - INFO -           Worker name:         SLURMCluster-170-0
2024-01-19 08:19:33,523 - distributed.worker - INFO -       Local Directory: /scratch/dask-worker-space/worker-5tx0rgct
2024-01-19 08:19:33,523 - distributed.worker - INFO -          dashboard at:          10.3.89.189:35905
2024-01-19 08:19:33,523 - distributed.worker - INFO - -------------------------------------------------
2024-01-19 08:19:33,523 - distributed.worker - INFO - Waiting to connect to:     tcp://10.3.88.12:42763
2024-01-19 08:19:33,523 - distributed.worker - INFO - -------------------------------------------------
2024-01-19 08:19:33,523 - distributed.worker - INFO -               Threads:                          2
2024-01-19 08:19:33,523 - distributed.worker - INFO -                Memory:                  10.24 GiB
2024-01-19 08:19:33,523 - distributed.worker - INFO -       Local Directory: /scratch/dask-worker-space/worker-a2tajb5j
2024-01-19 08:19:33,523 - distributed.worker - INFO - -------------------------------------------------
2024-01-19 08:19:33,606 - distributed.worker - INFO -         Registered to:     tcp://10.3.88.12:42763
2024-01-19 08:19:33,606 - distributed.worker - INFO - -------------------------------------------------
2024-01-19 08:19:33,607 - distributed.core - INFO - Starting established connection to tcp://10.3.88.12:42763
2024-01-19 08:19:33,609 - distributed.worker - INFO -         Registered to:     tcp://10.3.88.12:42763
2024-01-19 08:19:33,609 - distributed.worker - INFO - -------------------------------------------------
2024-01-19 08:19:33,610 - distributed.core - INFO - Starting established connection to tcp://10.3.88.12:42763
2024-01-19 09:24:03,654 - distributed.core - INFO - Connection to tcp://10.3.88.12:42763 has been closed.
2024-01-19 09:24:03,654 - distributed.core - INFO - Connection to tcp://10.3.88.12:42763 has been closed.
2024-01-19 09:24:03,668 - distributed.worker - INFO - Stopping worker at tcp://10.3.89.189:37469. Reason: worker-handle-scheduler-connection-broken
2024-01-19 09:24:03,668 - distributed.worker - INFO - Stopping worker at tcp://10.3.89.189:38732. Reason: worker-handle-scheduler-connection-broken
2024-01-19 09:24:03,672 - distributed.nanny - INFO - Closing Nanny gracefully at 'tcp://10.3.89.189:44717'. Reason: worker-handle-scheduler-connection-broken
2024-01-19 09:24:03,672 - distributed.nanny - INFO - Closing Nanny gracefully at 'tcp://10.3.89.189:38326'. Reason: worker-handle-scheduler-connection-broken
2024-01-19 09:24:03,675 - distributed.worker - ERROR - Failed to communicate with scheduler during heartbeat.
Traceback (most recent call last):
  File "/mnt/storage/nobackup/nmb1063/mamba/envs/fegrow/lib/python3.9/site-packages/distributed/comm/tcp.py", line 225, in read
    frames_nbytes = await stream.read_bytes(fmt_size)
tornado.iostream.StreamClosedError: Stream is closed

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/mnt/storage/nobackup/nmb1063/mamba/envs/fegrow/lib/python3.9/site-packages/distributed/worker.py", line 1237, in heartbeat
    response = await retry_operation(
  File "/mnt/storage/nobackup/nmb1063/mamba/envs/fegrow/lib/python3.9/site-packages/distributed/utils_comm.py", line 434, in retry_operation
    return await retry(
  File "/mnt/storage/nobackup/nmb1063/mamba/envs/fegrow/lib/python3.9/site-packages/distributed/utils_comm.py", line 413, in retry
    return await coro()
  File "/mnt/storage/nobackup/nmb1063/mamba/envs/fegrow/lib/python3.9/site-packages/distributed/core.py", line 1227, in send_recv_from_rpc
    return await send_recv(comm=comm, op=key, **kwargs)
  File "/mnt/storage/nobackup/nmb1063/mamba/envs/fegrow/lib/python3.9/site-packages/distributed/core.py", line 986, in send_recv
    response = await comm.read(deserializers=deserializers)
  File "/mnt/storage/nobackup/nmb1063/mamba/envs/fegrow/lib/python3.9/site-packages/distributed/comm/tcp.py", line 241, in read
    convert_stream_closed_error(self, e)
  File "/mnt/storage/nobackup/nmb1063/mamba/envs/fegrow/lib/python3.9/site-packages/distributed/comm/tcp.py", line 144, in convert_stream_closed_error
    raise CommClosedError(f"in {obj}: {exc}") from exc
distributed.comm.core.CommClosedError: in <TCP (closed) ConnectionPool.heartbeat_worker local=tcp://10.3.89.189:34124 remote=tcp://10.3.88.12:42763>: Stream is closed
2024-01-19 09:24:03,675 - distributed.worker - ERROR - Failed to communicate with scheduler during heartbeat.
Traceback (most recent call last):
  File "/mnt/storage/nobackup/nmb1063/mamba/envs/fegrow/lib/python3.9/site-packages/distributed/comm/tcp.py", line 225, in read
    frames_nbytes = await stream.read_bytes(fmt_size)
tornado.iostream.StreamClosedError: Stream is closed

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/mnt/storage/nobackup/nmb1063/mamba/envs/fegrow/lib/python3.9/site-packages/distributed/worker.py", line 1237, in heartbeat
    response = await retry_operation(
  File "/mnt/storage/nobackup/nmb1063/mamba/envs/fegrow/lib/python3.9/site-packages/distributed/utils_comm.py", line 434, in retry_operation
    return await retry(
  File "/mnt/storage/nobackup/nmb1063/mamba/envs/fegrow/lib/python3.9/site-packages/distributed/utils_comm.py", line 413, in retry
    return await coro()
  File "/mnt/storage/nobackup/nmb1063/mamba/envs/fegrow/lib/python3.9/site-packages/distributed/core.py", line 1227, in send_recv_from_rpc
    return await send_recv(comm=comm, op=key, **kwargs)
  File "/mnt/storage/nobackup/nmb1063/mamba/envs/fegrow/lib/python3.9/site-packages/distributed/core.py", line 986, in send_recv
    response = await comm.read(deserializers=deserializers)
  File "/mnt/storage/nobackup/nmb1063/mamba/envs/fegrow/lib/python3.9/site-packages/distributed/comm/tcp.py", line 241, in read
    convert_stream_closed_error(self, e)
  File "/mnt/storage/nobackup/nmb1063/mamba/envs/fegrow/lib/python3.9/site-packages/distributed/comm/tcp.py", line 144, in convert_stream_closed_error
    raise CommClosedError(f"in {obj}: {exc}") from exc
distributed.comm.core.CommClosedError: in <TCP (closed) ConnectionPool.heartbeat_worker local=tcp://10.3.89.189:34122 remote=tcp://10.3.88.12:42763>: Stream is closed
2024-01-19 09:24:03,682 - distributed.nanny - INFO - Worker closed
2024-01-19 09:24:03,682 - distributed.nanny - INFO - Worker closed
2024-01-19 09:24:05,918 - distributed.nanny - INFO - Closing Nanny at 'tcp://10.3.89.189:38326'. Reason: nanny-close-gracefully
2024-01-19 09:24:05,935 - distributed.nanny - INFO - Closing Nanny at 'tcp://10.3.89.189:44717'. Reason: nanny-close-gracefully
2024-01-19 09:24:05,936 - distributed.dask_worker - INFO - End worker
