hostname sb056.cluster
ipconfig 1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN group default qlen 1000 link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00 inet 127.0.0.1/8 scope host lo valid_lft forever preferred_lft forever inet6 ::1/128 scope host valid_lft forever preferred_lft forever 2: enp4s0f0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 9000 qdisc mq state UP group default qlen 1000 link/ether a0:8c:f8:74:c8:d8 brd ff:ff:ff:ff:ff:ff inet 10.3.81.136/22 brd 10.3.83.255 scope global enp4s0f0 valid_lft forever preferred_lft forever inet6 fe80::a28c:f8ff:fe74:c8d8/64 scope link valid_lft forever preferred_lft forever 3: enp4s0f1: <BROADCAST,MULTICAST> mtu 1500 qdisc noop state DOWN group default qlen 1000 link/ether a0:8c:f8:74:c8:d9 brd ff:ff:ff:ff:ff:ff 4: enp4s0f2: <BROADCAST,MULTICAST> mtu 1500 qdisc noop state DOWN group default qlen 1000 link/ether a0:8c:f8:74:c8:da brd ff:ff:ff:ff:ff:ff 5: enp4s0f3: <BROADCAST,MULTICAST> mtu 1500 qdisc noop state DOWN group default qlen 1000 link/ether a0:8c:f8:74:c8:db brd ff:ff:ff:ff:ff:ff 6: ib0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 4092 qdisc pfifo_fast state UP group default qlen 256 link/infiniband 80:00:00:29:fe:80:00:00:00:00:00:00:38:bc:01:03:00:4c:f6:30 brd 00:ff:ff:ff:ff:12:40:1b:ff:ff:00:00:00:00:00:00:ff:ff:ff:ff inet 10.3.89.136/22 brd 10.3.91.255 scope global ib0 valid_lft forever preferred_lft forever inet 10.3.97.136/22 brd 10.3.99.255 scope global ib0:1 valid_lft forever preferred_lft forever inet6 fe80::3abc:103:4c:f630/64 scope link valid_lft forever preferred_lft forever 7: ib1: <BROADCAST,MULTICAST> mtu 4092 qdisc noop state DOWN group default qlen 256 link/infiniband 80:00:00:29:fe:80:00:00:00:00:00:00:38:bc:01:03:00:4c:f6:31 brd 00:ff:ff:ff:ff:12:40:1b:ff:ff:00:00:00:00:00:00:ff:ff:ff:ff
2024-01-19 09:06:13,244 - distributed.nanny - INFO -         Start Nanny at: 'tcp://10.3.89.136:45023'
2024-01-19 09:06:13,305 - distributed.nanny - INFO -         Start Nanny at: 'tcp://10.3.89.136:39240'
2024-01-19 09:06:15,743 - distributed.diskutils - INFO - Found stale lock file and directory '/scratch/dask-worker-space/worker-ua9jg1je', purging
2024-01-19 09:06:15,744 - distributed.diskutils - INFO - Found stale lock file and directory '/scratch/dask-worker-space/worker-23ietity', purging
2024-01-19 09:06:29,419 - distributed.worker - INFO -       Start worker at:    tcp://10.3.89.136:43664
2024-01-19 09:06:29,419 - distributed.worker - INFO -          Listening to:    tcp://10.3.89.136:43664
2024-01-19 09:06:29,419 - distributed.worker - INFO -           Worker name:          SLURMCluster-38-1
2024-01-19 09:06:29,419 - distributed.worker - INFO -          dashboard at:          10.3.89.136:42799
2024-01-19 09:06:29,419 - distributed.worker - INFO - Waiting to connect to:     tcp://10.3.88.12:42763
2024-01-19 09:06:29,419 - distributed.worker - INFO -       Start worker at:    tcp://10.3.89.136:38076
2024-01-19 09:06:29,420 - distributed.worker - INFO - -------------------------------------------------
2024-01-19 09:06:29,420 - distributed.worker - INFO -          Listening to:    tcp://10.3.89.136:38076
2024-01-19 09:06:29,420 - distributed.worker - INFO -               Threads:                          2
2024-01-19 09:06:29,420 - distributed.worker - INFO -           Worker name:          SLURMCluster-38-0
2024-01-19 09:06:29,420 - distributed.worker - INFO -                Memory:                  10.24 GiB
2024-01-19 09:06:29,420 - distributed.worker - INFO -          dashboard at:          10.3.89.136:37990
2024-01-19 09:06:29,420 - distributed.worker - INFO -       Local Directory: /scratch/dask-worker-space/worker-nca4brqi
2024-01-19 09:06:29,420 - distributed.worker - INFO - Waiting to connect to:     tcp://10.3.88.12:42763
2024-01-19 09:06:29,420 - distributed.worker - INFO - -------------------------------------------------
2024-01-19 09:06:29,420 - distributed.worker - INFO - -------------------------------------------------
2024-01-19 09:06:29,420 - distributed.worker - INFO -               Threads:                          2
2024-01-19 09:06:29,420 - distributed.worker - INFO -                Memory:                  10.24 GiB
2024-01-19 09:06:29,420 - distributed.worker - INFO -       Local Directory: /scratch/dask-worker-space/worker-knec3lda
2024-01-19 09:06:29,420 - distributed.worker - INFO - -------------------------------------------------
2024-01-19 09:06:29,473 - distributed.worker - INFO -         Registered to:     tcp://10.3.88.12:42763
2024-01-19 09:06:29,473 - distributed.worker - INFO - -------------------------------------------------
2024-01-19 09:06:29,474 - distributed.core - INFO - Starting established connection to tcp://10.3.88.12:42763
2024-01-19 09:06:29,478 - distributed.worker - INFO -         Registered to:     tcp://10.3.88.12:42763
2024-01-19 09:06:29,478 - distributed.worker - INFO - -------------------------------------------------
2024-01-19 09:06:29,478 - distributed.core - INFO - Starting established connection to tcp://10.3.88.12:42763
2024-01-19 09:23:59,535 - distributed.core - INFO - Connection to tcp://10.3.88.12:42763 has been closed.
2024-01-19 09:23:59,535 - distributed.core - INFO - Connection to tcp://10.3.88.12:42763 has been closed.
2024-01-19 09:23:59,542 - distributed.worker - INFO - Stopping worker at tcp://10.3.89.136:38076. Reason: worker-handle-scheduler-connection-broken
2024-01-19 09:23:59,542 - distributed.worker - INFO - Stopping worker at tcp://10.3.89.136:43664. Reason: worker-handle-scheduler-connection-broken
2024-01-19 09:23:59,546 - distributed.nanny - INFO - Closing Nanny gracefully at 'tcp://10.3.89.136:45023'. Reason: worker-handle-scheduler-connection-broken
2024-01-19 09:23:59,547 - distributed.nanny - INFO - Closing Nanny gracefully at 'tcp://10.3.89.136:39240'. Reason: worker-handle-scheduler-connection-broken
2024-01-19 09:23:59,550 - distributed.worker - ERROR - Failed to communicate with scheduler during heartbeat.
Traceback (most recent call last):
  File "/mnt/storage/nobackup/nmb1063/mamba/envs/fegrow/lib/python3.9/site-packages/distributed/comm/tcp.py", line 225, in read
    frames_nbytes = await stream.read_bytes(fmt_size)
tornado.iostream.StreamClosedError: Stream is closed

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/mnt/storage/nobackup/nmb1063/mamba/envs/fegrow/lib/python3.9/site-packages/distributed/worker.py", line 1237, in heartbeat
    response = await retry_operation(
  File "/mnt/storage/nobackup/nmb1063/mamba/envs/fegrow/lib/python3.9/site-packages/distributed/utils_comm.py", line 434, in retry_operation
    return await retry(
  File "/mnt/storage/nobackup/nmb1063/mamba/envs/fegrow/lib/python3.9/site-packages/distributed/utils_comm.py", line 413, in retry
    return await coro()
  File "/mnt/storage/nobackup/nmb1063/mamba/envs/fegrow/lib/python3.9/site-packages/distributed/core.py", line 1227, in send_recv_from_rpc
    return await send_recv(comm=comm, op=key, **kwargs)
  File "/mnt/storage/nobackup/nmb1063/mamba/envs/fegrow/lib/python3.9/site-packages/distributed/core.py", line 986, in send_recv
    response = await comm.read(deserializers=deserializers)
  File "/mnt/storage/nobackup/nmb1063/mamba/envs/fegrow/lib/python3.9/site-packages/distributed/comm/tcp.py", line 241, in read
    convert_stream_closed_error(self, e)
  File "/mnt/storage/nobackup/nmb1063/mamba/envs/fegrow/lib/python3.9/site-packages/distributed/comm/tcp.py", line 144, in convert_stream_closed_error
    raise CommClosedError(f"in {obj}: {exc}") from exc
distributed.comm.core.CommClosedError: in <TCP (closed) ConnectionPool.heartbeat_worker local=tcp://10.3.89.136:53816 remote=tcp://10.3.88.12:42763>: Stream is closed
2024-01-19 09:23:59,549 - distributed.worker - ERROR - Failed to communicate with scheduler during heartbeat.
Traceback (most recent call last):
  File "/mnt/storage/nobackup/nmb1063/mamba/envs/fegrow/lib/python3.9/site-packages/distributed/comm/tcp.py", line 225, in read
    frames_nbytes = await stream.read_bytes(fmt_size)
tornado.iostream.StreamClosedError: Stream is closed

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/mnt/storage/nobackup/nmb1063/mamba/envs/fegrow/lib/python3.9/site-packages/distributed/worker.py", line 1237, in heartbeat
    response = await retry_operation(
  File "/mnt/storage/nobackup/nmb1063/mamba/envs/fegrow/lib/python3.9/site-packages/distributed/utils_comm.py", line 434, in retry_operation
    return await retry(
  File "/mnt/storage/nobackup/nmb1063/mamba/envs/fegrow/lib/python3.9/site-packages/distributed/utils_comm.py", line 413, in retry
    return await coro()
  File "/mnt/storage/nobackup/nmb1063/mamba/envs/fegrow/lib/python3.9/site-packages/distributed/core.py", line 1227, in send_recv_from_rpc
    return await send_recv(comm=comm, op=key, **kwargs)
  File "/mnt/storage/nobackup/nmb1063/mamba/envs/fegrow/lib/python3.9/site-packages/distributed/core.py", line 986, in send_recv
    response = await comm.read(deserializers=deserializers)
  File "/mnt/storage/nobackup/nmb1063/mamba/envs/fegrow/lib/python3.9/site-packages/distributed/comm/tcp.py", line 241, in read
    convert_stream_closed_error(self, e)
  File "/mnt/storage/nobackup/nmb1063/mamba/envs/fegrow/lib/python3.9/site-packages/distributed/comm/tcp.py", line 144, in convert_stream_closed_error
    raise CommClosedError(f"in {obj}: {exc}") from exc
distributed.comm.core.CommClosedError: in <TCP (closed) ConnectionPool.heartbeat_worker local=tcp://10.3.89.136:53814 remote=tcp://10.3.88.12:42763>: Stream is closed
2024-01-19 09:23:59,563 - distributed.nanny - INFO - Worker closed
2024-01-19 09:23:59,563 - distributed.nanny - INFO - Worker closed
2024-01-19 09:24:01,908 - distributed.nanny - INFO - Closing Nanny at 'tcp://10.3.89.136:45023'. Reason: nanny-close-gracefully
2024-01-19 09:24:01,909 - distributed.nanny - INFO - Closing Nanny at 'tcp://10.3.89.136:39240'. Reason: nanny-close-gracefully
2024-01-19 09:24:01,910 - distributed.dask_worker - INFO - End worker
